### ISSUE TITLE
vaadin 10 test failure

### ISSUE THREAD

**Issue by rjahn** [vaadin/framework#10151]
I tried out your starter app (beverage budy app) and used Eclipse Oxygen with an Embedded Tomcat8, with Java8. After starting the app in Chrome, following occured.

Servlet.service() for servlet [com.vaadin.server.startup.ServletDeployer] in context with path [/starterapp] threw exception [com.vaadin.server.ServiceException: java.lang.IllegalArgumentException: Unable to create an instance of 'com.vaadin.starter.beveragebuddy.ui.ReviewsList'. The constructor threw an exception.] with root cause
java.lang.IllegalStateException: Can't find resource 'frontend://reviews-list.html' via the servlet context
	at com.vaadin.ui.polymertemplate.DefaultTemplateParser.getTemplateContent(DefaultTemplateParser.java:104)
	at com.vaadin.ui.polymertemplate.TemplateInitializer.<init>(TemplateInitializer.java:133)
	at com.vaadin.ui.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:57)
	at com.vaadin.ui.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:70)
	at com.vaadin.starter.beveragebuddy.ui.ReviewsList.<init>(ReviewsList.java:71)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.vaadin.util.ReflectTools.createProxyInstance(ReflectTools.java:471)
	at com.vaadin.util.ReflectTools.createInstance(ReflectTools.java:439)
	at com.vaadin.flow.di.DefaultInstantiator.createRouteTarget(DefaultInstantiator.java:75)
	at com.vaadin.router.NavigationStateRenderer.lambda$getRouteTarget$94(NavigationStateRenderer.java:88)
	at java.util.Optional.orElseGet(Optional.java:267)
	at com.vaadin.router.NavigationStateRenderer.getRouteTarget(NavigationStateRenderer.java:87)
	at com.vaadin.router.NavigationStateRenderer.handle(NavigationStateRenderer.java:113)
	at com.vaadin.router.Router.navigate(Router.java:107)
	at com.vaadin.router.Router.initializeUI(Router.java:86)
	at com.vaadin.ui.UI.doInit(UI.java:194)
	at com.vaadin.server.BootstrapHandler.createAndInitUI(BootstrapHandler.java:770)
	at com.vaadin.server.BootstrapHandler.synchronizedHandleRequest(BootstrapHandler.java:246)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1455)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:294)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1533)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1489)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by pleku** [comment]
Issue moved to [vaadin/flow #2641](https://github.com/vaadin/flow/issues/2641) via [**ZenHub**](https://www.zenhub.com/)

**Comment by pleku** [comment]
Hello @rjahn, thanks for the report. I've closed the issue and moved it to vaadin/flow repository, since it is the correct place for it. (Could have also used vaadin/beverage-starter-flow repository)

This vaadin/framework repository is for Vaadin Framework (versions <= 8), and Vaadin 10 does not use the framework, but Vaadin Flow, which is in its own repository.

**Comment by rjahn** [comment]
Ah ok, was my mistake. Thanks!
