### ISSUE TITLE
ErrorHandler not being invoked for error thrown from async push thread

### ISSUE THREAD

**Issue by archiecobbs** [vaadin/framework#10297]
Vaadin 8.1.5.

A button click handler is throwing an exception, but this exception is completely swallowed, and not being delivered to our custom `ErrorHandler`. 

Here's the stack trace:

	...
	at com.example.MyView.editButtonClicked(MyView.java:223) ~[classes/:?]
	at com.example.MyView.lambda$addEditGridColumn$803c2f55$1(MyView.java:147) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510) ~[vaadin-server-8.1.5.jar:8.1.5]
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:211) ~[vaadin-server-8.1.5.jar:8.1.5]
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:174) ~[vaadin-server-8.1.5.jar:8.1.5]
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1033) ~[vaadin-server-8.1.5.jar:8.1.5]
	at com.vaadin.ui.renderers.ClickableRenderer.lambda$new$94333610$1(ClickableRenderer.java:138) ~[vaadin-server-8.1.5.jar:8.1.5]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155) ~[vaadin-server-8.1.5.jar:8.1.5]
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:116) ~[vaadin-server-8.1.5.jar:8.1.5]
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:445) ~[vaadin-server-8.1.5.jar:8.1.5]
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:410) ~[vaadin-server-8.1.5.jar:8.1.5]
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274) ~[vaadin-server-8.1.5.jar:8.1.5]
	at com.vaadin.server.communication.PushHandler.lambda$new$1(PushHandler.java:145) ~[vaadin-server-8.1.5.jar:8.1.5]
	at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:235) [vaadin-server-8.1.5.jar:8.1.5]
	at com.vaadin.server.communication.PushHandler.onMessage(PushHandler.java:520) [vaadin-server-8.1.5.jar:8.1.5]
	at com.vaadin.server.communication.PushAtmosphereHandler.onMessage(PushAtmosphereHandler.java:87) [vaadin-server-8.1.5.jar:8.1.5]
	at com.vaadin.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:77) [vaadin-server-8.1.5.jar:8.1.5]
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:223) [atmosphere-runtime-2.4.11.vaadin2.jar:2.4.11.vaadin2]
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:115) [atmosphere-runtime-2.4.11.vaadin2.jar:2.4.11.vaadin2]
	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:67) [atmosphere-runtime-2.4.11.vaadin2.jar:2.4.11.vaadin2]
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2284) [atmosphere-runtime-2.4.11.vaadin2.jar:2.4.11.vaadin2]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:593) [atmosphere-runtime-2.4.11.vaadin2.jar:2.4.11.vaadin2]
	at org.atmosphere.websocket.DefaultWebSocketProcessor$3.run(DefaultWebSocketProcessor.java:345) [atmosphere-runtime-2.4.11.vaadin2.jar:2.4.11.vaadin2]
	at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101) [atmosphere-runtime-2.4.11.vaadin2.jar:2.4.11.vaadin2]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:340) [atmosphere-runtime-2.4.11.vaadin2.jar:2.4.11.vaadin2]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:447) [atmosphere-runtime-2.4.11.vaadin2.jar:2.4.11.vaadin2]
	at org.atmosphere.container.JSR356Endpoint$3.onMessage(JSR356Endpoint.java:272) [atmosphere-runtime-2.4.11.vaadin2.jar:2.4.11.vaadin2]
	at org.atmosphere.container.JSR356Endpoint$3.onMessage(JSR356Endpoint.java:269) [atmosphere-runtime-2.4.11.vaadin2.jar:2.4.11.vaadin2]
	at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:394) [tomcat-websocket.jar:8.5.20]
	at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:119) [tomcat-websocket.jar:8.5.20]
	at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:495) [tomcat-websocket.jar:8.5.20]
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:294) [tomcat-websocket.jar:8.5.20]
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133) [tomcat-websocket.jar:8.5.20]
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:82) [tomcat-websocket.jar:8.5.20]
	at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:171) [tomcat-websocket.jar:8.5.20]
	at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:151) [tomcat-websocket.jar:8.5.20]
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148) [tomcat-websocket.jar:8.5.20]
	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54) [tomcat-coyote.jar:8.5.20]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53) [tomcat-coyote.jar:8.5.20]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-coyote.jar:8.5.20]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457) [tomcat-coyote.jar:8.5.20]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.20]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.20]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

**Comment by Legioth** [comment]
How can this be reproduced? This is my test code that seems to work as expected:
```
@Push
public class DemoUI extends UI {
    @WebServlet(value = "/*", asyncSupported = true)
    @VaadinServletConfiguration(ui = DemoUI.class, productionMode = false)
    public static class DemoServlet extends VaadinServlet {

    }

    @Override
    protected void init(VaadinRequest request) {
        Grid<String> grid = new Grid<>();
        grid.addColumn(value -> value, new ButtonRenderer<>(event -> {
            throw new RuntimeException();
        }));

        grid.setItems("foo");

        grid.setErrorHandler(new ErrorHandler() {
            @Override
            public void error(com.vaadin.server.ErrorEvent event) {
                System.out.println("Handling error for grid");
                event.getThrowable().printStackTrace();
            }
        });

        VerticalLayout layout = new VerticalLayout();

        layout.addComponent(grid);
        setContent(layout);
    }
}
```

**Comment by Legioth** [comment]
Without the error handler, I get a stacktrace with the relevant parts identical to the reported stacktrace. With the error handler, it is obviously invoked and the generic error handling logic is bypassed.
