### ISSUE TITLE
ConcurrentModificationException during push

### ISSUE THREAD

**Issue by markathomas** [vaadin/framework#10312]
Using 8.1.6 I am sporadically seeing push failing due to the following exception:
```
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
        at com.vaadin.ui.ConnectorTracker.getDirtyVisibleConnectors(ConnectorTracker.java:654)
        at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:94)
        at com.vaadin.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:168)
        ... 31 more
```

**Comment by Artur-** [comment]
Are you sure the session is locked correctly before accessing it from a background thread? It looks like a typical error caused by missing locking. Run server with -ea to find out

**Comment by markathomas** [comment]
yes, the call was made inside of UI.access(Runnable)

**Comment by markathomas** [comment]
Here is the full ST:
```
java.lang.RuntimeException: Push failed
        at com.vaadin.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:171)
        at com.vaadin.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:146)
        at com.vaadin.ui.UI.push(UI.java:1601)
        at com.vaadin.server.VaadinSession.unlock(VaadinSession.java:1025)
        at com.vaadin.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:1955)
        at com.vaadin.server.VaadinService.accessSession(VaadinService.java:1921)
        at com.vaadin.server.VaadinSession.access(VaadinSession.java:1416)
        at com.vaadin.ui.UI.access(UI.java:1494)
        at com.webit360.boxview.ui.BoxViewUI.access(BoxViewUI.java:387)
        at com.webit360.boxview.ui.dashboard.DividedFacilitiesGrid.handleDataProviderChangeEvent(DividedFacilitiesGrid.java:184)
        at com.webit360.boxview.ui.data.AbstractCacheDataProvider.lambda$notifyListeners$1(AbstractCacheDataProvider.java:253)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at com.webit360.boxview.ui.data.AbstractCacheDataProvider.notifyListeners(AbstractCacheDataProvider.java:253)
        at com.webit360.boxview.ui.data.AbstractEntityDataProvider.lambda$processChangeEvent$4(AbstractEntityDataProvider.java:138)
        at com.webit360.boxview.reactor.RunnableDelegate.run(RunnableDelegate.java:17)
        at com.webit360.boxview.reactor.RunnableSubscriber.onNext(RunnableSubscriber.java:36)
        at com.webit360.boxview.reactor.RunnableSubscriber.onNext(RunnableSubscriber.java:15)
        at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89)
        at reactor.core.publisher.EmitterProcessor.drain(EmitterProcessor.java:417)
        at reactor.core.publisher.EmitterProcessor.onNext(EmitterProcessor.java:265)
        at com.webit360.boxview.ui.data.AbstractEntityDataProvider.processChangeEvent(AbstractEntityDataProvider.java:139)
        at com.webit360.boxview.ui.data.AbstractEntityDataProvider.handleChangeNotificationEvent(AbstractEntityDataProvider.java:175)
        at sun.reflect.GeneratedMethodAccessor878.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:95)
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:154)
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:80)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at com.boxview.concurrency.LoggingRunnable.run(LoggingRunnable.java:21)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
        at com.vaadin.ui.ConnectorTracker.getDirtyVisibleConnectors(ConnectorTracker.java:654)
        at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:94)
        at com.vaadin.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:168)
        ... 31 more
```

**Comment by Legioth** [comment]
The trick here is to identify the code that modifies the collection that throws with the shown stacktrace at the same time that its being iterated.

The likely reason for this is that some other thread modifies it without holding the session lock. For more details on this case, see e.g. http://vaadinsolutions.blogspot.fi/2016/02/concurrentmodificationexception.html

The unlikely reason is that there's something on the same thread that modifies the collection while iterating. In this case, the only thing that seems to be run inside the iteration is `LegacyCommunicationManager.isConnectorVisibleToClient`, which means that there would be a connector that modifies state in `getParent()`, `isVisible()` or `isRendered(child)`.
