### ISSUE TITLE
Vaadin 8.2.0 Http status code 101 warning

### ISSUE THREAD

**Issue by tstsogoo** [vaadin/framework#10474]
`warning | 101 | GET /vaadinServlet/PUSH?v-uiId=0&v-pushId=...&X-Atmosphere-tracking-id=...&X-Atmosphere-Framework=2.3.2.vaadin1-javascript&X-Atmosphere-Transport=websocket&X-Atmosphere-TrackMessageSize=true&Content-Type=application/json;%20charset=UTF-8&X-atmo-protocol=true HTTP/1.1`
Spring-boot, let's encrypt, nginx, vaadin push

`@Push(transport = Transport.WEBSOCKET_XHR)`

**Comment by jtomass** [comment]
Do you have this in your nginx configuration file under server/location?

> proxy_http_version 1.1;  
> proxy_set_header Upgrade $http_upgrade;  
> proxy_set_header Connection "upgrade"; 

You can look at this document about [proxying websockets with nginx](https://chrislea.com/2013/02/23/proxying-websockets-with-nginx/) for more information.

**Comment by tstsogoo** [comment]
```
#ATTENTION!
#
#DO NOT MODIFY THIS FILE BECAUSE IT WAS GENERATED AUTOMATICALLY,
#SO ALL YOUR CHANGES WILL BE LOST THE NEXT TIME THE FILE IS GENERATED.

server {
        listen xxx.xxx.xxx.xxx:443 ssl http2;

        server_name example.mn;
        server_name www.example.mn;
        server_name ipv4.example.mn;

        ssl_certificate             /opt/psa/var/certificates/cert-HtaT9k;
        ssl_certificate_key         /opt/psa/var/certificates/cert-HtaT9k;
        ssl_client_certificate      /opt/psa/var/certificates/cert-4M1dWh;

        client_max_body_size 128m;

        # disable unsupported ciphers
        ssl_ciphers AESGCM:HIGH:!aNULL:!MD5;

        # ssl optimizations
        ssl_session_cache shared:SSL:60m;
        ssl_session_timeout 60m;
        add_header Strict-Transport-Security "max-age=31536000";

        root "/var/www/vhosts/example.mn/httpdocs";
        access_log "/var/www/vhosts/system/example.mn/logs/proxy_access_ssl_log";
        error_log "/var/www/vhosts/system/example.mn/logs/proxy_error_log";
#       return 503;
        if ($host ~* ^www\.example\.mn$) {
                return 301 https://example.mn$request_uri;
                #rewrite ^(.*)$ https://example.mn$1 permanent;
        }

        # %23 гэсэн байдлаар орж ирсэн # тэмдэгтийг чиглүүлэх
        rewrite ^(.*)\#(.*)$ $1#$2 redirect;

        location / {
                proxy_pass              https://xxx.xxx.xxx.xxx:801;
                proxy_set_header        Host             $host:443;
                proxy_set_header        X-Real-IP        $remote_addr;
                proxy_set_header        X-Forwarded-For  $proxy_add_x_forwarded_for;
                proxy_set_header        X-Accel-Internal /internal-nginx-static-location;
                proxy_set_header        Upgrade         $http_upgrade;
                proxy_set_header        Connection      "upgrade";

                proxy_http_version 1.1;
                proxy_connect_timeout   300;
                proxy_read_timeout      84600s;
                proxy_send_timeout      84600s;
        }

        location /vaadinServlet/PUSH {
               proxy_set_header          X-Forwarded-Host        $host;
               proxy_set_header          X-Forwarded-Server      $host;
               proxy_set_header          X-Real-IP               $remote_addr;
               proxy_set_header          X-Forwarded-For         $proxy_add_x_forwarded_for;
               proxy_set_header          Host                    $host;
               proxy_http_version        1.1;
               proxy_set_header          Upgrade                 $http_upgrade;
               proxy_set_header          Connection              $connection_upgrade;
               proxy_buffering           off;
               proxy_ignore_client_abort off;
               proxy_pass                https://xxx.xxx.xxx.xxx:801;
               proxy_read_timeout 84600s;
               proxy_send_timeout 84600s;
               proxy_redirect off;
        }
#        location /VAADIN {
#               proxy_set_header X-Forwarded-Host $host;
#               proxy_set_header X-Forwarded-Server $host;
#               proxy_set_header X-Real-IP $remote_addr;
#               proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#               proxy_set_header Host $host;
#               proxy_http_version        1.1;
#               proxy_set_header          Upgrade $http_upgrade;
#               proxy_set_header          Connection $connection_upgrade;
#               proxy_buffering           off;
#               proxy_ignore_client_abort off;
#               proxy_pass                https://xxx.xxx.xxx.xxx:801;
#               proxy_read_timeout 84600s;
#               proxy_send_timeout 84600s;
#               proxy_redirect off;
#        }

        location /internal-nginx-static-location/ {
                alias /var/www/vhosts/example.mn/httpdocs/;
                internal;
        }

        location ~ ^/(plesk-stat|awstats-icon|webstat|webstat-ssl|ftpstat|anon_ftpstat) {
                proxy_pass https://xxx.xxx.xxx.xxx:7081;
                proxy_set_header Host             $host;
                proxy_set_header X-Real-IP        $remote_addr;
                proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
                proxy_set_header X-Accel-Internal /internal-nginx-static-location;
                access_log off;
        }

        add_header X-Powered-By PleskLin;

        include "/var/www/vhosts/system/example.mn/conf/vhost_nginx.conf";
}
# Vaadin PUSH
map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
}

```

**Comment by tstsogoo** [comment]
we get same time this error on backend
```
java.io.IOException: Unable to unwrap data, invalid status [CLOSED]
        at org.apache.tomcat.util.net.SecureNioChannel.read(SecureNioChannel.java:618)
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1248)
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1221)
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.read(NioEndpoint.java:1194)
        at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:72)
        at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:171)
        at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:151)
        at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148)
        at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
```
