### ISSUE TITLE
Can upgrade to vaadin 8 via vaadin-maven-plugin

### ISSUE THREAD

**Issue by beerni** [vaadin/framework#10631]
Using the vaadin upgrade plugin (v.8.0.6)  I cannot upgrade from vaadin 7 to vaadin 8. 

The maven-plugin is trying to download the framework-migration-tool-8.0-SNAPSHOT.jar which is no longer available in (https://oss.sonatype.org/content/repositories/vaadin-snapshots/com/vaadin/framework8-migration-tool/8.0-SNAPSHOT/framework8-migration-tool-8.0-SNAPSHOT.jar)

Which results in a Migration to vaadin 8 failed. 

Logs: 
```

Downloading: https://oss.sonatype.org/content/repositories/vaadin-snapshots/com/vaadin/framework8-migration-tool/8.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata com.vaadin:framework8-migration-tool:8.0-SNAPSHOT/maven-metadata.xml from/to vaadin-snapshots (https://oss.sonatype.org/content/repositories/vaadin-snapshots): oss.sonatype.org
Downloading: https://oss.sonatype.org/content/repositories/vaadin-snapshots/com/vaadin/framework8-migration-tool/8.0-SNAPSHOT/framework8-migration-tool-8.0-SNAPSHOT.jar
[ERROR] Migration to Vaadin 8 failed
org.apache.maven.plugin.MojoExecutionException: Failed to resolve artifact
	at com.vaadin.integration.maven.Vaadin8UpgradeMojo.getMigrationJarFile(Vaadin8UpgradeMojo.java:52)
	at com.vaadin.integration.maven.Vaadin8UpgradeMojo.doExecute(Vaadin8UpgradeMojo.java:79)
	at org.codehaus.mojo.gwt.shell.AbstractGwtShellMojo.execute(AbstractGwtShellMojo.java:182)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: org.apache.maven.artifact.resolver.ArtifactResolutionException: Could not transfer artifact com.vaadin:framework8-migration-tool:jar:8.0-SNAPSHOT from/to vaadin-snapshots (https://oss.sonatype.org/content/repositories/vaadin-snapshots): oss.sonatype.org
  com.vaadin:framework8-migration-tool:jar:8.0-SNAPSHOT

from the specified remote repositories:
  vaadin-snapshots (https://oss.sonatype.org/content/repositories/vaadin-snapshots, releases=false, snapshots=true)

	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:225)
	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:154)
	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:555)
	at com.vaadin.integration.maven.Vaadin8UpgradeMojo.getMigrationJarFile(Vaadin8UpgradeMojo.java:48)
	... 30 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact com.vaadin:framework8-migration-tool:jar:8.0-SNAPSHOT from/to vaadin-snapshots (https://oss.sonatype.org/content/repositories/vaadin-snapshots): oss.sonatype.org
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:215)
	... 33 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact com.vaadin:framework8-migration-tool:jar:8.0-SNAPSHOT from/to vaadin-snapshots (https://oss.sonatype.org/content/repositories/vaadin-snapshots): oss.sonatype.org
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:43)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 37 more
Caused by: org.apache.maven.wagon.TransferFailedException: oss.sonatype.org
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1066)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:960)
	at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
	at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
	at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
	at org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:560)
	at org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:427)
	at org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:404)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:447)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:350)
	... 42 more
Caused by: java.net.UnknownHostException: oss.sonatype.org
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.maven.wagon.providers.http.httpclient.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:44)
	at org.apache.maven.wagon.providers.http.httpclient.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:101)
	at org.apache.maven.wagon.providers.http.httpclient.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:318)
	at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.maven.wagon.providers.http.httpclient.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.maven.wagon.providers.http.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.execute(AbstractHttpClientWagon.java:832)
	at org.apache.maven.wagon.providers.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:983)
	... 51 more
```

**Comment by tsuoanttila** [comment]
Based on a quick check, there are `framework8-migration-tool` snapshots in the repository. The following part from the stacktrace caught my attention:
```
Caused by: java.net.UnknownHostException: oss.sonatype.org
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
```

That sounds like there's an issue resolving the address of `oss.sonatype.org` which would definitely lead into not being able to download the migration tool.

**Comment by beerni** [comment]
Exactly, behind a proxy I cannot access to sonatype do download the packages. 
I can access via web and via the intellij check connection feature.

**Comment by elmot** [comment]
I see three ways to resolve the issue:
- try to install the plugin locally, using https://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html
- try to use proxy if it is set up for your network.
https://maven.apache.org/guides/mini/guide-proxies.html
- try to run the migration tool without maven 
https://github.com/vaadin/framework8-migration-tool

I close the issue because the case is not an issue of the framework. If none of the listed works, please open a ticket at [migration tool repo](https://github.com/vaadin/framework8-migration-tool) or at [maven plugin repo](https://github.com/vaadin/maven-plugin)
