### ISSUE TITLE
Vaadin 8.3.2 raises: IllegalArgumentException: Duplicate ID for columns

### ISSUE THREAD

**Issue by dmarko484** [vaadin/framework#10723]
We upgraded Vaadin from 8.3.1 to 8.3.2 on several projects and we  are constantly  getting error when using several Grid views on different pages. 

**Error says:**
> IllegalArgumentException: Duplicate ID for columns

Scenario:
- we open tab with grid on it ... its ok now
- then we click on another tab with another grid and now it raises error as below

From debugger we can see strange behaviour that  Vaadin mixes 'somehow' grid view classes together among components ...

Applications are running fine since 8.0.0 so it must me something wrong in 8.3.2 release. Rolling back to 8.3.1 fixes the issue.

```
at com.vaadin.ui.Grid$Column.setId(Grid.java:1162)
at com.vaadin.ui.Grid.setColumnId(Grid.java:4639)
Caused by: java.lang.IllegalArgumentException: Duplicate ID for columns
... 62 more
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
at java.lang.reflect.Method.invoke(Method.java:498)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at com.vaadin.ui.Tree.lambda$new$c61d0278$1(Tree.java:300)
at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1014)
at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237)
at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273)
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:519)
Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method itemClick in app.modules.vk.VkModule$$Lambda$135/1491981203 failed.
... 57 more
at com.vaadin.ui.Grid$GridServerRpcImpl.itemClick(Grid.java:631)
at com.vaadin.ui.Grid.access$500(Grid.java:142)
at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1014)
at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237)
at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273)
at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:519)
Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method itemClick in com.vaadin.ui.Tree$$Lambda$112/844844724 failed.
... 52 more
at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155)
at java.lang.reflect.Method.invoke(Method.java:498)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.Thread.run(Thread.java:748)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:208)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:445)
at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1601)
at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90)
at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274)
at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:410)
at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:445)
at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:116)
at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:159)
com.vaadin.server.ServerRpcManager$RpcInvocationException: Unable to invoke method itemClick in com.vaadin.shared.ui.grid.GridServerRpc
```

**Comment by elmot** [comment]
Please provide a code snippet to reproduce the issue.

**Comment by dmarko484** [comment]
Hmm, apps are quite complited and related to db. We have several apps that were working fine since Vaadin 8.0.0 with every release. Now it broke several different apps for us.  Will have to look if I can create a small demo somehow ...

**Comment by anasmi** [comment]
Are you initializing you grids in **attach** method or how do you do it?
