### ISSUE TITLE
Update Atmosphere in Vaadin 8.4 to 2.4.23 (or later)

### ISSUE THREAD

**Issue by kkolinko** [vaadin/framework#10816]
Vaadin master was updated to Atmosphere 2.4.21.vaadin1 in commit d5ad32c20249f1eb91b5b7ad42ee770abf4c8803 (PR #10706)

This version of Atmosphere has a bug that manifests when running on Apache Tomcat.
This is a regression, it was fixed in 2.4.22 and 2.4.23.
Please upgrade to Atmosphere 2.4.23 (or later) before releasing Vaadin 8.4.0.

The necessary changes are the same as in d5ad32c20249f1eb91b5b7ad42ee770abf4c8803 (PR #10706), but somebody should build and publish a "vaadin" flavor of Atmosphere to be used here.

My current workaround is downgrading to "Atmosphere 2.4.11.vaadin4" (the latest earlier version available from Maven Central).

## Technical details

Atmosphere bug:
https://github.com/Atmosphere/atmosphere/issues/2320

Tested with Vaadin Framework 8.4-SNAPSHOT (built 2018-04-03, several commits after 8.4.0.alpha1 tag).
When running on Apache Tomcat 8.5.29, web application print the following log message at startup:

```
Apr 03, 2018 11:35:11 AM org.atmosphere.cpr.DefaultAsyncSupportResolver newCometSupport
SEVERE: Real error: The path [/{path0}/] contains one or more empty segments which are is not permitted
java.lang.IllegalArgumentException: The path [/{path0}/] contains one or more empty segments which are is not permitted
	at org.apache.tomcat.websocket.server.UriTemplate.<init>(UriTemplate.java:71)
	at org.apache.tomcat.websocket.server.WsServerContainer.addEndpoint(WsServerContainer.java:155)
	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:99)
	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:42)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.newCometSupport(DefaultAsyncSupportResolver.java:237)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolveWebSocket(DefaultAsyncSupportResolver.java:308)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolve(DefaultAsyncSupportResolver.java:294)
	at org.atmosphere.cpr.AtmosphereFramework.autoDetectContainer(AtmosphereFramework.java:2085)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:914)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:838)
	at com.vaadin.server.communication.PushRequestHandler.initAtmosphere(PushRequestHandler.java:212)
	at com.vaadin.server.communication.JSR356WebsocketInitializer.initAtmosphereForVaadinServlet(JSR356WebsocketInitializer.java:152)
	at com.vaadin.server.communication.JSR356WebsocketInitializer.contextInitialized(JSR356WebsocketInitializer.java:118)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4753)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5215)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1421)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1411)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

This issue is not fatal. The exception is caught in DefaultAsyncSupportResolver.newCometSupport() and consumed, and the framework switches over to implementation based on Servlet 3.0 Async API:
```
...
Apr 03, 2018 12:41:17 PM org.atmosphere.cpr.AtmosphereFramework info
INFO: Atmosphere is using async support: org.atmosphere.container.Servlet30CometSupport running
```

**Comment by ScreamingTree86** [comment]
I switched recently to 8.4.0 final with spring boot and use the push support. In 8.3.3 everyting works as expected with the well known 
``` 2018-04-26 15:22:36.032  WARN 15524 --- [nio-8080-exec-8] org.atmosphere.util.IOUtils              : More than one Servlet Mapping defined. WebSocket may not work org.apache.catalina.core.ApplicationServletRegistration@63de78f6 ``` warning.
After the switch i get the following stacktrace on startup:

```2018-04-26 15:22:29.411  INFO 15524 --- [nio-8080-exec-1] o.v.s.s.Vaadin4SpringServletService      : Using custom Vaadin4Spring servlet service
2018-04-26 15:22:29.443  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Installed AtmosphereHandler com.vaadin.server.communication.PushAtmosphereHandler mapped to context-path: /*
2018-04-26 15:22:29.443  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Installed the following AtmosphereInterceptor mapped to AtmosphereHandler com.vaadin.server.communication.PushAtmosphereHandler
2018-04-26 15:22:29.474  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Atmosphere is using org.atmosphere.util.VoidAnnotationProcessor for processing annotation
2018-04-26 15:22:29.489  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.util.ForkJoinPool         : Using ForkJoinPool  java.util.concurrent.ForkJoinPool. Set the org.atmosphere.cpr.broadcaster.maxAsyncWriteThreads to -1 to fully use its power.
2018-04-26 15:22:29.489  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Installed WebSocketProtocol org.atmosphere.websocket.protocol.SimpleHttpProtocol 
2018-04-26 15:22:29.489  WARN 15524 --- [nio-8080-exec-1] org.atmosphere.util.IOUtils              : More than one Servlet Mapping defined. WebSocket may not work org.apache.catalina.core.ApplicationServletRegistration@5e17c4c4
2018-04-26 15:22:29.489  INFO 15524 --- [nio-8080-exec-1] o.a.container.JSR356AsyncSupport         : JSR 356 Mapping path /vaadinServlet
2018-04-26 15:22:29.505  WARN 15524 --- [nio-8080-exec-1] o.a.cpr.DefaultAsyncSupportResolver      : Failed to create AsyncSupport class: class org.atmosphere.container.JSR356AsyncSupport, error: java.lang.reflect.InvocationTargetException
2018-04-26 15:22:29.505 ERROR 15524 --- [nio-8080-exec-1] o.a.cpr.DefaultAsyncSupportResolver      : Real error: The path [/vaadinServlet/{path0}/] contains one or more empty segments which are is not permitted

java.lang.IllegalArgumentException: The path [/vaadinServlet/{path0}/] contains one or more empty segments which are is not permitted
	at org.apache.tomcat.websocket.server.UriTemplate.<init>(UriTemplate.java:71) ~[tomcat-embed-websocket-8.5.29.jar:8.5.29]
	at org.apache.tomcat.websocket.server.WsServerContainer.addEndpoint(WsServerContainer.java:155) ~[tomcat-embed-websocket-8.5.29.jar:8.5.29]
	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:99) ~[atmosphere-runtime-2.4.21.vaadin1.jar:2.4.21.vaadin1]
	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:42) ~[atmosphere-runtime-2.4.21.vaadin1.jar:2.4.21.vaadin1]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_151]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_151]
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.newCometSupport(DefaultAsyncSupportResolver.java:237) [atmosphere-runtime-2.4.21.vaadin1.jar:2.4.21.vaadin1]
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolveWebSocket(DefaultAsyncSupportResolver.java:308) [atmosphere-runtime-2.4.21.vaadin1.jar:2.4.21.vaadin1]
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolve(DefaultAsyncSupportResolver.java:294) [atmosphere-runtime-2.4.21.vaadin1.jar:2.4.21.vaadin1]
	at org.atmosphere.cpr.AtmosphereFramework.autoDetectContainer(AtmosphereFramework.java:2085) [atmosphere-runtime-2.4.21.vaadin1.jar:2.4.21.vaadin1]
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:914) [atmosphere-runtime-2.4.21.vaadin1.jar:2.4.21.vaadin1]
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:838) [atmosphere-runtime-2.4.21.vaadin1.jar:2.4.21.vaadin1]
	at com.vaadin.server.communication.PushRequestHandler.initAtmosphere(PushRequestHandler.java:212) [vaadin-server-8.4.0.jar:8.4.0]
	at com.vaadin.server.communication.PushRequestHandler.<init>(PushRequestHandler.java:80) [vaadin-server-8.4.0.jar:8.4.0]
	at com.vaadin.server.VaadinServletService.createRequestHandlers(VaadinServletService.java:68) [vaadin-server-8.4.0.jar:8.4.0]
	at com.vaadin.spring.server.SpringVaadinServletService.createRequestHandlers(SpringVaadinServletService.java:63) [vaadin-spring-3.0.0.jar:3.0.0]
	at com.vaadin.server.VaadinService.init(VaadinService.java:216) [vaadin-server-8.4.0.jar:8.4.0]
	at org.vaadin.spring.servlet.Vaadin4SpringServlet.createServletService(Vaadin4SpringServlet.java:74) [vaadin-spring-ext-core-2.0.0.RELEASE.jar:na]
	at com.vaadin.server.VaadinServlet.createServletService(VaadinServlet.java:377) [vaadin-server-8.4.0.jar:8.4.0]
	at com.vaadin.server.VaadinServlet.init(VaadinServlet.java:207) [vaadin-server-8.4.0.jar:8.4.0]
	at org.vaadin.spring.servlet.Vaadin4SpringServlet.init(Vaadin4SpringServlet.java:66) [vaadin-spring-ext-core-2.0.0.RELEASE.jar:na]
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:789) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:133) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]

2018-04-26 15:22:29.521  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Installing Default AtmosphereInterceptors
2018-04-26 15:22:29.521  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : 	org.atmosphere.interceptor.CorsInterceptor : CORS Interceptor Support
2018-04-26 15:22:29.521  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : 	org.atmosphere.interceptor.CacheHeadersInterceptor : Default Response's Headers Interceptor
2018-04-26 15:22:29.521  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : 	org.atmosphere.interceptor.PaddingAtmosphereInterceptor : Browser Padding Interceptor Support
2018-04-26 15:22:29.521  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : 	org.atmosphere.interceptor.AndroidAtmosphereInterceptor : Android Interceptor Support
2018-04-26 15:22:29.521  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Dropping Interceptor org.atmosphere.interceptor.HeartbeatInterceptor
2018-04-26 15:22:29.521  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : 	org.atmosphere.interceptor.SSEAtmosphereInterceptor : SSE Interceptor Support
2018-04-26 15:22:29.521  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : 	org.atmosphere.interceptor.JSONPAtmosphereInterceptor : JSONP Interceptor Support
2018-04-26 15:22:29.521  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : 	org.atmosphere.interceptor.JavaScriptProtocol : Atmosphere JavaScript Protocol
2018-04-26 15:22:29.521  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : 	org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor : org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor
2018-04-26 15:22:29.521  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : 	org.atmosphere.interceptor.OnDisconnectInterceptor : Browser disconnection detection
2018-04-26 15:22:29.521  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : 	org.atmosphere.interceptor.IdleResourceInterceptor : org.atmosphere.interceptor.IdleResourceInterceptor
2018-04-26 15:22:29.521  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Set org.atmosphere.cpr.AtmosphereInterceptor.disableDefaults to disable them.
2018-04-26 15:22:29.521  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Installed AtmosphereInterceptor CORS Interceptor Support with priority FIRST_BEFORE_DEFAULT 
2018-04-26 15:22:29.536  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Installed AtmosphereInterceptor Default Response's Headers Interceptor with priority AFTER_DEFAULT 
2018-04-26 15:22:29.536  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Installed AtmosphereInterceptor Browser Padding Interceptor Support with priority AFTER_DEFAULT 
2018-04-26 15:22:29.536  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Installed AtmosphereInterceptor Android Interceptor Support with priority AFTER_DEFAULT 
2018-04-26 15:22:29.536  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Installed AtmosphereInterceptor SSE Interceptor Support with priority AFTER_DEFAULT 
2018-04-26 15:22:29.536  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Installed AtmosphereInterceptor JSONP Interceptor Support with priority AFTER_DEFAULT 
2018-04-26 15:22:29.536  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Installed AtmosphereInterceptor Atmosphere JavaScript Protocol with priority AFTER_DEFAULT 
2018-04-26 15:22:29.536  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Installed AtmosphereInterceptor org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor with priority AFTER_DEFAULT 
2018-04-26 15:22:29.536  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Installed AtmosphereInterceptor Browser disconnection detection with priority AFTER_DEFAULT 
2018-04-26 15:22:29.536  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Installed AtmosphereInterceptor org.atmosphere.interceptor.IdleResourceInterceptor with priority BEFORE_DEFAULT 
2018-04-26 15:22:29.536  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Using EndpointMapper class org.atmosphere.util.DefaultEndpointMapper
2018-04-26 15:22:29.536  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Using BroadcasterCache: org.atmosphere.cache.UUIDBroadcasterCache
2018-04-26 15:22:29.536  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Default Broadcaster Class: org.atmosphere.cpr.DefaultBroadcaster
2018-04-26 15:22:29.536  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Broadcaster Shared List Resources: false
2018-04-26 15:22:29.536  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Broadcaster Polling Wait Time 100
2018-04-26 15:22:29.536  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Shared ExecutorService supported: true
2018-04-26 15:22:29.552  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Messaging ExecutorService Pool Size unavailable - Not instance of ThreadPoolExecutor
2018-04-26 15:22:29.552  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Async I/O Thread Pool Size: 200
2018-04-26 15:22:29.552  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Using BroadcasterFactory: org.atmosphere.cpr.DefaultBroadcasterFactory
2018-04-26 15:22:29.552  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Using AtmosphereResurceFactory: org.atmosphere.cpr.DefaultAtmosphereResourceFactory
2018-04-26 15:22:29.552  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Using WebSocketProcessor: org.atmosphere.websocket.DefaultWebSocketProcessor
2018-04-26 15:22:29.552  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Invoke AtmosphereInterceptor on WebSocket message true
2018-04-26 15:22:29.552  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : HttpSession supported: true
2018-04-26 15:22:29.552  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Atmosphere is using org.atmosphere.inject.InjectableObjectFactory for dependency injection and object creation
2018-04-26 15:22:29.552  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Atmosphere is using async support: org.atmosphere.container.Servlet30CometSupport running under container: Apache Tomcat/8.5.29 using javax.servlet/3.0
2018-04-26 15:22:29.552  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Atmosphere Framework 2.4.21.vaadin1 started.
2018-04-26 15:22:29.552  INFO 15524 --- [nio-8080-exec-1] org.atmosphere.cpr.AtmosphereFramework   : Installed AtmosphereInterceptor  Track Message Size Interceptor using | with priority BEFORE_DEFAULT ```

In addition i get: 
``` 2018-04-26 15:22:36.032  WARN 15524 --- [nio-8080-exec-8] org.atmosphere.util.IOUtils              : More than one Servlet Mapping defined. WebSocket may not work org.apache.catalina.core.ApplicationServletRegistration@63de78f6
2018-04-26 15:22:36.039  WARN 15524 --- [nio-8080-exec-8] o.atmosphere.cpr.AsynchronousProcessor   : Websocket protocol not supported
2018-04-26 15:22:36.039  WARN 15524 --- [nio-8080-exec-8] o.a.w.protocol.SimpleHttpProtocol        : Status code higher or equal than 400. Unable to deliver the websocket messages to installed component. Status 501 Message OK
 ```
For every user which connects. After this push does not work anymore with no exception is thrown.

**Comment by TatuLund** [comment]
@ScreamingTree86  Pullrequest #10847 has not been merged yet, 8.4.0 does not contain the fix, so this was expected.

**Comment by ScreamingTree86** [comment]
@TatuLund  I see. Just wanted to point it out, so that nobody needs to debug the hell out of their code. 

Maybe it would be a good idea to put the info, that push does not work in 8.4.0, in the release information.

**Comment by elmot** [comment]
The issue is still open, that means is is not fixed. 
According to our process, if the issue is fixed and the fix is included into a build, then the issue is marked closed and assigned to a *closed* milestone.

**Comment by andersforsell** [comment]
I was also bitten by this issue when upgrading to 8.4. Would have been good to see this as a "known issue" along with the set of new features.

**Comment by elmot** [comment]
@kkolinko , can you, please, test upgrade to `atmosphere-2.4.24.vaadin1`?

**Comment by tsuoanttila** [comment]
8.4.1 has been released. Please comment if there are still issues.

**Comment by kkolinko** [comment]
All is good. Thank you!

Old logs (April 03, 2018):
```
Apr 03, 2018 12:41:17 PM org.atmosphere.cpr.AtmosphereFramework info
INFO: Atmosphere is using async support: org.atmosphere.container.Servlet30CometSupport running under container: Apache Tomcat/8.5.29 using javax.servlet/3.0
```
Current, Vaadin 8.4.1:
```
May 11, 2018 2:25:57 PM org.atmosphere.cpr.AtmosphereFramework info
INFO: Atmosphere is using async support: org.atmosphere.container.JSR356AsyncSupport running under container: Apache Tomcat/8.5.31 using javax.servlet/3.0 and jsr356/WebSocket API
May 11, 2018 2:25:57 PM org.atmosphere.cpr.AtmosphereFramework info
INFO: Atmosphere Framework 2.4.24.vaadin1 started.
```
