### ISSUE TITLE
NullPointerException trying to stringify() JSON object

### ISSUE THREAD

**Issue by archiecobbs** [vaadin/framework#10947]
Vaadin is still having trouble creating JSON properly...

```
java.lang.NullPointerException: null
	at elemental.json.impl.JsonUtil.quote(JsonUtil.java:208) ~[vaadin-shared-8.3.3.jar:8.3.3]
	at elemental.json.impl.JsonUtil$StringifyJsonVisitor.visit(JsonUtil.java:96) ~[vaadin-shared-8.3.3.jar:8.3.3]
	at elemental.json.impl.JreJsonString.traverse(JreJsonString.java:81) ~[vaadin-shared-8.3.3.jar:8.3.3]
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82) ~[vaadin-shared-8.3.3.jar:8.3.3]
	at elemental.json.impl.JreJsonObject.traverse(JreJsonObject.java:177) ~[vaadin-shared-8.3.3.jar:8.3.3]
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82) ~[vaadin-shared-8.3.3.jar:8.3.3]
	at elemental.json.impl.JreJsonObject.traverse(JreJsonObject.java:177) ~[vaadin-shared-8.3.3.jar:8.3.3]
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82) ~[vaadin-shared-8.3.3.jar:8.3.3]
	at elemental.json.impl.JreJsonArray.traverse(JreJsonArray.java:164) ~[vaadin-shared-8.3.3.jar:8.3.3]
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82) ~[vaadin-shared-8.3.3.jar:8.3.3]
	at elemental.json.impl.JreJsonArray.traverse(JreJsonArray.java:164) ~[vaadin-shared-8.3.3.jar:8.3.3]
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82) ~[vaadin-shared-8.3.3.jar:8.3.3]
	at elemental.json.impl.JreJsonArray.traverse(JreJsonArray.java:164) ~[vaadin-shared-8.3.3.jar:8.3.3]
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82) ~[vaadin-shared-8.3.3.jar:8.3.3]
	at elemental.json.impl.JreJsonArray.traverse(JreJsonArray.java:164) ~[vaadin-shared-8.3.3.jar:8.3.3]
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82) ~[vaadin-shared-8.3.3.jar:8.3.3]
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:72) ~[vaadin-shared-8.3.3.jar:8.3.3]
	at elemental.json.impl.JsonUtil.stringify(JsonUtil.java:281) ~[vaadin-shared-8.3.3.jar:8.3.3]
	at elemental.json.impl.JsonUtil.stringify(JsonUtil.java:267) ~[vaadin-shared-8.3.3.jar:8.3.3]
	at elemental.json.impl.JsonUtil.stringify(JsonUtil.java:252) ~[vaadin-shared-8.3.3.jar:8.3.3]
	at com.vaadin.server.communication.ClientRpcWriter.write(ClientRpcWriter.java:106) ~[vaadin-server-8.3.3.jar:8.3.3]
	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:207) ~[vaadin-server-8.3.3.jar:8.3.3]
	at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:124) ~[vaadin-server-8.3.3.jar:8.3.3]
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:92) ~[vaadin-server-8.3.3.jar:8.3.3]
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[vaadin-server-8.3.3.jar:8.3.3]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1601) [vaadin-server-8.3.3.jar:8.3.3]
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:445) [vaadin-server-8.3.3.jar:8.3.3]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [servlet-api.jar:?]

```

**Comment by elmot** [comment]
Can you please provide a code example?

**Comment by archiecobbs** [comment]
Not without uploading my entire web application. I have no idea where this problem is originating.

But that's exactly the real problem here: this stupid "elemental" library is allowing Vaadin to construct an invalid `JreJsonString` object with a `null` value, but the failure is only detected later when someone tries to `stringify()` the whole JSON blob within which it is deeply nested. By that time the the origin of the error is hopelessly obscured.

A properly written software library would be "fail fast" and properly defend against the construction of an invalid instance of anything. Then we would have seen an `IllegalArgumentException` identifying the root cause of the problem, instead of a random and uninformative `NullPointerException` some random time later.

So what I want to say is: why am I having to explain all of this? because Vaadin chose to use this library, Vaadin can deal with the resulting debug nightmare...

But of course that means this bug will just get ignored (been there many times before), so I guess I'll have to track it down myself as usual... bleh.

Sorry. End of rant.

**Comment by archiecobbs** [comment]
I edited `JreJsonString` to throw an exception when a null value is set. Here's what that shows:
```
2018-05-24T13:50:56,797 [http-nio-127.0.0.1-8080-exec-46] ERROR: ILLEGAL NULL STRING SET HERE
java.lang.Throwable: null
	at elemental.json.impl.JreJsonString.<init>(JreJsonString.java:37) [classes/:8.3.3]
	at elemental.json.impl.JreJsonFactory.create(JreJsonFactory.java:36) [vaadin-shared-8.3.3.jar:8.3.3]
	at elemental.json.Json.create(Json.java:26) [vaadin-shared-8.3.3.jar:8.3.3]
	at com.vaadin.ui.renderers.TextRenderer.encode(TextRenderer.java:56) [vaadin-server-8.3.3.jar:8.3.3]
	at com.vaadin.ui.Grid$Column.generateRendererValue(Grid.java:1050) [vaadin-server-8.3.3.jar:8.3.3]
	at com.vaadin.ui.Grid$Column.access$1100(Grid.java:831) [vaadin-server-8.3.3.jar:8.3.3]
	at com.vaadin.ui.Grid$Column$1.generateData(Grid.java:862) [vaadin-server-8.3.3.jar:8.3.3]
	at com.vaadin.data.provider.DataCommunicator.getDataObject(DataCommunicator.java:449) [vaadin-server-8.3.3.jar:8.3.3]
	at com.vaadin.data.provider.DataCommunicator.pushData(DataCommunicator.java:429) [vaadin-server-8.3.3.jar:8.3.3]
	at com.vaadin.data.provider.DataCommunicator.sendDataToClient(DataCommunicator.java:342) [vaadin-server-8.3.3.jar:8.3.3]
	at com.vaadin.data.provider.DataCommunicator.beforeClientResponse(DataCommunicator.java:311) [vaadin-server-8.3.3.jar:8.3.3]
	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:126) [vaadin-server-8.3.3.jar:8.3.3]
	at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:124) [vaadin-server-8.3.3.jar:8.3.3]
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:92) [vaadin-server-8.3.3.jar:8.3.3]
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) [vaadin-server-8.3.3.jar:8.3.3]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1601) [vaadin-server-8.3.3.jar:8.3.3]
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:445) [vaadin-server-8.3.3.jar:8.3.3]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [servlet-api.jar:?]
```

**Comment by archiecobbs** [comment]
The problem is caused by trying to display an object whose `toString()` method returns null.

Although this is admittedly weird, the entire Vaadin application shouldn't just blow up if that happens.

Here's a fix:
```
diff --git a/server/src/main/java/com/vaadin/ui/renderers/TextRenderer.java b/server/src/main/java/com/vaadin/ui/renderers/TextRenderer.java
index eb749d1..0eb2ee1 100644
--- a/server/src/main/java/com/vaadin/ui/renderers/TextRenderer.java
+++ b/server/src/main/java/com/vaadin/ui/renderers/TextRenderer.java
@@ -50,11 +50,12 @@ public class TextRenderer extends AbstractRenderer<Object, Object> {
 
     @Override
     public JsonValue encode(Object value) {
-        if (value == null) {
+        if (value == null)
             return super.encode(null);
-        } else {
-            return Json.create(value.toString());
-        }
+        final String stringValue = value.toString();
+        if (stringValue == null)
+            return super.encode(null);
+        return Json.create(value.toString());
     }
 
     @Override
```
