### ISSUE TITLE
Vaadin 7 | FileUploadHandler#273 NPE

### ISSUE THREAD

**Issue by knoobie** [vaadin/framework#10951]
We noticed a lot of exceptions in our production log today:

Looking at the sources with IntelliJ IDEA it's the following:

https://github.com/vaadin/framework/blob/3d337da49225558ed4f2a39ceafa8b5b6f5a4ff8/server/src/main/java/com/vaadin/server/communication/FileUploadHandler.java#L272

Stacktrace:

```
threw exception [com.vaadin.server.ServiceException: java.lang.NullPointerException] with root cause
java.lang.NullPointerException
	at com.vaadin.server.communication.FileUploadHandler.handleRequest(FileUploadHandler.java:273)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1435)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:380)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
```

Vaadin Version: 7.7.13
Tomcat: 8.5~

**Comment by elmot** [comment]
Does it happen after the session expiration?

**Comment by knoobie** [comment]
I have no further information (sadly) - we had no time to reproduce this and no customer complained. (so it's okay I guess) 

Just wanted to make sure you guys know about this.
