### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by cliviu** [vaadin/framework#11029]
Hi,
I'm using  Vaadin Framework version  8.3.2, I receive the following stackTrace when using our custom component: 
`
java.lang.RuntimeException: java.util.ConcurrentModificationException

       at com.vaadin.server.JsonCodec.encodeObject(JsonCodec.java:758)

       at com.vaadin.server.JsonCodec.encode(JsonCodec.java:687)

       at com.vaadin.server.LegacyCommunicationManager.encodeState(LegacyCommunicationManager.java:107)

       at com.vaadin.server.AbstractClientConnector.encodeState(AbstractClientConnector.java:282)

       at com.vaadin.server.communication.SharedStateWriter.write(SharedStateWriter.java:67)

       at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:176)

       at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:124)

       at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:92)

       at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)

       at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1601)

       at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:445)

       at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

       at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)

       at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)

       at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:201)

       at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)

       at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)

       at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)

       at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)

       at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)

       at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)

       at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)

       at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)

       at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)

       at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)

       at org.eclipse.jetty.server.Server.handle(Server.java:499)

       at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)

       at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)

       at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)

       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)

       at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)

       at java.lang.Thread.run(Thread.java:748)`

What can I do in order to avoid this ? Why is the LegacyCommunicationManager still there. According to the documentation it should be deprecated ... Thanks !

**Comment by elmot** [comment]
This error looks very strange, this piece of code is very often, and we never seen anything like that. Please provide more information - any reproducible example will be helpful, or, at least, a very detailed description - what kind of a custom component, do you use any push or not.

**Comment by Artur-** [comment]
Typically caused by not locking the session before modifying it from a background thread. Try running the server with `-ea` (assertions enabled) to find the real cause
