### ISSUE TITLE
Push failed due ConcurrentModificationException

### ISSUE THREAD

**Issue by smikesmike** [vaadin/framework#11204]
- Vaadin Framework version: 8.5.2
- Browser version: Google chrome "Version 68.0.3440.106 (Offizieller Build) (64-Bit)")
- Web container: Jetty 9.4.7
- I've developed a Vaadin canvas widget which works like a VNC viewer. This means the widget contains a background thread updating continuously the UI. Together with server push messages, this leads into the following exception:

```
14:55:35.775;;com.vaadin.server.DefaultErrorHandler ;qtp189194499-23;E;

java.lang.RuntimeException: Push failed
	at com.vaadin.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:171)
	at com.vaadin.server.communication.PushHandler.lambda$new$1(PushHandler.java:149)
	at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:248)
	at com.vaadin.server.communication.PushHandler.onMessage(PushHandler.java:534)
	at com.vaadin.server.communication.PushAtmosphereHandler.onMessage(PushAtmosphereHandler.java:87)
	at com.vaadin.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:77)
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:225)
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:114)
	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:67)
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2297)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:594)
	at org.atmosphere.websocket.DefaultWebSocketProcessor$3.run(DefaultWebSocketProcessor.java:345)
	at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:340)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:448)
	at org.atmosphere.container.JSR356Endpoint$3.onMessage(JSR356Endpoint.java:272)
	at org.atmosphere.container.JSR356Endpoint$3.onMessage(JSR356Endpoint.java:269)
	at org.eclipse.jetty.websocket.jsr356.messages.TextWholeMessage.messageComplete(TextWholeMessage.java:56)
	at org.eclipse.jetty.websocket.jsr356.endpoints.JsrEndpointEventDriver.onTextFrame(JsrEndpointEventDriver.java:218)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:162)
	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:375)
	at org.eclipse.jetty.websocket.common.extensions.AbstractExtension.nextIncomingFrame(AbstractExtension.java:182)
	at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.nextIncomingFrame(PerMessageDeflateExtension.java:105)
	at org.eclipse.jetty.websocket.common.extensions.compress.CompressExtension.forwardIncoming(CompressExtension.java:142)
	at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.incomingFrame(PerMessageDeflateExtension.java:85)
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220)
	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:256)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:679)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:511)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:104)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:243)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
	at com.vaadin.ui.ConnectorTracker.getDirtyVisibleConnectors(ConnectorTracker.java:666)
	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:94)
	at com.vaadin.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:168)

... 39 common frames omitted
```

If you inspect the related code
```
    /**
     * Returns a collection of those {@link #getDirtyConnectors() dirty
     * connectors} that are actually visible to the client.
     *
     * @return A list of dirty and visible connectors.
     */
    public ArrayList<ClientConnector> getDirtyVisibleConnectors() {
        Collection<ClientConnector> dirtyConnectors = getDirtyConnectors();
        ArrayList<ClientConnector> dirtyVisibleConnectors = new ArrayList<>(
                dirtyConnectors.size());
        for (ClientConnector c : dirtyConnectors) {
            if (LegacyCommunicationManager.isConnectorVisibleToClient(c)) {
                dirtyVisibleConnectors.add(c);
            }
        }
        return dirtyVisibleConnectors;
    }
```
a threadsafe patch is quite easy to implement. For instance like this
```
[...]
public class ConnectorTracker implements Serializable {

    private final Map<String, ClientConnector> connectorIdToConnector = new ConcurrentHashMap<>();
    private final Set<ClientConnector> dirtyConnectors = new CopyOnWriteArraySet<>();
    private final Set<ClientConnector> uninitializedConnectors = new CopyOnWriteArraySet<>();
[...]
  /**
     * Returns a collection of those {@link #getDirtyConnectors() dirty
     * connectors} that are actually visible to the client.
     *
     * @return A list of dirty and visible connectors.
     */
    public ArrayList<ClientConnector> getDirtyVisibleConnectors() {
        ArrayList<ClientConnector> dirtyVisibleConnectors = new ArrayList<>(
                getDirtyConnectors());
        for (Iterator<ClientConnector> itr = dirtyVisibleConnectors
                .iterator(); itr.hasNext();) {
            ClientConnector c = itr.next();
            if (!LegacyCommunicationManager.isConnectorVisibleToClient(c)) {
                itr.remove();
            }
        }
        return dirtyVisibleConnectors;
    }
[...]
```

Unfortunately, I don't now how to create a pull request. Therefore, I've created the merge request as an issue.

Best regards
Marc

**Comment by TatuLund** [comment]
Thanks for reporting this. It would help us to understand the case better, if you could link minimal reproducing sample application to the issue report.

**Comment by smikesmike** [comment]
Hi Tatu,
the problem is, that I use a custom widget which draws the screen from an android phone in the web browser (as canvas element). Hence, it is not easy to create a simple test project for you.
But if you inspect the vaadin part, you will see that the exception producing code is uses map and set classes which are not threadsafe. Especially, the field "dirtyConnectors" might change while processing it in "ConnectorTracker::getDirtyVisibleConnectors".
When I replace them by "ConcurrentHashMap" and "CopyOnWriteArraySet" everything works fine. 
What do you think? This change shouldn't break anything, doesn't it?
Best regards,
Marc

**Comment by TatuLund** [comment]
> This means the widget contains a background thread updating continuously the UI. 

I am interested to know your code regarding this part, namely to assess that UI.access(..) is used in right manner for the updates.

**Comment by Legioth** [comment]
This problem is in 99% of all cases caused by misbehaving components. The `ConcurrentModificationException` from framework code is only the canary. "Fixing" it to be "threadsafe" would only cause problems to show up in some other place instead.

Run you server with assertions enabled to pinpoint the actual cause of the problem.

See http://vaadinsolutions.blogspot.com/2016/02/concurrentmodificationexception.html for more details.

**Comment by Legioth** [comment]
If nothing else, we could consider adding comments in the code for the typical cases that might feel tempting to make "threadsafe" so that anyone encountering this type of exception and looks at the source might understand the actual root cause.
