### ISSUE TITLE
Setting Grid item type in Designer Fails in OSGi container

### ISSUE THREAD

**Issue by QNENet** [vaadin/framework#11377]
Vaadin Framework version 8.5.1
Designer 4

When running in OSGi container
If Grid item type is set in the designer, at runtime the class is not found.
If set in code e.g.  menusGrid.setItems(new ArrayList`<QMenuInfo>`()); there is no problem.

The cause is related to Class.forName in Grid#resolveClass 

java.lang.IllegalArgumentException: Unable to find class net.qnenet.qMemberClasses.api.QMenuInfo
	at com.vaadin.ui.Grid.resolveClass(Grid.java:4422)
	at com.vaadin.ui.Grid.setBeanType(Grid.java:4394)
	at com.vaadin.ui.Grid.doReadDesign(Grid.java:4351)
	at com.vaadin.ui.AbstractListing.readDesign(AbstractListing.java:356)
	at com.vaadin.ui.declarative.DesignContext.readDesign(DesignContext.java:526)
	at com.vaadin.ui.declarative.DesignContext.readDesign(DesignContext.java:506)
	at com.vaadin.ui.AbstractOrderedLayout.readDesign(AbstractOrderedLayout.java:471)
	at com.vaadin.ui.declarative.DesignContext.readDesign(DesignContext.java:526)
	at com.vaadin.ui.declarative.DesignContext.readDesign(DesignContext.java:506)
	at com.vaadin.ui.AbstractOrderedLayout.readDesign(AbstractOrderedLayout.java:471)
	at com.vaadin.ui.declarative.DesignContext.readDesign(DesignContext.java:526)
	at com.vaadin.ui.declarative.DesignContext.readDesign(DesignContext.java:506)
	at com.vaadin.ui.AbstractOrderedLayout.readDesign(AbstractOrderedLayout.java:471)
	at com.vaadin.ui.declarative.DesignContext.readDesign(DesignContext.java:526)
	at com.vaadin.ui.declarative.Design.designToComponentTree(Design.java:502)
	at com.vaadin.ui.declarative.Design.read(Design.java:612)
	at net.qnenet.qViewMenus.provider.designer.QViewMenusDesign.<init>(QViewMenusDesign.java:34)
	at net.qnenet.qViewMenus.provider.views.QViewMenusImpl.<init>(QViewMenusImpl.java:27)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:237)
	at org.apache.felix.scr.impl.manager.ServiceFactoryComponentManager.getService(ServiceFactoryComponentManager.java:114)
	at org.apache.felix.framework.ServiceRegistrationImpl.getFactoryUnchecked(ServiceRegistrationImpl.java:347)
	at org.apache.felix.framework.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:247)
	at org.apache.felix.framework.ServiceRegistry.getService(ServiceRegistry.java:350)
	at org.apache.felix.framework.Felix.getService(Felix.java:3737)
	at org.apache.felix.framework.BundleContextImpl$ServiceObjectsImpl.getService(BundleContextImpl.java:574)
	at org.apache.felix.scr.impl.helper.ComponentServiceObjectsHelper$ComponentServiceObjectsImpl.getService(ComponentServiceObjectsHelper.java:182)

**Comment by TatuLund** [comment]
Have you tested this with latest Vaadin 8.6.3. After 8.5.1 there has been couple of patches regarding OSGi, and they may have changed the behavior.
