### ISSUE TITLE
NPE in ComboBox filtering when ItemCaptionGenerator returns null

### ISSUE THREAD

**Issue by mvysny** [vaadin/framework#11434]
This is something else than #8630, since this is a bug in the filtering mechanism by default used by ComboBox when no `CaptionFilter` is provided by the user. The stacktrace:

```
java.lang.NullPointerException: null
	at com.vaadin.ui.ComboBox.lambda$setDataProvider$70331b78$1(ComboBox.java:410)
	at com.vaadin.ui.ComboBox.lambda$null$2c74abb5$1(ComboBox.java:456)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.LongPipeline.reduce(LongPipeline.java:438)
	at java.util.stream.LongPipeline.sum(LongPipeline.java:396)
	at java.util.stream.ReferencePipeline.count(ReferencePipeline.java:526)
	at com.vaadin.data.provider.ListDataProvider.size(ListDataProvider.java:87)
	at com.vaadin.data.provider.DataCommunicator.getDataProviderSize(DataCommunicator.java:776)
	at com.vaadin.data.provider.DataCommunicator.sendDataToClient(DataCommunicator.java:358)
	at com.vaadin.data.provider.DataCommunicator.beforeClientResponse(DataCommunicator.java:338)
	at com.vaadin.data.provider.DataCommunicator.reset(DataCommunicator.java:533)
	at com.vaadin.data.provider.DataCommunicator.lambda$setDataProvider$166e3c82$1(DataCommunicator.java:706)
	at com.vaadin.ui.ComboBox.lambda$setDataProvider$94aae624$1(ComboBox.java:946)
	at com.vaadin.ui.ComboBox$1.setFilter(ComboBox.java:210)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:116)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:445)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:410)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274)
```

Vaadin 8.6.4. I'm using Tomcat. Just type in anything into the following ComboBox in attempt to search in its items, and and the ComboBox will throw a NPE:

```
        final ComboBox<String> comboBox = new ComboBox<>();
        comboBox.setItems("1", "2", "3");
        comboBox.setItemCaptionGenerator(item -> null);
```

**Comment by mvysny** [comment]
[karibu-helloworld-application.zip](https://github.com/vaadin/framework/files/2790903/karibu-helloworld-application.zip)
Example project, use Intellij to open it.

**Comment by anasmi** [comment]
closed by https://github.com/vaadin/framework/pull/11435 

Thanks for reporting and test application! :)
