### ISSUE TITLE
vaadin designer causes java to core dump when opening a template

### ISSUE THREAD

**Issue by bsutton** [vaadin/framework#11448]
I've just being trying to install vaadin designer without a license.
I last trialed it two years ago (and gave up because it was flakey).
I'm now trying again with a new flow project we are boot strapping.
So I thought I would follow the install guide as per:
https://vaadin.com/trial 'Start trial with designer'.

I first found and deleted my old licenses.

When I created my first form eclipse crashed.
Now each time I try to open the form eclipse crashes.

core dump attached.

Startup Logs from eclipse:
```
./eclipse
org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.

(Eclipse:14228): Gtk-WARNING **: 17:45:42.504: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.504: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.605: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.605: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.720: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.720: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.774: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.774: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.795: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.795: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.812: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.812: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.825: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.825: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.848: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.848: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.860: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.860: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.880: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.880: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.899: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.899: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.914: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.914: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.927: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.927: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.941: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.941: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.959: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.959: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.975: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.975: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.992: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:42.992: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:43.008: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(Eclipse:14228): Gtk-WARNING **: 17:45:43.008: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)
org.eclipse.m2e.logback.configuration: Logback config file: /home/bsutton/git/workspaces/micropbx/.metadata/.plugins/org.eclipse.m2e.logback.configuration/logback.1.9.0.20180606-2036.xml
org.eclipse.m2e.logback.configuration: Initializing logback
17:45:45,730 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
17:45:45,730 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
17:45:45,730 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.xml]
17:45:45,731 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Setting up default configuration.
17:45:45,794 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
17:45:45,799 |-INFO in ReconfigureOnChangeFilter{invocationCounter=0} - Will scan for changes in [[/home/bsutton/git/workspaces/micropbx/.metadata/.plugins/org.eclipse.m2e.logback.configuration/logback.1.9.0.20180606-2036.xml]] every 60 seconds. 
17:45:45,799 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Adding ReconfigureOnChangeFilter as a turbo filter
17:45:45,800 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
17:45:45,800 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
17:45:45,831 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
17:45:45,832 |-ERROR in ch.qos.logback.core.joran.action.AppenderAction - Could not create an Appender of type [ch.qos.logback.core.rolling.RollingFileAppender]. ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.core.rolling.RollingFileAppender
	at ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.core.rolling.RollingFileAppender
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:73)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:48)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:35)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:54)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:275)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:147)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:129)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
	at 	at org.eclipse.m2e.logback.configuration.LogPlugin.loadConfiguration(LogPlugin.java:185)
	at 	at org.eclipse.m2e.logback.configuration.LogPlugin.configureLogback(LogPlugin.java:144)
	at 	at org.eclipse.m2e.logback.configuration.LogPlugin.access$2(LogPlugin.java:107)
	at 	at org.eclipse.m2e.logback.configuration.LogPlugin$1.run(LogPlugin.java:62)
	at 	at java.util.TimerThread.mainLoop(Timer.java:555)
	at 	at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.core.rolling.RollingFileAppender cannot be found by ch.qos.logback.classic_1.1.2.v20160208-0839
	at 	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:508)
	at 	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:419)
	at 	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:411)
	at 	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:60)
	at 	... 17 common frames omitted
17:45:45,832 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@11:81 - ActionException in Action for tag [appender] ch.qos.logback.core.joran.spi.ActionException: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.core.rolling.RollingFileAppender
	at ch.qos.logback.core.joran.spi.ActionException: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.core.rolling.RollingFileAppender
	at 	at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:82)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:275)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:147)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:129)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
	at 	at org.eclipse.m2e.logback.configuration.LogPlugin.loadConfiguration(LogPlugin.java:185)
	at 	at org.eclipse.m2e.logback.configuration.LogPlugin.configureLogback(LogPlugin.java:144)
	at 	at org.eclipse.m2e.logback.configuration.LogPlugin.access$2(LogPlugin.java:107)
	at 	at org.eclipse.m2e.logback.configuration.LogPlugin$1.run(LogPlugin.java:62)
	at 	at java.util.TimerThread.mainLoop(Timer.java:555)
	at 	at java.util.TimerThread.run(Timer.java:505)
Caused by: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type ch.qos.logback.core.rolling.RollingFileAppender
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:73)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:48)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:35)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:54)
	at 	... 14 common frames omitted
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.core.rolling.RollingFileAppender cannot be found by ch.qos.logback.classic_1.1.2.v20160208-0839
	at 	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:508)
	at 	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:419)
	at 	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:411)
	at 	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
	at 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:60)
	at 	... 17 common frames omitted
17:45:45,832 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [org.eclipse.m2e.logback.appender.EclipseLogAppender]
17:45:45,833 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [EclipseLog]
17:45:45,834 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [org.eclipse.m2e.logback.appender.MavenConsoleAppender]
17:45:45,834 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [MavenConsoleLog]
17:45:45,835 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
17:45:45,835 |-ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - Could not find an appender named [FILE]. Did you define it below instead of above in the configuration file?
17:45:45,835 |-ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - See http://logback.qos.ch/codes.html#appender_order for more details.
17:45:45,835 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
17:45:45,835 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [EclipseLog] to Logger[ROOT]
17:45:45,835 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [MavenConsoleLog] to Logger[ROOT]
17:45:45,835 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.ning.http.client] to INFO
17:45:45,835 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
17:45:45,835 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@39501793 - Registering current configuration as safe fallback point

Warning: NLS unused message: Outline_title in: com.vaadin.designer2.i18n.messages
Warning: NLS unused message: Palette_title in: com.vaadin.designer2.i18n.messages
Warning: NLS unused message: Property_editor_title in: com.vaadin.designer2.i18n.messages
Warning: NLS unused message: Property_editor_error_title in: com.vaadin.designer2.i18n.messages
Warning: NLS unused message: Property_editor_int_error in: com.vaadin.designer2.i18n.messages
Warning: NLS unused message: Property_editor_float_error in: com.vaadin.designer2.i18n.messages
Warning: NLS unused message: Property_editor_click_here_to_add_string in: com.vaadin.designer2.i18n.messages
Warning: NLS unused message: Property_editor_click_here_to_add_boolean in: com.vaadin.designer2.i18n.messages
Warning: NLS unused message: NewDesignWizard_javaPackage in: com.vaadin.designer2.i18n.messages
Warning: NLS unused message: NewDesignWizard_designName in: com.vaadin.designer2.i18n.messages
Warning: NLS unused message: NewDesignWizard_error_name_required in: com.vaadin.designer2.i18n.messages
Warning: NLS unused message: NewDesignWizard_error_name_format in: com.vaadin.designer2.i18n.messages
Warning: NLS unused message: NewDesignWizard_error_flow_choose_java_root in: com.vaadin.designer2.i18n.messages
Warning: NLS unused message: NewDesignWizard_error_flow_default_package_warning in: com.vaadin.designer2.i18n.messages
Warning: NLS unused message: NewDesignWizard_error_flow_location in: com.vaadin.designer2.i18n.messages
Warning: NLS unused message: NewDesignWizard_error_design_location in: com.vaadin.designer2.i18n.messages
Warning: NLS unused message: NewDesignWizard_error_java_location in: com.vaadin.designer2.i18n.messages
Warning: NLS unused message: NewDesignWizard_error_package_name_format in: com.vaadin.designer2.i18n.messages
Warning: NLS unused message: NewDesignWizard_error_name_special_character in: com.vaadin.designer2.i18n.messages
Warning: NLS unused message: NewFlowTemplateWizard_template_location in: com.vaadin.designer2.i18n.messages
Warning: NLS unused message: NewFlowTemplateWizard_companion_file_already_exists in: com.vaadin.designer2.i18n.messages
Warning: NLS unused message: NewFlowTemplateWizard_java_source_root in: com.vaadin.designer2.i18n.messages
Warning: NLS unused message: NewFlowTemplateWizard_java_package in: com.vaadin.designer2.i18n.messages
Warning: NLS unused message: Editor_wrong_content_unexpected_exception in: com.vaadin.designer2.i18n.messages
Warning: NLS unused message: Editor_warning_file_readonly_title in: com.vaadin.designer2.i18n.messages
Warning: NLS unused message: Editor_warning_file_readonly in: com.vaadin.designer2.i18n.messages
Warning: NLS unused message: Editor_version_conflict_prevention_title in: com.vaadin.designer2.i18n.messages
Warning: NLS unused message: Editor_version_conflict_prevention_message in: com.vaadin.designer2.i18n.messages
Warning: NLS unused message: Error_scss_exception_view_errors_link in: com.vaadin.designer2.i18n.messages
Warning: NLS unused message: Error_scss_exception_see_console in: com.vaadin.designer2.i18n.messages
Warning: NLS unused message: Error_polymer_imports_view_errors_link in: com.vaadin.designer2.i18n.messages
2019-02-03 17:45:56.050:INFO::main: Logging initialized @17333ms
Initiated 'com.salesforce.ide.core' plugin, version 38.0.0.201701101558
Initiated 'com.salesforce.ide.ui.editors' plugin, version 38.0.0.201701101558
Feb 03, 2019 5:46:08 PM com.vaadin.integration.eclipse.notifications.ContributionService refreshNotifications
INFO: Schedule fetching all notifications
Feb 03, 2019 5:46:08 PM com.vaadin.integration.eclipse.notifications.ContributionService startVersionJobs
INFO: Schedule version update jobs
OpenJDK 64-Bit Server VM warning: You have loaded library /home/bsutton/apps/eclipse/jee-oxygen/configuration/org.eclipse.osgi/1127/0/.cp/libj2v8_linux_x86_64.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Feb 03, 2019 5:46:09 PM com.vaadin.integration.eclipse.notifications.model.NotificationsService doGet
INFO: Requesting user info (notification settings URL)
Feb 03, 2019 5:46:09 PM com.vaadin.integration.eclipse.notifications.model.NotificationsService doGet
INFO: Fetching all notifications
Feb 03, 2019 5:46:11 PM com.vaadin.integration.eclipse.notifications.model.NotificationsService getStatusCode
INFO: HTTP Response code :200
Feb 03, 2019 5:46:11 PM com.vaadin.integration.eclipse.notifications.model.NotificationsService getStatusCode
INFO: HTTP Response code :200
Feb 03, 2019 5:46:11 PM com.vaadin.integration.eclipse.notifications.model.NotificationsService getNotifications
INFO: Parse notifications
Feb 03, 2019 5:46:11 PM com.vaadin.integration.eclipse.notifications.model.NotificationsService saveCache
INFO: Save JSON notifications content to cache file /home/bsutton/git/workspaces/micropbx/.metadata/.plugins/com.vaadin.integration.eclipse/notifications-cache.json
05:46:12 SEVERE: [0203/174612.677160:ERROR:nss_util.cc(724)] After loading Root Certs, loaded==false: NSS error code: -8018
Feb 03, 2019 5:46:13 PM com.vaadin.integration.eclipse.notifications.ContributionService schedulePollingJob
INFO: Schedule fetching new notifications
Initiated 'com.salesforce.ide.ui' ForceIdeUIPlugin, version 38.0.0.201701101558
Initiated 'com.salesforce.ide.upgrade' plugin, version 38.0.0.201701101558
Feb 03, 2019 5:46:14 PM com.vaadin.designer2.browser.EmbeddedJxBrowser initializeBrowserCore
INFO: BrowserCore initialized.



Feb 03, 2019 5:46:38 PM com.vaadin.integration.eclipse.notifications.jobs.nightly.NightlyCheckJob checkProjects
INFO: All vaadin 7+ projects : []
2019-02-03 17:47:20.470:INFO:oejs.Server:main: jetty-9.3.19.v20170502
2019-02-03 17:47:20.523:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@4795fe87{/,null,AVAILABLE}
2019-02-03 17:47:20.530:INFO:oejs.AbstractConnector:main: Started ServerConnector@3673c520{HTTP/1.1,[http/1.1]}{localhost:32933}
2019-02-03 17:47:20.531:INFO:oejs.Server:main: Started @101814ms
Feb 03, 2019 5:47:20 PM com.vaadin.designer2.server.AbstractEditorApplicationServer start
INFO: Remote preview available on http://192.168.86.134:32933. Designer running on http://localhost:32933.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f5decd95321, pid=14228, tid=0x00007f5f34c35700
#
# JRE version: OpenJDK Runtime Environment (8.0_191-b12) (build 1.8.0_191-8u191-b12-2ubuntu0.18.10.1-b12)
# Java VM: OpenJDK 64-Bit Server VM (25.191-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libgdk-x11-2.0.so.0+0x4f321]  gdk_display_open+0x61
#
# Core dump written. Default location: /home/bsutton/apps/eclipse/jee-oxygen/core or core.14228
#
# An error report file with more information is saved as:
# /home/bsutton/apps/eclipse/jee-oxygen/hs_err_pid14228.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

```

```
lsb_release -a
LSB Version:	core-9.20170808ubuntu1-noarch:cxx-3.0-amd64:cxx-3.0-noarch:cxx-3.1-amd64:cxx-3.1-noarch:cxx-3.2-amd64:cxx-3.2-noarch:cxx-4.0-amd64:cxx-4.0-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-3.1-amd64:desktop-3.1-noarch:desktop-3.2-amd64:desktop-3.2-noarch:desktop-4.0-amd64:desktop-4.0-noarch:desktop-4.1-amd64:desktop-4.1-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.0-amd64:graphics-3.0-noarch:graphics-3.1-amd64:graphics-3.1-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0-amd64:graphics-4.0-noarch:graphics-4.1-amd64:graphics-4.1-noarch:languages-3.2-amd64:languages-3.2-noarch:languages-4.0-amd64:languages-4.0-noarch:languages-4.1-amd64:languages-4.1-noarch:multimedia-3.2-amd64:multimedia-3.2-noarch:multimedia-4.0-amd64:multimedia-4.0-noarch:multimedia-4.1-amd64:multimedia-4.1-noarch:printing-9.20170808ubuntu1-noarch:qt4-3.1-amd64:qt4-3.1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic
```

```
java -versio]n
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```

**Comment by bsutton** [comment]
I've just upgraded to java 11 and the crash no longer occurs:

```
java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1+13-Ubuntu-3ubuntu3.18.10.1)
OpenJDK 64-Bit Server VM (build 11.0.1+13-Ubuntu-3ubuntu3.18.10.1, mixed mode, sharing)

```
