### ISSUE TITLE
Vaadin 7.7.16 push closes connection and session expires

### ISSUE THREAD

**Issue by ShawnRG** [vaadin/framework#11549]
Hi,
I'm currently facing some issues with Vaadin push.
I have a view that opens a browser frame and shows the browser when its loaded.

For some reason vaadin push can't connect.
This application has been tested on multiple host pc's, including:

- Windows 7 host in a production facility (NOT WORKING)
    - Firefox v66.0
    - Chrome v65.0
    - Tomcat v8.0.32 
- Linux host (WORKING)
    - Chrome v72.0
    - Tomcat 8.5.13
- Windows 7 host on the development floor (WORKING)
    - Chrome v71.0
    - Firefox v66.0
    - Tomcat 8.0.32

Running it on the not working environment resulted in following browser logs
[pastebin link](https://pastebin.com/GfHnMGkT)

Possible solutions I've tried:

- Trying each push transport mode (websocket, xhr, long-polling)
- Different tomcat server (8.5.13 & 8.0.13)
- Setting load on start to 1

Any clues?

EDIT:
Found an exception on the server:
```
2019-04-24 14:54:35 : .serv.comm.PushAtmosphereHandler :          : Exception in push connection 
 org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe
	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:393)
	at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:426)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:342)
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:317)
	at org.apache.catalina.connector.Response.flushBuffer(Response.java:497)
	at org.apache.catalina.connector.ResponseFacade.flushBuffer(ResponseFacade.java:318)
	at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:176)
	at org.atmosphere.cpr.AtmosphereResponse.flushBuffer(AtmosphereResponse.java:485)
	at org.atmosphere.cpr.AtmosphereInterceptorWriter.flush(AtmosphereInterceptorWriter.java:102)
	at org.atmosphere.cpr.AtmosphereResponse$2.flush(AtmosphereResponse.java:589)
	at org.atmosphere.handler.AbstractReflectorAtmosphereHandler.onStateChange(AbstractReflectorAtmosphereHandler.java:154)
	at com.vaadin.server.communication.PushAtmosphereHandler.onStateChange(PushAtmosphereHandler.java:52)
	at org.atmosphere.cpr.DefaultBroadcaster.invokeOnStateChange(DefaultBroadcaster.java:1096)
	at org.atmosphere.cpr.DefaultBroadcaster.prepareInvokeOnStateChange(DefaultBroadcaster.java:1116)
	at org.atmosphere.cpr.DefaultBroadcaster.executeAsyncWrite(DefaultBroadcaster.java:921)
	at org.atmosphere.cpr.DefaultBroadcaster$3.run(DefaultBroadcaster.java:522)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:124)
	at org.apache.tomcat.util.net.NioBlockingSelector.write(NioBlockingSelector.java:101)
	at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:172)
	at org.apache.coyote.http11.InternalNioOutputBuffer.writeToSocket(InternalNioOutputBuffer.java:139)
	at org.apache.coyote.http11.InternalNioOutputBuffer.addToBB(InternalNioOutputBuffer.java:197)
	at org.apache.coyote.http11.InternalNioOutputBuffer.access$000(InternalNioOutputBuffer.java:41)
	at org.apache.coyote.http11.InternalNioOutputBuffer$SocketOutputBuffer.doWrite(InternalNioOutputBuffer.java:320)
	at org.apache.coyote.http11.filters.ChunkedOutputFilter.doWrite(ChunkedOutputFilter.java:118)
	at org.apache.coyote.http11.AbstractOutputBuffer.doWrite(AbstractOutputBuffer.java:256)
	at org.apache.coyote.Response.doWrite(Response.java:501)
	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:388)
	... 20 more
```

Thanks in advance

**Comment by TatuLund** [comment]
Do you have proxy in the server setup as well?

**Comment by tstsogoo** [comment]
+1
