### ISSUE TITLE
Push failed empty string

### ISSUE THREAD

**Issue by matjeromin** [vaadin/framework#11568]
Update  button.text from background thread via UI.access() and @Push(AUTOMATIC).
In same ui.access, set text to something e.g. "asd" and afterwards set it to empty string "".

Results in 
RuntimeException: Push failed, caused by IndexOutOfBoundsException (full trace see below)

Expected:
update the button, s.t. it has no text

<details>
  <summary>Versions (Vaadin 13)</summary>
vaadin.version 13.0.4
vaadin.plugin.version 13.0.3
jetty.plugin.version 9.4.12.v20180830
java 1.8 (windows/oracle/64-bit)
Browser: Firefox 66.0.5 (64-Bit)
</details>

<details>
  <summary>Example</summary>

```
import com.vaadin.flow.component.UI;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.icon.VaadinIcon;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.page.Push;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.shared.communication.PushMode;

@Route(value="bug")
@Push(value=PushMode.AUTOMATIC)
public class ButtonEmptyStringBug extends VerticalLayout {

	Button button = new Button("lala");
	
	public ButtonEmptyStringBug() {
		
		button.setIcon(VaadinIcon.CHECK.create());
		add(button);
		
		final UI ui = UI.getCurrent();
		
		Thread backgroundThread = new Thread(() -> {
			try {
				Thread.sleep(5000); // work, work
				ui.access(() -> {
					button.setText("asd");
					button.setText("");
				});
				System.out.println("done");
			} catch (InterruptedException e) {	} 
		});
		backgroundThread.start();
	}
	
}
```
</details>

<details>
  <summary>Stack Trace</summary>

```
Exception in thread "Thread-75" java.lang.RuntimeException: Push failed
	at com.vaadin.flow.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:198)
	at com.vaadin.flow.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:173)
	at com.vaadin.flow.component.UI.push(UI.java:655)
	at com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:650)
	at com.vaadin.flow.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:1917)
	at com.vaadin.flow.server.VaadinService.accessSession(VaadinService.java:1884)
	at com.vaadin.flow.server.VaadinSession.access(VaadinSession.java:930)
	at com.vaadin.flow.component.UI.access(UI.java:487)
	at com.vaadin.flow.component.UI.access(UI.java:470)
	at ButtonEmptyStringBug.lambda$0(ButtonEmptyStringBug.java:27)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IndexOutOfBoundsException: Index: 5, Size: 3
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.vaadin.flow.internal.nodefeature.NodeList.adjustChanges(NodeList.java:444)
	at com.vaadin.flow.internal.nodefeature.NodeList.collectChanges(NodeList.java:308)
	at com.vaadin.flow.internal.StateNode.lambda$doCollectChanges$4(StateNode.java:582)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.vaadin.flow.internal.StateNode.doCollectChanges(StateNode.java:581)
	at com.vaadin.flow.internal.StateNode.collectChanges(StateNode.java:575)
	at com.vaadin.flow.internal.StateTree.lambda$collectChanges$0(StateTree.java:252)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.vaadin.flow.internal.StateTree.collectChanges(StateTree.java:252)
	at com.vaadin.flow.server.communication.UidlWriter.encodeChanges(UidlWriter.java:337)
	at com.vaadin.flow.server.communication.UidlWriter.createUidl(UidlWriter.java:179)
	at com.vaadin.flow.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:194)
	... 10 more
```
</details>

**Comment by TatuLund** [comment]
As this is issue in Vaadin 13, i.e. our new platform, I moved this issue report to another issue tracker.
