### ISSUE TITLE
Delete button on grid causes NullPointerException

### ISSUE THREAD

**Issue by SomMeri** [vaadin/framework#11750]
I have a grid configured with button renderer. Button deletes its own element row from the grid. When user attempts to delete multiple rows by clicking on delete button fast, grid produces `NullPointerException: "editor can't edit null"`. 

This is because vaadin on client side decides second click is actually double click on just removed row and attempts to open editor. 

Similar issue was reported here: https://vaadin.com/forum/thread/16616603/vaadin-8-buttonrenderer-doubleclick

Workaround - create custom grid:
````java
@SuppressWarnings({ "javadoc", "serial" })
public class CustomGrid<T> extends Grid<T> {

	@Override
	protected Editor<T> createEditor() {
		return new FixedEditorImpl<>(getPropertySet());
	}

}

@SuppressWarnings("serial")
class FixedEditorImpl<T> extends EditorImpl<T> {

	public FixedEditorImpl(PropertySet<T> propertySet) {
		super(propertySet);
	}

	@Override
	protected void doEdit(T bean) {
		if (bean == null) {
			cancel();
			return;
		}

		super.doEdit(bean);
	}

}
````

**Comment by SomMeri** [comment]
Adding full call stack:
````java
com.vaadin.server.ServerRpcManager$RpcInvocationException: Unable to invoke method bind in com.vaadin.shared.ui.grid.editor.EditorServerRpc
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:159)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:116)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:445)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:410)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274)
	at com.whitestein.lsps.vaadin.util.requesthandlers.PatchedServerRpcHandler.handleRpc(PatchedUidlRequestHandler.java:39)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1602)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:445)
	at com.whitestein.lsps.vaadin.util.VaadinServletWithTransaction.service(VaadinServletWithTransaction.java:78)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	at com.whitestein.lsps.vaadin.util.LspsVaadinServlet.service(LspsVaadinServlet.java:79)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.tomee.catalina.OpenEJBValve.invoke(OpenEJBValve.java:44)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155)
	... 29 more
Caused by: java.lang.NullPointerException: Editor can't edit null
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.vaadin.ui.components.grid.EditorImpl.doEdit(EditorImpl.java:216)
	at com.whitestein.lsps.vaadin.forms.components.FixedEditorImpl.doEdit(CustomGrid.java:121)
	at com.vaadin.ui.components.grid.EditorImpl$1.bind(EditorImpl.java:152)
	... 34 more
````

**Comment by TatuLund** [comment]
I think this is duplicate of this one https://github.com/vaadin/framework/issues/10995

Thank you for the workaround, which is different than the one described in the other ticket. It is good to have alternatives.
