### ISSUE TITLE
NPE in FileUploadHandler when use Upload.interruptUpload() in CloseListener/DetachListener

### ISSUE THREAD

**Issue by dyorgio** [vaadin/framework#11806]
- Vaadin Framework version (8.9.2)
- Browser version (last Safari and Chrome)
- Web container name and version (Embedded Tomcat (Springboot 1.5.22))
- Description of the bug
NPE in FileUploadHandler while call ConnectorTracker.cleanStreamVariable when try to use Upload.interruptUpload() in CloseListener/DetachListener. 
```stackTrace
java.lang.NullPointerException
	at com.vaadin.ui.ConnectorTracker.cleanStreamVariable(ConnectorTracker.java:881)
	at com.vaadin.server.communication.FileUploadHandler.lambda$cleanStreamVariable$0(FileUploadHandler.java:704)
	at com.vaadin.server.VaadinSession.accessSynchronously(VaadinSession.java:1363)
	at com.vaadin.server.communication.FileUploadHandler.cleanStreamVariable(FileUploadHandler.java:703)
	at com.vaadin.server.communication.FileUploadHandler.handleFileUploadValidationAndData(FileUploadHandler.java:467)
	at com.vaadin.server.communication.FileUploadHandler.doHandleSimpleMultipartFileUpload(FileUploadHandler.java:417)
	at com.vaadin.server.communication.FileUploadHandler.handleRequest(FileUploadHandler.java:294)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1602)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:445)
	at com.upquery.agent.webviewer.ApplicationServlet.service(ApplicationServlet.java:34)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```
- Expected behavior
No erros while interrupt a upload

- Actual behavior
NPE in FileUploadHandler while call ConnectorTracker.cleanStreamVariable (No streamVariable in conector, already cleaned)

**Comment by TatuLund** [comment]
@dyorgio Thanks for the ticket. Can you also attach simplified code example that reproduces the problem.

**Comment by dyorgio** [comment]
Hi @TatuLund, I made some tests and belive that the problem only occours if I interrupt upload in a close listener of window who contains upload component (already detached?).

Here a demo: [demo.zip](https://github.com/vaadin/framework/files/3882554/demo.zip)

**Comment by dyorgio** [comment]
I used guava's RateLimiter to easy tests...

**Comment by dyorgio** [comment]
Confirm, NPE if use DetachListener too..

**Comment by netsrotr** [comment]
Can confirm. We see this exception, reported by the DefaultErrorHandler regulary in our server logs (Glassfish v4.1). Vaadin version: 8.9.4
