### ISSUE TITLE
ClassCastException: class com.vaadin.server.ThemeResource cannot be cast to class com.vaadin.server.ConnectorResource

### ISSUE THREAD

**Issue by mvysny** [vaadin/framework#12113]
- Vaadin 8.11.3
- Firefox 81.0.1, or Chrome 85
- Jetty 9.4.31.v20200723

## Description

A possible race condition, when the image source is modified rapidly, can lead to a ClassCastException:

```
java.lang.ClassCastException: class com.vaadin.server.ThemeResource cannot be cast to class com.vaadin.server.ConnectorResource (com.vaadin.server.ThemeResource and com.vaadin.server.ConnectorResource are in unnamed module of loader org.eclipse.jetty.webapp.WebAppClassLoader @52abed9d)
        at com.vaadin.server.AbstractClientConnector.handleConnectorRequest(AbstractClientConnector.java:671)
        at com.vaadin.server.ConnectorResourceHandler.handleRequest(ConnectorResourceHandler.java:90)
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1606)
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:448)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1651)
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:226)
```

## Steps to reproduce

1. Unzip the attached app
2. run `mvn -C clean package jetty:run`
3. Start clicking rapidly between the "Image1" and the "Image 2" row in the grid.
4. Observe the jetty stdout - at some point the exception will manifest itself.

**Comment by mvysny** [comment]
[vaadin-app.zip](https://github.com/vaadin/framework/files/5347599/vaadin-app.zip)

The example app which reproduces the issue.

**Comment by mvysny** [comment]
Even easier way to reproduce:

1. Click on "Image 2"
2. Copy the link from which the image downloads the image. It's going to be something like http://localhost:8080/APP/connector/1/19/source/e70c7dad-755b-4943-9cc4-9f7481eaee66.png
3. Click on "Image 1"
4. Open the link above in a new tab. It will instantly cause the exception to appear.

In this particular scenario, it is clear that the browser is fetching an obsolete data which is no longer there. That sounds to me that we should respond with 404 instead. @TatuLund if you agree, I can create a PR in this regard.

**Comment by mvysny** [comment]
I propose to change `AbstractClientConnector:671`: if the resource is not of type ConnectorResource, then run this code:
```
response.sendError(HttpServletResponse.SC_NOT_FOUND,
                    "Resource is no longer present");
return true;
```
Or even better, just `return false` since `ConnectorResourceHandler:91` will then handle this as 404.

**Comment by mvysny** [comment]
While this gets fixed, a workaround is to patch the `Image.handleConnectorRequest()`:

```java
        Image image = new Image() {
            @Override
            public boolean handleConnectorRequest(VaadinRequest request,
                                                  VaadinResponse response, String path) throws IOException {
                DownloadStream stream = null;
                String[] parts = path.split("/", 2);
                String key = parts[0];

                VaadinSession session = getSession();
                session.lock();
                try {
                    Resource resource = getResource(key);
                    if (!(resource instanceof ConnectorResource)) {
                        return false;
                    }
                    stream = ((ConnectorResource) resource).getStream();
                } finally {
                    session.unlock();
                }
                stream.writeResponse(request, response);
                return true;
            }
        };
```
