### ISSUE TITLE
NPE closing sessions under low-memory condition

### ISSUE THREAD

**Issue by enver-haase** [vaadin/framework#12204]
Only use GitHub issues for bugs and feature requests.   
For general support from the community, see https://vaadin.com/forum

NOTE: Issues for Vaadin Flow (Vaadin v10 Java Framework) should go to https://github.com/vaadin/flow

To make sure we can quickly validate and fix the bug, please provide as much as possible of the following information:
- Vaadin Framework version (e.g. 8.3.1)
8.3.3
- Browser version
Dunno
- Web container name and version
Tomcat
- Description of the bug
- Minimal reproducible example
Hard to reproduce
- Expected behavior
no NPE
- Actual behavior
NPE

17-Feb-2021 07:31:15.658 WARNING [Catalina-utility-2] org.apache.catalina.core.StandardContext.backgroundProcess Exception processing manager [PersistentManager[StandardEngine[Catalina].StandardHost[localhost].StandardContext[/fmi]]] background process
java.lang.NullPointerException
at com.vaadin.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:2010)
at com.vaadin.server.VaadinService.accessSession(VaadinService.java:1978)
at com.vaadin.server.VaadinSession.access(VaadinSession.java:1418)
at com.vaadin.server.VaadinService.fireSessionDestroy(VaadinService.java:529)
at com.vaadin.server.VaadinSession.valueUnbound(VaadinSession.java:314)
at org.apache.catalina.session.StandardSession.removeAttributeInternal(StandardSession.java:1831)
at org.apache.catalina.session.StandardSession.expire(StandardSession.java:853)
at org.apache.catalina.session.StandardSession.isValid(StandardSession.java:656)
at org.apache.catalina.session.PersistentManagerBase.processExpires(PersistentManagerBase.java:432)
at org.apache.catalina.session.ManagerBase.backgroundProcess(ManagerBase.java:591)
at org.apache.catalina.core.StandardContext.backgroundProcess(StandardContext.java:5574)
at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1353)
at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1357)
at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1357)
at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1335)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.base/java.lang.Thread.run(Thread.java:834)
17-Feb-2021 10:05:35.398 SEVERE [Catalina-utility-2] org.apache.catalina.core.ContainerBase.threadStart Exception processing background thread
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
at org.apache.catalina.core.ContainerBase.threadStart(ContainerBase.java:1276)
at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessorMonitor.run(ContainerBase.java:1322)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.OutOfMemoryError: Java heap space

**Comment by enver-haase** [comment]
![Screenshot 2021-02-18 at 08 42 02](https://user-images.githubusercontent.com/7870436/108322341-a6734400-71c5-11eb-8065-24eb318c3f46.png)

**Comment by enver-haase** [comment]
I suspect getLockInstance() can return NULL under very specific circumstances and we should better protect against that.

**Comment by Ansku** [comment]
I'm not sure there is any way to protect against lack of memory causing unexpected behaviour. If there isn't enough memory for the lock to be there when it should, there probably isn't enough memory for workarounds either. Pretty much anything can go wrong when there isn't sufficient memory to perform the expected operations.

That said, Vaadin 8.3.3 is pretty ancient by now and a lot of things have been improved by then, so it's possible that simply upgrading to 8.13.1 might help you to see less OutOfMemoryErrors in the first place -- at least as far as the framework goes. Upgrading obviously won't protect against any potential memory leaks caused by application-specific code.
