### ISSUE TITLE
[Flow-data:6.0.3] NPE when binder write has null value's number field.

### ISSUE THREAD

**Issue by CNBroderick** [vaadin/framework#12259]
#### showing
When binder . write Bean If Valid() process on a blank number field will be throw Null Pointer Exception.

#### position
com.vaadin.flow.data.binder.Binder.BindingImpl#writeFieldValue

#### can use this to replace error code.
``` java
if(!Objects.equals(field.getValue(), converted))
```

#### my binder code
```java
         NumberField maxPenalty = new NumberField();
        binder.forField(maxPenalty)
                .withNullRepresentation(0d)
                .withValidator(a -> a == null || a >= 0, "error message")
                .bind(Contract::getMaxPenalty, Contract::setMaxPenalty);

        BinderValidationStatus<Contract> validate = binder.validate();
        if (validate.isOk()) {
            binder.writeBeanIfValid(contract);
            return null;
        }
```

#### source code
```java
        private BindingValidationStatus<TARGET> writeFieldValue(BEAN bean) {
            assert bean != null;

            Result<TARGET> result = doConversion();
            if (!isReadOnly()) {
                result.ifOk(value -> {
                    setter.accept(bean, value);
                    if (value != null) {
                        FIELDVALUE converted = convertToFieldType(value);
                        // IF not input number field anything, there will throw NPE. (null.equals())
                        if (!field.getValue().equals(converted)) {  
                            getField().setValue(converted);
                        }
                    }
                });
            }
            return toValidationStatus(result);
        }

```

#### errors
```
java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "com.vaadin.flow.component.HasValue.getValue()" is null
	at com.vaadin.flow.data.binder.Binder$BindingImpl.lambda$writeFieldValue$5169480d$1(Binder.java:1251)
	at com.vaadin.flow.data.binder.SimpleResult.handle(SimpleResult.java:77)
	at com.vaadin.flow.data.binder.ValidationResultWrap.handle(ValidationResultWrap.java:81)
	at com.vaadin.flow.data.binder.Result.ifOk(Result.java:145)
	at com.vaadin.flow.data.binder.Binder$BindingImpl.writeFieldValue(Binder.java:1247)
	at com.vaadin.flow.data.binder.Binder$BindingImpl.access$1600(Binder.java:1032)
	at com.vaadin.flow.data.binder.Binder.lambda$doWriteIfValid$4(Binder.java:1963)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.vaadin.flow.data.binder.Binder.doWriteIfValid(Binder.java:1962)
	at com.vaadin.flow.data.binder.Binder.writeBeanIfValid(Binder.java:1928)
```

**Comment by TatuLund** [comment]
The latest version of the code in master branch is using `!Objects.equals(field.getValue(), converted)` which should not trigger this NPE, so it seems to have been corrected already

https://github.com/vaadin/flow/blob/master/flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java#L1297
