### ISSUE TITLE
License checker in Framework 8.16.0 incompatible with the one in 23.1.3

### ISSUE THREAD

**Issue by enver-haase** [vaadin/framework#12549]
To make sure we can quickly validate and fix the bug, please provide as much as possible of the following information:
- Description of the bug

Using MPR and 8.16 and 23.1.3, it depends on the CLASSPATH order whether or not the system can come up.

Consider
```
	Caused by: java.lang.NoSuchMethodError: 'void com.vaadin.pro.licensechecker.LicenseChecker.setStrictOffline(boolean)'
		at com.vaadin.base.devserver.startup.DevModeInitializer.initDevModeHandler(DevModeInitializer.java:208)
		at com.vaadin.base.devserver.DevModeHandlerManagerImpl.initDevModeHandler(DevModeHandlerManagerImpl.java:80)
		at com.vaadin.base.devserver.startup.DevModeStartupListener.initialize(DevModeStartupListener.java:74)
		at com.vaadin.flow.server.startup.VaadinServletContextStartupInitializer.process(VaadinServletContextStartupInitializer.java:42)
```
where said method does not exist in the 8.16.0 version of LicenseChecker.java .

NOTE THE PROBLEM MAY OR MAY NOT SHOW.  I did not witness it in Linux, not in Windows either.
I reckon it is a classpath order thing.

- Minimal reproducible example

The most simple MPR project with said versions should show the problem.

- Expected behavior

Running up the system for a paying customer at least, validating the license okay

- Actual behavior

Exception as above

- Versions:
    - Vaadin Framework 8.16.0
    - Flow 23.1.3
    - MPR "mpr-v8" as from the BOM (6.0.1 apparently)
    - Java JRE / JDK: tested in 11 and 16 OpenJDK.
    - Operating System: macOS latest 
    - Browser (if applicable): n/a

**Comment by TatuLund** [comment]
Fixed by https://github.com/vaadin/framework-es/pull/40
