### ISSUE TITLE
java.lang.AssertionError: null in ConnectorTracker

### ISSUE THREAD

**Issue by nPraml** [vaadin/framework#12565]
Hi,

we check regularly the logs of our customers and an AssertionError occures very often since we updated the vaadin version from 8.16.1 to 8.17.0.
Stacktrace:

`java.lang.AssertionError: null
	at com.vaadin.ui.ConnectorTracker.getDiffState(ConnectorTracker.java:700)
	at com.vaadin.server.LegacyCommunicationManager.encodeState(LegacyCommunicationManager.java:96)
	at com.vaadin.server.AbstractClientConnector.encodeState(AbstractClientConnector.java:292)
	at com.vaadin.server.communication.SharedStateWriter.write(SharedStateWriter.java:67)
	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:176)
	at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:125)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:93)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1669)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:464)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:239)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:215)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)`

Can you explain it what does it mean and when/why does it happen?

Kind regards
Noemi (FOCONIS AG)

**Comment by TatuLund** [comment]
There was one fix, that was related to connector tracker in 8.16.0. That introduced a regression that was fixed in 8.16.1. But there is no changes in it between 8.16.1 and 8.17.0, so this is a bit surprising.

**Comment by nPraml** [comment]
since 28th October we have vaadin 8.17.0 and we get the exeception every day multiple times.

Can you explain it what does it mean and when/why can it happen?

**Comment by nPraml** [comment]
Hi, could you get a look at to this issue?
Can you explain it what does the exception mean and when/why can it happen?

**Comment by TatuLund** [comment]
> Can you explain it what does the exception mean and when/why can it happen?

I think the exception is possibly only if connector id is null.

**Comment by nPraml** [comment]
> > Can you explain it what does the exception mean and when/why can it happen?
> 
> I think the exception is possible only if connector id is null.

Yes I know that, but how can the connector id be null after update to vaadin 8.17.0?

**Comment by nPraml** [comment]
one more detail: when we updated the application from 8.16.1 to 8.17.0, the other app would be updated from 14.8.11 to 14.8.17

**Comment by nPraml** [comment]
Hi, can you give a statement if it can be caused by the vaadin 14 application?

**Comment by TatuLund** [comment]
> Hi, can you give a statement if it can be caused by the vaadin 14 application?

If you are using MPR and the Vaadin 8 application is embedded in Vaadin 14 using it, then yes. The MPR product is implemented in such a way that it interferes with couple of asserts. This has been "fixed" in Vaadin 8.19.0 so that it does not run those asserts if MPR is present.

**Comment by TatuLund** [comment]
@rPraml for me your latest comment seems not to be related to original question about the ConnectorTracker. So should you actually open a new ticket about this.

**Comment by TatuLund** [comment]
> We invalidate certain user-session with httpSession.removeSessionAttribute(vaadinService.getSessionAttributeName())

Why not httpSession.invalidate()?
