### ISSUE TITLE
Cannot invoke "org.atmosphere.cpr.AtmosphereResource.getBroadcaster()" because the return value of "com.vaadin.flow.server.communication.AtmospherePushConnection.getResource()" is null

### ISSUE THREAD

**Issue by pogocode** [vaadin/framework#12567]
Upon session destruction, the following stack trace is often seen:

```
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Push failed
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.vaadin.flow.server.FutureAccess.get(FutureAccess.java:62)
	at com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:2062)
	at com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:710)
	at com.xyz.ui.session.SessionHelper.accessWithTimeout(SessionHelper.java:139)
	at com.xyz.ui.session.VaadinSessionTracker.lambda$checkAllSessions$1(VaadinSessionTracker.java:128)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at com.xyz.ui.session.VaadinSessionTracker.checkAllSessions(VaadinSessionTracker.java:127)
	at com.xyz.util.ResourceWatcher$WatchedRunnable.run(ResourceWatcher.java:159)
	at com.xyz.multitenancy.RepoScopedRunnable.run(RepoScopedRunnable.java:23)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: Push failed
	at com.vaadin.flow.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:200)
	at com.vaadin.flow.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:175)
	at com.vaadin.flow.component.UI.close(UI.java:325)
	at com.vaadin.flow.server.VaadinService.lambda$fireSessionDestroy$20ed7015$1(VaadinService.java:646)
	at com.vaadin.flow.component.UI.accessSynchronously(UI.java:447)
	at com.vaadin.flow.component.UI.accessSynchronously(UI.java:408)
	at com.vaadin.flow.server.VaadinService.lambda$fireSessionDestroy$9c853e43$1(VaadinService.java:638)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:2059)
	... 13 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "org.atmosphere.cpr.AtmosphereResource.getBroadcaster()" because the return value of "com.vaadin.flow.server.communication.AtmospherePushConnection.getResource()" is null
	at com.vaadin.flow.server.communication.AtmospherePushConnection.sendMessage(AtmospherePushConnection.java:215)
	at com.vaadin.flow.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:198)
	... 22 common frames omitted

```

In turn, this means that any `SessionDestroyListener`s registered to be executed upon Vaadin session destruction will not be called (see `com.vaadin.flow.server.VaadinService#fireSessionDestroy`) as the exception is not caught.

Looking at the code, it seems that there is some attempt to guard against the `resource` being null, but it does appear that the `resource` is null at the point the push is attempted.

#Minimal Reproducible Example
Unfortunately I have not yet been able to reproduce this behaviour, but I am attempting to do so and will update the ticket if I am able to find an example.

#Expected behaviour

All `SessionDestroyListener`s should be allowed to run as part of session destruction, even in the case of issues with the AtmospherePushConnection.

#Actual behaviour
Exception thrown and `SessionDestroyListener`s not executed.

Versions:
Vaadin Framework: 8.16.1
Flow: 23.2.5
MPR: 6.0.2
Java JRE / JDK: 17
openjdk 17.0.2 2022-01-18 LTS
OpenJDK Runtime Environment Corretto-17.0.2.8.1 (build 17.0.2+8-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.2.8.1 (build 17.0.2+8-LTS, mixed mode, sharing)

**Comment by pogocode** [comment]
Now updated with a minimal application exhibiting this behaviour. It seems that this exception occurs when the `HttpSession` is invalidated (which could be through some means other than via the Vaadin API, for example if the servlet container decides to destroy the seesion).

**Comment by pogocode** [comment]
I've also confirmed that same issue occurs on Vaadin 23.3.1 / MPR 6.1.0.

**Comment by TatuLund** [comment]
Thanks for the issue report. As this is quite clearly not bug in Vaadin 8, but possibly something either in Flow or MPR, I am going to move the ticket to either one of the repositories.

**Comment by TatuLund** [comment]
> MPR 6.1.0.

Just noting that 6.1.1 exists already. https://github.com/vaadin/multiplatform-runtime/releases/tag/6.1.1
