### ISSUE TITLE
OSGi error with Vaadin 8.25.1

### ISSUE THREAD

**Issue by mikke-alekstra** [vaadin/framework#12620]
Liferay 7.4.0
Vaadin 8.25.1

Deploying vaadin-server-8.25.1.jar causes the following error:

```
at com.liferay.portal.file.install.internal.DirectoryWatcher._process(DirectoryWatcher.java:1001) [bundleFile:?]
at com.liferay.portal.file.install.internal.DirectoryWatcher.run(DirectoryWatcher.java:272) [bundleFile:?]
Caused by: java.lang.IllegalArgumentException: invalid range "[${vaadin.licensechecker.version},${vaadin.licensechecker.version}]": invalid version "${vaadin.licensechecker.version}": non-numeric "${vaadin"
at org.osgi.framework.VersionRange.parseVersion(VersionRange.java:195) ~[org.eclipse.osgi.jar:?]
at org.osgi.framework.VersionRange.<init>(VersionRange.java:156) ~[org.eclipse.osgi.jar:?]
at org.eclipse.osgi.container.builders.OSGiManifestBuilderFactory.addPackageImports(OSGiManifestBuilderFactory.java:366) ~[org.eclipse.osgi.jar:?]
at org.eclipse.osgi.container.builders.OSGiManifestBuilderFactory.getPackageImports(OSGiManifestBuilderFactory.java:345) ~[org.eclipse.osgi.jar:?]
```

This might happen because META-INF/MANIFEST.MF in vaadin-server-8.25.1.jar contains
```
 :=optional;version="2.4.30.vaadin6",org.atmosphere.handler;resolution:=
 optional;version="2.4.30.vaadin6",org.atmosphere.util;resolution:=optio
 nal;version="2.4.30.vaadin6",com.vaadin.pro.licensechecker;version="[${
 vaadin.licensechecker.version},${vaadin.licensechecker.version}]",com.v
 aadin.osgi.resources;version="[8.25.1,8.25.1]",com.vaadin.shared;versio
 n="[8.25.1,8.25.1]",com.vaadin.shared.communication;version="[8.25.1,8.
 25.1]",com.vaadin.shared.customcomponent;version="[8.25.1,8.25.1]",com.
```

and OSGi requires numeric version numbers.

This same variable version number appears both in vaadin-server-8.25.1.jar and vaadin-server-mpr-jakarta-8.25.1.jar. I am unable to test vaadin-server-mpr-jakarta-8.25.1.jar but I assume OSGi will throw the same error for it, too.

**Comment by TatuLund** [comment]
This should be fixed in Vaadin 8.25.2 released today.
