### ISSUE TITLE
"Session already invalidated" error when detaching UI

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#4241]
**Originally by _archie172_**

___
Vaadin 7.1.0.

I am using push and the Vaadin servlet is configured with:
```
        <init-param>
            <param-name>closeIdleUIs</param-name>
            <param-value>true</param-value>
        </init-param>
        <init-param>
            <param-name>heartbeatInterval</param-name>
            <param-value>60</param-value>      <!-- UI's expire after (3.1 * heartbeatInterval) seconds -->
        </init-param>
        <init-param>
            <param-name>org.atmosphere.cpr.broadcasterCacheClass</param-name>
            <param-value>org.atmosphere.cache.UUIDBroadcasterCache</param-value>
        </init-param>
        <async-supported>true</async-supported>
```

When a UI instance was detached (not sure how as I didn't witness it), the following exception occurred:
```
javax.servlet.ServletException: com.vaadin.server.ServiceException: java.lang.IllegalStateException: getAttribute: Session already invalidated
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:238)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.dellroad.stuff.servlet.ExceptionLoggingFilter.doFilterInternal(ExceptionLoggingFilter.java:38)
        at com.patientexp.pcom.gui.support.AtmosphereHackExceptionLoggingFilter.doFilterInternal(AtmosphereHackExceptionLoggingFilter.java:30)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:947)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1009)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1686)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:722)
Caused by: com.vaadin.server.ServiceException: java.lang.IllegalStateException: getAttribute: Session already invalidated
        at com.vaadin.server.VaadinService.handleExceptionDuringRequest(VaadinService.java:1387)
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1341)
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:236)
        ... 22 more
Caused by: java.lang.IllegalStateException: getAttribute: Session already invalidated
        at org.apache.catalina.session.StandardSession.getAttribute(StandardSession.java:1165)
        at org.apache.catalina.session.StandardSessionFacade.getAttribute(StandardSessionFacade.java:122)
        at com.vaadin.server.WrappedHttpSession.getAttribute(WrappedHttpSession.java:54)
        at com.vaadin.server.VaadinService.getSessionLock(VaadinService.java:530)
        at com.vaadin.server.VaadinService.unlockSession(VaadinService.java:585)
        at com.vaadin.server.VaadinService.findOrCreateVaadinSession(VaadinService.java:598)
        at com.vaadin.server.VaadinService.findVaadinSession(VaadinService.java:479)
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1323)
        ... 23 more
```

The exception is thrown by the `unlockSession()` invocation in `findOrCreateVaadinSession()`:
```
        lockSession(wrappedSession);
        try {
            return doFindOrCreateVaadinSession(request, requestCanCreateSession);
        } finally {
            unlockSession(wrappedSession);
        }
```

Not sure how this happened... is it possible for an HTTP session to be invalidated in `doFindOrCreateVaadinSession()` ? I don't see how right off the bat.

Maybe there is some race condition somewhere on UI heartbeat timeout when also doing push?

___
 Imported from https://dev.vaadin.com/ issue #12282

**Comment by gauravbh1** [comment]
Hi,
Is there any update on this bug? We are using vaadin version 7.6.8 (application server is WAS Liberty profile) and we also see occasional exceptions like the one provided in the bug description.

javax.servlet.ServletException: com.vaadin.server.ServiceException: java.lang.IllegalStateException: The following session is not valid! qOZlr1lTSf_4AITFvhq8ykC
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:366)
	at com.ibm.igi.toolkit.web.gestione.servlet.CIServlet.service(Unknown Source)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1290)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:778)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:475)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:148)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:79)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1021)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1143)
	at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:82)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:945)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:280)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:967)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:359)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:318)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:471)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:405)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:285)
	at com.ibm.ws.http.channel.internal.inbound.HttpICLReadCallback.complete(HttpICLReadCallback.java:66)
	at com.ibm.ws.channel.ssl.internal.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1777)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:929)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1018)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:785)
Caused by: com.vaadin.server.ServiceException: java.lang.IllegalStateException: The following session is not valid! qOZlr1lTSf_4AITFvhq8ykC
	at com.vaadin.server.VaadinService.handleExceptionDuringRequest(VaadinService.java:1464)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1421)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:364)
	... 27 more
Caused by: java.lang.IllegalStateException: The following session is not valid! qOZlr1lTSf_4AITFvhq8ykC
	at com.ibm.ws.session.http.HttpSessionImpl.getAttribute(HttpSessionImpl.java:200)
	at com.ibm.ws.session.SessionData.getSessionValue(SessionData.java:310)
	at com.ibm.ws.session.SessionData.getAttribute(SessionData.java:170)
	at com.ibm.ws.session.HttpSessionFacade.getAttribute(HttpSessionFacade.java:137)
	at com.vaadin.server.WrappedHttpSession.getAttribute(WrappedHttpSession.java:54)
	at com.vaadin.server.VaadinService.getSessionLock(VaadinService.java:583)
	at com.vaadin.server.VaadinService.unlockSession(VaadinService.java:652)
	at com.vaadin.server.VaadinService.findOrCreateVaadinSession(VaadinService.java:670)
	at com.vaadin.server.VaadinService.findVaadinSession(VaadinService.java:527)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1403)

**Comment by shoikot** [comment]
In my case when I'm trying to use `VaadinService.reinitializeSession(VaadinService.getCurrentRequest()); `  getting the following exception 

```java.lang.IllegalStateException: setAttribute: Session already invalidated
	at org.apache.catalina.session.StandardSession.setAttribute(StandardSession.java:1814)
	at org.apache.catalina.session.StandardSessionFacade.setAttribute(StandardSessionFacade.java:178)
	at com.vaadin.server.WrappedHttpSession.setAttribute(WrappedHttpSession.java:59)
	at com.vaadin.server.VaadinService.reinitializeSession(VaadinService.java:1076)
	at com.testapp.gb.GroupBuilderApp.loginSuccessful(TestApp.java:4259)
	at com.testapp.gb.LoginLayout.handleLogin(LoginLayout.java:259)
	at com.testapp.LoginLayout$1.buttonClick(LoginLayout.java:182)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:200)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:163)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1015)
	at com.vaadin.ui.Button.fireClick(Button.java:377)
	at com.vaadin.ui.Button$1.click(Button.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:158)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:119)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:437)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:402)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:273)
	at com.vaadin.server.communication.PushHandler$2.run(PushHandler.java:148)
	at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:240)
	at com.vaadin.server.communication.PushHandler.onMessage(PushHandler.java:494)
	at com.vaadin.server.communication.PushAtmosphereHandler.onMessage(PushAtmosphereHandler.java:87)
	at com.vaadin.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:77)
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:199)
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:107)
	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:66)
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2075)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:571)
	at org.atmosphere.websocket.DefaultWebSocketProcessor$3.run(DefaultWebSocketProcessor.java:333)
	at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:328)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:425)
	at org.atmosphere.container.JSR356Endpoint$1.onMessage(JSR356Endpoint.java:214)
	at org.atmosphere.container.JSR356Endpoint$1.onMessage(JSR356Endpoint.java:211)
	at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:576)
	at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:879)
	at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:216)
	at org.glassfish.tyrus.core.frame.TextFrame.respond(TextFrame.java:139)
	at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:807)
	at org.glassfish.tyrus.core.TyrusWebSocketEngine$TyrusReadHandler.handle(TyrusWebSocketEngine.java:562)
	at org.glassfish.tyrus.servlet.TyrusHttpUpgradeHandler.onDataAvailable(TyrusHttpUpgradeHandler.java:173)
	at org.apache.catalina.connector.InputBuffer$ReadHandlerImpl.processDataAvailable(InputBuffer.java:477)
	at org.apache.catalina.connector.InputBuffer$ReadHandlerImpl.onDataAvailable(InputBuffer.java:437)
	at org.glassfish.grizzly.http.io.InputBuffer.invokeHandler(InputBuffer.java:1085)
	at org.glassfish.grizzly.http.io.InputBuffer.invokeHandlerOnProperThread(InputBuffer.java:1076)
	at org.glassfish.grizzly.http.io.InputBuffer.append(InputBuffer.java:959)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:271)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:539)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
	at java.lang.Thread.run(Thread.java:745)
]]```

**Comment by TatuLund** [comment]
Original patch fixed this was not linked to this ticket, here it is

https://github.com/vaadin/framework/commit/7212e02a9b4eb02759f7b2195187a6e6db6bfb33
