### ISSUE TITLE
File upload broken

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#4403]
**Originally by _agaton_**

___
Using JDK 7 and Glassfish 4, file upload doesn't seem to work.

An ArrayIndexOutOfBoundsException is thrown on line 2477 in 
AbstractCommunicationManager$SimpleMultiPartInputStream.getBuffered() method, eventually leading to an UploadException.

It seems to happen when nearing the end of the input stream reading. While debugging this I noticed that the contentLength input parameter (1642316) in streamToReceiver() method doesn't seem to match the size of the file I'm trying to upload (1642330).

The exception stack trace:

Caused by: java.lang.ArrayIndexOutOfBoundsException: 58
	at com.vaadin.terminal.gwt.server.AbstractCommunicationManager$SimpleMultiPartInputStream.getBuffered(AbstractCommunicationManager.java:2477)
	at com.vaadin.terminal.gwt.server.AbstractCommunicationManager$SimpleMultiPartInputStream.matchForBoundary(AbstractCommunicationManager.java:2457)
	at com.vaadin.terminal.gwt.server.AbstractCommunicationManager$SimpleMultiPartInputStream.read(AbstractCommunicationManager.java:2407)
	at java.io.InputStream.read(InputStream.java:179)
	at java.io.InputStream.read(InputStream.java:101)
	at com.vaadin.terminal.gwt.server.AbstractCommunicationManager.streamToReceiver(AbstractCommunicationManager.java:578)

___
 Imported from https://dev.vaadin.com/ issue #12508

**Comment by clavaud** [comment]
Dear,

This problem is still present on the 8.5.1
Line 292 should be : 
`doHandleSimpleMultipartFileUpload(session, request, response,
                    streamVariable, variableName, source,
                    contentType.split("boundary=")[1].split(";")[0]);`

instead of 
`doHandleSimpleMultipartFileUpload(session, request, response,
                    streamVariable, variableName, source,
                    contentType.split("boundary=")[1]);`

Problem is that boundary is not the last token.

Best regards
