### ISSUE TITLE
NullPointerException in VaadinService.findUI()

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5473]
**Originally by _archie172_**

___
Saw this NPE. I'm using Vaadin 7.1.8 but the same bug appears to be present in git master.

```
java.lang.NullPointerException
        at com.vaadin.server.VaadinSession.getForSession(VaadinSession.java:414)
        at com.vaadin.server.VaadinService.findUI(VaadinService.java:948)
        at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:272)
        at com.vaadin.server.communication.PushHandler.disconnect(PushHandler.java:429)
        at com.vaadin.server.communication.PushHandler.onDisconnect(PushHandler.java:407)
        at org.atmosphere.cpr.AtmosphereResourceImpl.onDisconnect(AtmosphereResourceImpl.java:824)
        at org.atmosphere.cpr.AtmosphereResourceImpl.notifyListeners(AtmosphereResourceImpl.java:768)
        at org.atmosphere.cpr.AtmosphereResponse.handleException(AtmosphereResponse.java:920)
        at org.atmosphere.cpr.AtmosphereResponse.flushBuffer(AtmosphereResponse.java:478)
        at org.atmosphere.cpr.AtmosphereInterceptorWriter.flush(AtmosphereInterceptorWriter.java:93)
        at org.atmosphere.cpr.AsyncIOWriterAdapter.flush(AsyncIOWriterAdapter.java:148)
        at org.atmosphere.cpr.AtmosphereResponse$4.flush(AtmosphereResponse.java:722)
        at com.vaadin.server.communication.PushHandler.onStateChange(PushHandler.java:390)
        at org.atmosphere.cpr.DefaultBroadcaster.invokeOnStateChange(DefaultBroadcaster.java:1163)
        at org.atmosphere.cpr.DefaultBroadcaster.prepareInvokeOnStateChange(DefaultBroadcaster.java:1183)
        at org.atmosphere.cpr.DefaultBroadcaster.executeAsyncWrite(DefaultBroadcaster.java:1054)
        at org.atmosphere.cpr.DefaultBroadcaster$3.run(DefaultBroadcaster.java:636)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
```

The method `VaadinService.findUI()` fails to verify the the return value from `request.getWrappedSession()` is not null. It can be null (as proven by the above stack trace) and should be checked first before invoking `VaadinSession.getForSession()`.

___
 Imported from https://dev.vaadin.com/ issue #14301

**Comment by TatuLund** [comment]
I checked the latest Vaadin 8.11.2 code, and it has appropriate null check and the implementation has been refactored after this report. It can't happen in this way anymore.
