### ISSUE TITLE
Session idle timeout causes "Cannot call sendError() after the response has been committed" exception

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#5750]
**Originally by _archie172_**

___
Using Tomcat 7.0.42 behind and Apache proxy with push enabled and Vaadin 7.2.7.

I have sessions configured to idle timeout after a while. This didn't work for a long time (bug #12139) but now works again in 7.3. Horray.

Unfortunately, now when idle timeout occurs, this exception is logged:

```
java.lang.IllegalStateException: Cannot call sendError() after the response has been committed
        at org.apache.catalina.connector.ResponseFacade.sendError(ResponseFacade.java:451)
        at org.apache.catalina.servlets.DefaultServlet.serveResource(DefaultServlet.java:835)
        at org.apache.catalina.servlets.DefaultServlet.doGet(DefaultServlet.java:411)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.dellroad.stuff.servlet.ExceptionLoggingFilter.doFilterInternal(ExceptionLoggingFilter.java:38)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1023)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1686)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
```

Due to the problem occurring after Vaadin has processed the request, it's hard to tell what's causing it or even if it's a Vaadin bug rather than a Tomcat bug.

___
 Imported from https://dev.vaadin.com/ issue #14811

**Comment by brunoienne** [comment]
Hey @vaadin-bot  did you solve your problem? I'm having the same issue in Java.My pages become slow

**Comment by elmot** [comment]
Isn't it too short request timeout at your apache proxy?
And I don't think we can fix this without reproducible example.

**Comment by brunoienne** [comment]
I solve it.Actually was a query taking 22s to execute and bring data.The jsp loads faster than the query so after the response has been comitted the application cannot call sendError().

**Comment by elmot** [comment]
Not a bug.
