### ISSUE TITLE
Push / Broadcasting causing memory issues

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6021]
**Originally by _l.pereira.fernandez@gmail.com_**

___
Hi there,

We have been running an application with no issues at all until we enabled push and started to broadcast messages to UIs.

We are using Vaadin 7.3.2 on Tomcat v7.0.55, and we strictly followed the indications provided in https://vaadin.com/book/vaadin7/-/page/advanced.push.html building the Broadcaster class and overriding the method in our UI. The broadcasting functionality works fine, but when we redeploy the application we now see these error messages in Tomcat log:

dic 21, 2014 12:29:58 PM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SEVERE: The web application [] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
dic 21, 2014 12:29:58 PM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [] appears to have started a thread named [pool-1-thread-1] but has failed to stop it. This is very likely to create a memory leak.
dic 21, 2014 12:29:58 PM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [] created a ThreadLocal with key of type [com.google.api.client.util.escape.Platform$1] (value [com.google.api.client.util.escape.Platform$1@7d3be970]) and a value of type [char[]] (value [[C@685af84b]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
dic 21, 2014 12:29:58 PM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [] created a ThreadLocal with key of type [com.vaadin.util.CurrentInstance$1] (value [com.vaadin.util.CurrentInstance$1@2c633973]) and a value of type [java.util.HashMap] (value [{class com.vaadin.server.VaadinService=com.vaadin.util.CurrentInstance@2650c3c9, class com.vaadin.server.VaadinSession=com.vaadin.util.CurrentInstance@65d4c6, class com.vaadin.ui.UI=com.vaadin.util.CurrentInstance@1d74135e}]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

Besides this, we have enabled Tomcat to persist sessions across restarts, so with the first interaction on the application after the restarts, the UI hangs and the loader indicator starts blinking and never ends, and we see this new error in the log file:

dic 21, 2014 12:30:33 PM org.atmosphere.container.TomcatWebSocketUtil doService
SEVERE: 
org.atmosphere.cpr.DefaultBroadcasterFactory$BroadcasterCreationException: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@33742ed5 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@10aebc57[Terminated, pool size # 0, active threads0, queued tasks # 0, completed tasks27]
	at org.atmosphere.cpr.DefaultBroadcasterFactory.createBroadcaster(DefaultBroadcasterFactory.java:147)
	at org.atmosphere.cpr.DefaultBroadcasterFactory.lookup(DefaultBroadcasterFactory.java:208)
	at org.atmosphere.cpr.DefaultBroadcasterFactory.get(DefaultBroadcasterFactory.java:121)
	at org.atmosphere.cpr.DefaultBroadcasterFactory.get(DefaultBroadcasterFactory.java:108)
	at org.atmosphere.cpr.AsynchronousProcessor.configureWorkflow(AsynchronousProcessor.java:206)
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:138)
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:95)
	at org.atmosphere.container.TomcatWebSocketUtil.doService(TomcatWebSocketUtil.java:154)
	at org.atmosphere.container.Tomcat7Servlet30SupportWithWebSocket.service(Tomcat7Servlet30SupportWithWebSocket.java:62)
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:1802)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:432)
	at org.atmosphere.websocket.DefaultWebSocketProcessor$2.run(DefaultWebSocketProcessor.java:285)
	at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:280)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:303)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatchReader(DefaultWebSocketProcessor.java:647)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:404)
	at org.atmosphere.container.TomcatWebSocketHandler.onTextData(TomcatWebSocketHandler.java:100)
	at org.apache.catalina.websocket.StreamInbound.doOnTextData(StreamInbound.java:191)
	at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:139)
	at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:88)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:724)
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@33742ed5 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@10aebc57[Terminated, pool size # 0, active threads0, queued tasks # 0, completed tasks27]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2048)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:821)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:325)
	at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleWithFixedDelay(ScheduledThreadPoolExecutor.java:594)
	at org.atmosphere.cache.UUIDBroadcasterCache.start(UUIDBroadcasterCache.java:97)
	at org.atmosphere.cpr.DefaultBroadcaster.start(DefaultBroadcaster.java:551)
	at org.atmosphere.cpr.DefaultBroadcasterFactory.createBroadcaster(DefaultBroadcasterFactory.java:136)
	... 26 more   
   
In order to continue we have to reload the app in the browser and that causes a new error to be shown in the log file:

dic 21, 2014 12:31:24 PM org.apache.coyote.AbstractProtocol$AbstractConnectionHandler process
SEVERE: Error reading request, ignored
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@386315ad rejected from java.util.concurrent.ScheduledThreadPoolExecutor@10aebc57[Terminated, pool size # 0, active threads0, queued tasks # 0, completed tasks27]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2048)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:821)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:325)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:546)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.close(DefaultWebSocketProcessor.java:482)
	at org.atmosphere.container.TomcatWebSocketHandler.onClose(TomcatWebSocketHandler.java:80)
	at org.apache.catalina.websocket.StreamInbound.doOnClose(StreamInbound.java:226)
	at org.apache.catalina.websocket.StreamInbound.closeOutboundConnection(StreamInbound.java:210)
	at org.apache.catalina.websocket.StreamInbound.onData(StreamInbound.java:141)
	at org.apache.coyote.http11.upgrade.UpgradeProcessor.upgradeDispatch(UpgradeProcessor.java:88)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:724)

We have also noticed that if we repeat the previous process a few times (redeploying and interacting, redeploying and interacting, ....) we end up crashing the Tomcat server with a java.lang.OutOfMemoryError: Permgen space

___
 Imported from https://dev.vaadin.com/ issue #15442

**Comment by TatuLund** [comment]
This should be fixed in Vaadin 8.11.1
