### ISSUE TITLE
Can't import both Reindeer and Valo in the same theme

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6303]
**Originally by @Artur-**

___
After upgrading to 7.4.0.rc1, the sampler theme compilation throws
```
Feb 10, 2015 11:42:48 PM com.vaadin.sass.internal.tree.controldirective.IfElseDefNode traverse
SEVERE: null
com.vaadin.sass.internal.expression.exception.IncompatibleUnitsException: Incompatible units found in: '-26px'
	at com.vaadin.sass.internal.parser.LexicalUnitImpl.checkAndGetUnit(LexicalUnitImpl.java:409)
	at com.vaadin.sass.internal.parser.LexicalUnitImpl.minus(LexicalUnitImpl.java:392)
	at com.vaadin.sass.internal.expression.BinaryOperator$10.evalInternal(BinaryOperator.java:144)
	at com.vaadin.sass.internal.expression.BinaryOperator.eval(BinaryOperator.java:228)
	at com.vaadin.sass.internal.expression.BinaryExpression.eval(BinaryExpression.java:48)
	at com.vaadin.sass.internal.expression.ArithmeticExpressionEvaluator.evaluate(ArithmeticExpressionEvaluator.java:116)
	at com.vaadin.sass.internal.parser.SassExpression.evaluateFunctionsAndExpressions(SassExpression.java:220)
	at com.vaadin.sass.internal.tree.RuleNode.traverse(RuleNode.java:108)
	at com.vaadin.sass.internal.tree.Node.traverseChildren(Node.java:227)
	at com.vaadin.sass.internal.tree.Node.traverseChildren(Node.java:214)
	at com.vaadin.sass.internal.tree.KeyframeSelectorNode.traverse(KeyframeSelectorNode.java:49)
	at com.vaadin.sass.internal.tree.Node.traverseChildren(Node.java:227)
	at com.vaadin.sass.internal.tree.Node.traverseChildren(Node.java:214)
	at com.vaadin.sass.internal.tree.KeyframesNode.traverse(KeyframesNode.java:54)
	at com.vaadin.sass.internal.tree.controldirective.TemporaryNode.traverse(TemporaryNode.java:71)
	at com.vaadin.sass.internal.visitor.IfElseNodeHandler.traverseChild(IfElseNodeHandler.java:66)
	at com.vaadin.sass.internal.visitor.IfElseNodeHandler.traverse(IfElseNodeHandler.java:45)
	at com.vaadin.sass.internal.tree.controldirective.IfElseDefNode.traverse(IfElseDefNode.java:49)
	at com.vaadin.sass.internal.tree.controldirective.TemporaryNode.traverse(TemporaryNode.java:71)
	at com.vaadin.sass.internal.visitor.MixinNodeHandler.replaceMixinNode(MixinNodeHandler.java:75)
	at com.vaadin.sass.internal.visitor.MixinNodeHandler.replaceMixins(MixinNodeHandler.java:45)
	at com.vaadin.sass.internal.visitor.MixinNodeHandler.traverse(MixinNodeHandler.java:34)
```

There is no context information and quite unclear why "-26px" is incompatible with something

___
 Imported from https://dev.vaadin.com/ issue #16652

**Comment by jouni** [comment]
I would say this is a wontfix. @Artur- can make the decision.
