### ISSUE TITLE
Elemental JSON on server-side exception

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#6668]
**Originally by @macprzepiora**

___
Hard to tell what caused an exception

elemental.json.JsonException: Invalid number literal: 666|
	at elemental.json.impl.JsonTokenizer.getNumberForLiteral(JsonTokenizer.java:284)
	at elemental.json.impl.JsonTokenizer.getValueForLiteral(JsonTokenizer.java:307)
	at elemental.json.impl.JsonTokenizer.nextValue(JsonTokenizer.java:175)
	at elemental.json.impl.JreJsonFactory.parse(JreJsonFactory.java:64)
	at elemental.json.impl.JsonUtil.parse(JsonUtil.java:200)
	at com.vaadin.server.communication.ServerRpcHandler$RpcRequest.<init>(ServerRpcHandler.java:81)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:176)
	at com.vaadin.server.communication.PushHandler$2.run(PushHandler.java:147)
	at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:226)
	at com.vaadin.server.communication.PushHandler.onMessage(PushHandler.java:486)
	at com.vaadin.server.communication.PushAtmosphereHandler.onMessage(PushAtmosphereHandler.java:88)
	at com.vaadin.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:78)
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:205)
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:104)
	at org.atmosphere.container.JettyWebSocketUtil.doService(JettyWebSocketUtil.java:70)
	at org.atmosphere.container.JettyServlet30AsyncSupportWithWebSocket.service(JettyServlet30AsyncSupportWithWebSocket.java:52)
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2075)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:570)
	at org.atmosphere.websocket.DefaultWebSocketProcessor$3.run(DefaultWebSocketProcessor.java:332)
	at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:327)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:424)
	at org.atmosphere.container.JettyWebSocketHandler.onMessage(JettyWebSocketHandler.java:97)
	at org.eclipse.jetty.websocket.WebSocketConnectionRFC6455$WSFrameHandler.onFrame(WebSocketConnectionRFC6455.java:835)
	at org.eclipse.jetty.websocket.WebSocketParserRFC6455.parseNext(WebSocketParserRFC6455.java:349)
	at org.eclipse.jetty.websocket.WebSocketConnectionRFC6455.handle(WebSocketConnectionRFC6455.java:225)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)

___
 Imported from https://dev.vaadin.com/ issue #17656

**Comment by mazchaz** [comment]
I have also seen this issue occur in Vaadin 8.2.1. 

It seems to happen when a Thread calls the _receiveMessage_ method in **AtmospherePushConnection.java** before having called the connect method. 

This means the resource is null and the start of the json payload doesn't get stripped off by the rest of the _recieveMessage_ logic, leading to the

>  Invalid Number literal

 error mentioned earlier.

Tracing this back, it appears to mean the POST branch is executed before the GET branch in the below code snippet from **PushAtmosphereHandler.java:** 

```
  if (req.getMethod().equalsIgnoreCase("GET")) {
            onConnect(resource);
        } else if (req.getMethod().equalsIgnoreCase("POST")) {
            onMessage(resource);
        }
```

**Comment by AlexByte** [comment]
This error occurs continuously at every session in Vaadin 8 with Push enabled.

**Comment by TatuLund** [comment]
The most likely cause for this exception is that widgetset and server are not the same version. Hence it may happen, that some data to be exchanged has been changed by structure. Server side expects the json to contain a numeric value and there is conversion error, since client has sent non-number. Re-compiling the widgetset should fix the issue.
