### ISSUE TITLE
vaadin-shared-deps 1.0.3 does not load into OSGi frameworks

### ISSUE THREAD

**Issue by vaadin-bot** [vaadin/framework#7254]
**Originally by _djmcgreal_**

___
Caused by: java.lang.NumberFormatException: For input string: "rebased"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)[:1.8.0_60]
	at java.lang.Integer.parseInt(Integer.java:580)[:1.8.0_60]
	at java.lang.Integer.parseInt(Integer.java:615)[:1.8.0_60]
	at org.osgi.framework.Version.parseInt(Version.java:168)[org.osgi.core-6.0.0.jar:]
	... 20 more

This is because the OSGi headers for Export-Package are specifying versions as 15.0.rebased, whereas OSGi versioning expects three digits before the qualifier.

1.0.2 of the library is fine.

___
 Imported from https://dev.vaadin.com/ issue #19160

**Comment by elmot** [comment]
OSGi support is completely rewritten in 8.1, most probably we can close this ticket.
