### ISSUE TITLE
Vaadin 7.7.6 on Tomcat 8.5.6 Servlet 3.1.0 woes

### ISSUE THREAD

**Issue by xenoterracide** [vaadin/framework#8026]
http://stackoverflow.com/q/40088934/206466 another user experiencing the same issue

stackoverflow.com/q/24080541/206466 says it's a problem with `ServletContext` duplicates

On spring platform 2.0.8 which has Servlet 3.1.0 and tomcat 8.0.37, we upgraded to 7.7.6 without issue. Now I'm upgrading to Platform Athens SR1 which has Servlet 3.1.0,  tomcat 8.5.6 and we're still using 7.7.6 I've hit this issue. our standalone servers (to contrast embedded tomcat, running for local dev)  still have 8.0.37 and I don't see this error on those.

I found this
```
[Loaded javax.servlet.ServletContext from file:/Users/calebcushing/.m2/repository/com/vaadin/external/‌​gwt/gwt-user/2.7.0.v‌​aadin4/gwt-user-2.7.‌​0.vaadin4.jar] –
```
here's the full stack
```
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:911)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:890)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1403)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1393)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	... 6 more
Caused by: org.apache.catalina.LifecycleException: Failed to start component [Pipeline[StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5099)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 6 more
Caused by: org.apache.catalina.LifecycleException: Failed to start component [org.apache.catalina.authenticator.NonLoginAuthenticator[]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	at org.apache.catalina.core.StandardPipeline.startInternal(StandardPipeline.java:170)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 8 more
Caused by: java.lang.NoSuchMethodError: javax.servlet.ServletContext.getVirtualServerName()Ljava/lang/String;
	at org.apache.catalina.authenticator.AuthenticatorBase.startInternal(AuthenticatorBase.java:1125)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 10 more

Dec 16, 2016 10:55:58 AM org.apache.catalina.core.ContainerBase startInternal
SEVERE: A child container failed during start
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost]]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:911)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:791)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:356)
	at com.mckesson.dex.ui.Start.startTomcat(Start.java:129)
	at com.mckesson.dex.ui.Start.main(Start.java:63)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1403)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1393)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.catalina.LifecycleException: A child container failed during start
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:890)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 6 more
```

Here are what I believe to be the relevant deps, this class is run from test

```
mvn dependency:list | grep -e vaadin -e servlet-api -e tomcat | sort -u
[INFO]    com.vaadin.external.atmosphere:atmosphere-runtime:jar:2.2.9.vaadin2:compile
[INFO]    com.vaadin.external.flute:flute:jar:1.3.0.gg2:compile
[INFO]    com.vaadin.external.gwt:gwt-elemental:jar:2.7.0.vaadin4:provided
[INFO]    com.vaadin.external.gwt:gwt-servlet:jar:2.7.0.vaadin4:runtime
[INFO]    com.vaadin.external.gwt:gwt-user:jar:2.7.0.vaadin4:provided
[INFO]    com.vaadin.external.json:json:jar:0.0.20080701:compile
[INFO]    com.vaadin.external.slf4j:vaadin-slf4j-jdk14:jar:1.6.1:compile
[INFO]    com.vaadin:vaadin-client-compiled:jar:7.7.6:compile
[INFO]    com.vaadin:vaadin-client:jar:7.7.6:provided
[INFO]    com.vaadin:vaadin-push:jar:7.7.6:compile
[INFO]    com.vaadin:vaadin-sass-compiler:jar:0.9.13:compile
[INFO]    com.vaadin:vaadin-server:jar:7.7.6:compile
[INFO]    com.vaadin:vaadin-shared:jar:7.7.6:compile
[INFO]    com.vaadin:vaadin-themes:jar:7.7.6:compile
[INFO]    javax.servlet:javax.servlet-api:jar:3.1.0:provided # originally set to compile, provided is an attempted fix
[INFO]    javax.servlet:servlet-api:jar:2.5:provided 
[INFO]    org.apache.tomcat.embed:tomcat-embed-core:jar:8.5.6:test
[INFO]    org.apache.tomcat.embed:tomcat-embed-el:jar:8.5.6:test
[INFO]    org.apache.tomcat.embed:tomcat-embed-jasper:jar:8.5.6:test
[INFO]    org.apache.tomcat:tomcat-api:jar:8.5.6:test
[INFO]    org.apache.tomcat:tomcat-el-api:jar:8.5.6:test
[INFO]    org.apache.tomcat:tomcat-jasper-el:jar:8.5.6:test
[INFO]    org.apache.tomcat:tomcat-jasper:jar:8.5.6:test
[INFO]    org.apache.tomcat:tomcat-jsp-api:jar:8.5.6:test
[INFO]    org.apache.tomcat:tomcat-juli:jar:8.5.6:test
[INFO]    org.apache.tomcat:tomcat-servlet-api:jar:8.5.6:test
[INFO]    org.apache.tomcat:tomcat-util-scan:jar:8.5.6:test
[INFO]    org.apache.tomcat:tomcat-util:jar:8.5.6:test
[INFO]    org.vaadin.addon:jfreechartwrapper:jar:3.0.2:compile
[INFO]    org.vaadin.addons:jain-assoc:jar:1.1.4:compile
[INFO]    org.vaadin.addons:jain-i18N:jar:1.1.4:compile
[INFO]    org.vaadin.addons:tokenfield:jar:7.0.1:compile
```

**Comment by Legioth** [comment]
The problem is most likely `gwt-user` is included on the server-side classpath even though that should not be necessary with general Vaadin Framework usage.

You can fix this by ensuring you set `<scope>provided</scrope>` for `vaadin-client-compiler` and/or `gwt-user` in your `pom.xml` file(s). As an additional benefit, you'll probably also get faster redeploys since the `.war` file will be smaller.

**Comment by xenoterracide** [comment]
so `gwt-user` is part of the client, for build only? we build our own widgetset so I'm guessing that this was included in the wrong spot when we did that...

**Comment by xenoterracide** [comment]
actually we set it to runtime, because we removed our compile time dependencies on it, is it even needed for us?

**Comment by xenoterracide** [comment]
```
[INFO] +- com.vaadin:vaadin-client:jar:7.7.6:provided
[INFO] |  +- com.vaadin:vaadin-shared:jar:7.7.6:compile
[INFO] |  \- com.vaadin.external.gwt:gwt-elemental:jar:2.7.0.vaadin4:provided
[INFO] |     \- com.vaadin.external.gwt:gwt-user:jar:2.7.0.vaadin4:provided
[INFO] |        \- javax.validation:validation-api:jar:sources:1.0.0.GA:provided
```

hmm so it is provided already... but our `Start` class for embedded mode is in `test`...

**Comment by Artur-** [comment]
Are you using Spring Boot for this?

**Comment by xenoterracide** [comment]
No to Spring Boot, we do use Spring IO Platform and this is using embedded tomcat from `test`.

Here's how we're resolving it currently though not sure our pom's are the best they can be (still recovering from a lot of legacy code and guess work)

In our widgetset build we have

```		
<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>vaadin-client</artifactId>
			<version>${vaadin.version}</version>
			<scope>provided</scope>
	</dependency>
```

in our -ui module which imports our widgetset (to ensure these artifacts don't end up in our test scope)

```
		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>vaadin-client</artifactId>
			<version>${vaadin.version}</version>
			<scope>provided</scope>
			<exclusions>
				<exclusion>
					<groupId>com.vaadin.external.gwt</groupId>
					<artifactId>gwt-user</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```
