### ISSUE TITLE
ServerRpcHandler -> java.lang.OutOfMemoryError: Requested array size exceeds VM limit

### ISSUE THREAD

**Issue by SNVID** [vaadin/framework#8058]
Hi,

We are occasionally receiving an out of memory error (stacktrace below). We have added a JavaScriptFunction to return some base64 text back to the server. This works fine most of the time but sometimes the rpc json string sent to the server isn’t complete. It may be that the network dropped out on the client? Or something. 

So what is happening is the Server RPC handler gets incomplete Json and tries to parse it causing an infinite loop and blowing the memory. 

Vaadin Version: 7.7.4

Stacktrace:
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
at java.util.Arrays.copyOf(Arrays.java:3332)
at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:622)
at java.lang.StringBuilder.append(StringBuilder.java:202)
at elemental.json.impl.JsonTokenizer.nextString(JsonTokenizer.java:144)
at elemental.json.impl.JsonTokenizer.nextValue(JsonTokenizer.java:169)
at elemental.json.impl.JsonTokenizer.parseArray(JsonTokenizer.java:190)
at elemental.json.impl.JsonTokenizer.nextValue(JsonTokenizer.java:173)
at elemental.json.impl.JsonTokenizer.parseArray(JsonTokenizer.java:190)
at elemental.json.impl.JsonTokenizer.nextValue(JsonTokenizer.java:173)
at elemental.json.impl.JsonTokenizer.parseArray(JsonTokenizer.java:190)
at elemental.json.impl.JsonTokenizer.nextValue(JsonTokenizer.java:173)
at elemental.json.impl.JsonTokenizer.parseArray(JsonTokenizer.java:190)
at elemental.json.impl.JsonTokenizer.nextValue(JsonTokenizer.java:173)
at elemental.json.impl.JsonTokenizer.parseObject(JsonTokenizer.java:229)
at elemental.json.impl.JsonTokenizer.nextValue(JsonTokenizer.java:171)
at elemental.json.impl.JreJsonFactory.parse(JreJsonFactory.java:64)
at elemental.json.impl.JsonUtil.parse(JsonUtil.java:200)
at com.vaadin.server.communication.ServerRpcHandler$RpcRequest.<init>(ServerRpcHandler.java:86)
at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:231)
at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90)
at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1422)
at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:379)
at com.vaadin.addon.touchkit.server.TouchKitServlet.service(TouchKitServlet.java:63)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)

How to reproduce: 
Send truncated Json code back to the server e.g.
{"csrfToken":"6a975b88-5078-4bec-bd56-c6f307e0d8dc","rpc":[["151","com.vaadin.ui.JavaScript$JavaScriptCallbackRpc","call",["XXX",["data:image/png;base64,iXXXXXX

**Comment by aboydude** [comment]
We experienced the same in our Vaadin project, only the json data was cleartext, not base64, but also incomplete. It could be network error, but it's irrelevant, broken json packages should be handled.

Anyway the effect is the same, ran out of memory and the application is gone.

**Comment by elmot** [comment]
Fixed with #9236 #9237 #9056
