### ISSUE TITLE
Idea: non-reflection based Event router for component event firing

### ISSUE THREAD

**Issue by jreznot** [vaadin/framework#8090]
Now stack traces of component events are deep and go through reflection call:
```
java.lang.RuntimeException: Exception
	at com.haulmont.cuba.web.gui.components.WebButton.lambda$new$61446b05$1(WebButton.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:200)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:163)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1037)
	at com.vaadin.ui.Button.fireClick(Button.java:377)
	at com.vaadin.ui.Button$1.click(Button.java:54)
```
How about using non-reflection based EventRouter similar to [this](https://github.com/cuba-platform/cuba/blob/master/modules/global/src/com/haulmont/bali/events/EventRouter.java) ?

**Comment by jreznot** [comment]
Also, please take a look at my prototype of EventRouter with Consumer<T> listeners instead of concrete listener interface per each event type: https://github.com/strangeway-org/event-router

**Comment by Legioth** [comment]
A solution that is compatible with the current `EventRouter` architecture is actually more complex than the alternatives suggested here.

`EventRouter` supports "hierarchical" events; a listener registered for `Component.Event` will get any subclass event, e.g. `FocusEvent`, `BlurEvent` and `ClickEvent`. The utility of this architecture is questionable, but it still means that we cannot easily make changes to the architecture without severely impacting backwards compatibility.

**Comment by elmot** [comment]
Yes, we have tried to replace EventRouter already, but that breaks compatibility and we can not do that in this release.

**Comment by Legioth** [comment]
> Yes, we have tried to replace EventRouter already, but that breaks compatibility and we can not do that in this release.

This enhancement is still valid for some future release (i.e. Framework 9.0+). It's only 8.x that is out of scope at this point.
