### ISSUE TITLE
Vaadin 8 seems to require bean validation library, but this is not declared in documentation

### ISSUE THREAD

**Issue by mstahv** [vaadin/framework#8141]
With Vaadin 8.0.0.beta1 and BeanBinder you'll get an exception if bean validation library is not present. In previous versions Vaadin versions this was not required.

Either the functionality should be similar as before (just gracefully continue with limited featureset) or documentation and archetypes should be fixed.

See https://github.com/mstahv/v-leaflet/pull/144#issuecomment-270355264

**Comment by Legioth** [comment]
We might want to do add a more rigorous test as a separate submodule in https://github.com/vaadin/framework/tree/master/test without any bean validation implementation in its `pom.xml`?

**Comment by denis-anisimov** [comment]
Can be added, yes.

**Comment by denis-anisimov** [comment]
@mstahv 
One more time : I cannot reproduce this !

I need a code snippet which I can use to reproduce the issue.

The simplest usecase doesn't reveal any issues.

As I said: we have a test for this already. Test is working.
I will create one more test (as a separate module which has no Validation API dependency).
I already have it locally and it also works which shows that the first one (which actually does some classloader manipulation) also works.

So I cannot do anything without additional information.

**Comment by mstahv** [comment]
Sorry Denis, have been super busy week. Did you try with the referenced v-leaflet project. The exception happens in its test, see the discussion there, Ilia also knows that project. To reproduce, you need to remove the validator dependency, that was added as a workaround.

Sent from my iPhone

**Comment by denis-anisimov** [comment]
OK, thanks.

**Comment by denis-anisimov** [comment]
For the future references :
- the project is outdated (BeanBinder doesn't no longer exist)
- there are references to 8.0-beta1 for compatibility module though everything else is 8.0-SNAPSHOT
- quite tricky to build (g-leaflet 1.4.0-SNAPSHOT dependency  is required though it's not available as a binary. One has to build it and install locally from sources)
- mistakes in the documentation about UI tests
- spend a lot of time to get it working and find a stacktrace (would be awesome to see the stacktrace in the ticket description from the very beginning).

Now the localized issue:

the root cause is : there is validation-api/1.0.0.GA/validation-api-1.0.0.GA.jar in the project's classpath. But there are no any JSR-303 provider available.
As a result : our code detects the JSR 303 API presence and thinks that bean validation can be used. Then BeanValidator class becomes available to validation and used for this. But it requires a validation provider available. And it fails at this point.
The stacktrace is below.

java.lang.ExceptionInInitializerError
	at com.vaadin.data.validator.BeanValidator.getJavaxBeanValidatorFactory(BeanValidator.java:145)
	at com.vaadin.data.validator.BeanValidator.getJavaxBeanValidator(BeanValidator.java:154)
	at com.vaadin.data.validator.BeanValidator.apply(BeanValidator.java:120)
	at com.vaadin.data.Binder$ValidatorAsConverter.convertToModel(Binder.java:989)
	at com.vaadin.data.Converter$2.lambda$convertToModel$5daf174e$1(Converter.java:167)
	at com.vaadin.data.SimpleResult.flatMap(SimpleResult.java:64)
	at com.vaadin.data.Converter$2.convertToModel(Converter.java:167)
	at com.vaadin.data.Binder$BindingImpl.doConversion(Binder.java:838)
	at com.vaadin.data.Binder$BindingImpl.doValidation(Binder.java:858)
	at com.vaadin.data.Binder$BindingImpl.access$1300(Binder.java:760)
	at com.vaadin.data.Binder.validateBindings(Binder.java:1596)
	at com.vaadin.data.Binder.doWriteIfValid(Binder.java:1451)
	at com.vaadin.data.Binder.writeBean(Binder.java:1406)
	at org.vaadin.addon.leaflet.demoandtestapp.JtsPointFieldTest.lambda$getTestComponent$166a13ad$1(JtsPointFieldTest.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:211)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:174)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1028)
	at com.vaadin.ui.Button.fireClick(Button.java:369)
	at com.vaadin.ui.Button$1.click(Button.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:158)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:119)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:443)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:415)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1450)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:380)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:313)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:626)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:546)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.validation.ValidationException: Unable to find a default provider
	at javax.validation.Validation$GenericBootstrapImpl.configure(Validation.java:264)
	at javax.validation.Validation.buildDefaultValidatorFactory(Validation.java:111)
	at com.vaadin.data.validator.BeanValidator$LazyFactoryInitializer.getFactory(BeanValidator.java:190)
	at com.vaadin.data.validator.BeanValidator$LazyFactoryInitializer.<clinit>(BeanValidator.java:187)
	... 56 more

**Comment by denis-anisimov** [comment]
I'm not sure about the issue:
- this is the behavior which is preserved from previous version: implementation wise the code is the same: only the `javax.validation.Validation` class presence is checked (in the old impl and in the new one)
- is this a user error to have in the classpath JS-303 API and don't have implementation for it ?
- I would not consider this is as a user error actually but rather our implementation error but the reason I'm not sure : the implementation is the same is in V7.

I think we should fix this by checking the presence of a valdiation provider impl.
I'm going to do that unless there are objections.

**Comment by mstahv** [comment]
@denis-anisimov I think your analysis is correct and suggested workaround is correct. In v-leaflet (and I guess in pretty many add-on projects and actual application projects with custom GWT extensions), the validation-api comes in via vaadin-client (via GWT stuff). Thus the check would be better if it relied on a concrete implementation, even though on actual concrete deployments the validation-api brought in by GWT should not be there.

**Comment by Legioth** [comment]
Unrelated question, but why does the project have `vaadin-client` on the server-side classpath?

**Comment by mstahv** [comment]
It is in provided scope for GWT compilation. It probably is not on server class path in this case (only in testing environment), but I have seen many Vaadin apps where it is there for some reason. In Spring Boot apps if you have custom widgets in the same project (which is stupid in general).
