### ISSUE TITLE
NullPointerException if calling VaadinServletRequest.logout()

### ISSUE THREAD

**Issue by doctorsmith** [vaadin/framework#8238]
Hello,

I got an exception when calling the HttpServletRequest.logout() method in Vaadin 8.0.0 beta1.
The simplest way to logout when using external SSO like Keycloak is to call the HttpServletRequest.logout() method or VaadinServletRequest.logout()

`java.lang.NullPointerException
	at com.vaadin.ui.ConnectorTracker.removeUnregisteredConnectors(ConnectorTracker.java:422)
	at com.vaadin.ui.ConnectorTracker.cleanConnectorMap(ConnectorTracker.java:282)
	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:334)
	at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:124)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:92)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1450)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:380)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)`

The problem lies in the ConnectorTracker.removeUnregisteredConnectors.
`GlobalResourceHandler globalResourceHandler = uI.getSession()
                .getGlobalResourceHandler(false);`

There is no check if the session really exists.

**Comment by Artur-** [comment]
Hi,

Are you able to create some sort of test case for this issue? It's hard to say where the root problem is without any way to test it.

https://vaadin.com/forum#!/thread/9145228 contains a possible workaround.
