### ISSUE TITLE
NullPointerException when serializing SharedState containing java.util.Map with null key

### ISSUE THREAD

**Issue by geert3** [vaadin/framework#8244]
Tested with Vaadin 7.6.6 and 7.7.6

The following is the basic code: some CustomComponent with a SharedState containing a Map:
```
public class GraphComponent extends CustomComponent {
	@Override
	protected GraphComponentState getState() {
		return (GraphComponentState)super.getState();
	}

	public void setId2Comment(Map<String, String> id2comment) {
	    getState().id2comment = id2comment;
	}
}

public class GraphComponentState extends AbstractComponentState {
...
	@DelegateToWidget
	public Map<String, String> id2comment;
...
}
```

Filling the map with a null key leads to NPE when serializing:
```
Map<String, String> foo = new HashMap<>();
foo.put(null, "somevalue");
myGraph.setId2Comment(foo);
```

Exception when serializing to client:
```
22:31:15,651 SEVERE [com.vaadin.server.DefaultErrorHandler] (default task-54) : java.lang.NullPointerException
	at elemental.json.impl.JreJsonObject.stringifyOrder(JreJsonObject.java:43)
	at elemental.json.impl.JreJsonObject.traverse(JreJsonObject.java:168)
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82)
	at elemental.json.impl.JreJsonObject.traverse(JreJsonObject.java:171)
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82)
	at elemental.json.impl.JreJsonObject.traverse(JreJsonObject.java:171)
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82)
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:72)
	at elemental.json.impl.JsonUtil.stringify(JsonUtil.java:281)
	at elemental.json.impl.JsonUtil.stringify(JsonUtil.java:267)
	at elemental.json.impl.JsonUtil.stringify(JsonUtil.java:252)
	at com.vaadin.server.communication.SharedStateWriter.write(SharedStateWriter.java:81)
	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:161)
	at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:124)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:92)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1422)
	at com.vaadin.cdi.server.VaadinCDIServletService.handleRequest(VaadinCDIServletService.java:92)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:379)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at io.undertow.websockets.jsr.JsrWebSocketFilter.doFilter(JsrWebSocketFilter.java:129)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:284)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:263)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:174)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:793)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Tested with Vaadin 7.6.6 and 7.7.6

**Comment by JoergOstertag** [comment]
I have a similar looking NPE with Vaadin 8.0.6
Using the following class as a Field in a design and having value set to null results in a NPE:

`Jul 10, 2017 12:56:05 PM com.vaadin.server.DefaultErrorHandler doDefault
SCHWERWIEGEND:
java.lang.NullPointerException
        at elemental.json.impl.JsonUtil.quote(JsonUtil.java:208)
        at elemental.json.impl.JsonUtil$StringifyJsonVisitor.visit(JsonUtil.java:96)
        at elemental.json.impl.JreJsonString.traverse(JreJsonString.java:81)
        at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82)
        at elemental.json.impl.JreJsonObject.traverse(JreJsonObject.java:177)
        at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82)
        at elemental.json.impl.JreJsonObject.traverse(JreJsonObject.java:177)
        at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82)
        at elemental.json.impl.JreJsonArray.traverse(JreJsonArray.java:164)
        at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82)
        at elemental.json.impl.JreJsonArray.traverse(JreJsonArray.java:164)
        at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82)
        at elemental.json.impl.JreJsonArray.traverse(JreJsonArray.java:164)
        at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82)
        at elemental.json.impl.JreJsonArray.traverse(JreJsonArray.java:164)
        at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82)
        at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:72)
        at elemental.json.impl.JsonUtil.stringify(JsonUtil.java:281)
        at elemental.json.impl.JsonUtil.stringify(JsonUtil.java:267)
        at elemental.json.impl.JsonUtil.stringify(JsonUtil.java:252)
        at com.vaadin.server.communication.ClientRpcWriter.write(ClientRpcWriter.java:106)
        at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:190)
        at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:124)
        at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:92)
        at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
        at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1464)
        at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:381)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
`

`
public class NlsTextDTO {

	String value = "";

	public NlsTextDTO() {
	}

	public NlsTextDTO(String string) {
		this.value = string;
	}

	public String getValue() {
		// For Vaadin 8 never return NULL Value. Otherwise vaadin 8 crashes with
		// NPE in the JSON Module.
		// if (null == value) {
		// return "";
		//
		// }
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Override
	public String toString() {
		return (getValue());
	}

}
`
