### ISSUE TITLE
Building lazy binding for ComboBox seems to be very buggy

### ISSUE THREAD

**Issue by mstahv** [vaadin/framework#8496]
version: 8.0.0.beta2

I tried to work with lazy binding to ComboBox, but faced couple of issue:

The binding I used looked like this:

        comboBox.setDataProvider(new CallbackDataProvider<>(
                query -> {
                    return Service.findByFirstName(query.getFilter().orElse(""), query.getOffset(), query.getLimit()).stream();
                }
                , query-> {
                    return (int) Service.countByFirstName(query.getFilter().orElse(""));
                }));

Commented output form the log of the Service class:

# Initial load, no popup opened:
countByFirstName 
count result: 1000
findByFirstName  0 40
findByFirstName  40 960

# Opening popup, no selection or filtering
countByFirstName 
count result: 1000
findByFirstName  0 1000

# Writing X to combobox filterbox (the datasource contains no names starting with X):

countByFirstName x
count result: 0
findByFirstName x 50 950
Feb 08, 2017 12:07:40 AM com.vaadin.server.DefaultErrorHandler doDefault
SEVERE: 
java.lang.IllegalArgumentException: fromIndex(50) > toIndex(0)
	at java.util.ArrayList.subListRangeCheck(ArrayList.java:1006)
	at java.util.ArrayList.subList(ArrayList.java:996)
	at com.mycompany.v8tests.Service.findByFirstName(Service.java:93)
	at com.mycompany.v8tests.MyUI.lambda$showComboBox$f019fb75$1(MyUI.java:71)
	at com.vaadin.data.provider.CallbackDataProvider.fetchFromBackEnd(CallbackDataProvider.java:88)
	at com.vaadin.data.provider.AbstractBackEndDataProvider.fetch(AbstractBackEndDataProvider.java:60)
	at com.vaadin.data.provider.DataCommunicator.beforeClientResponse(DataCommunicator.java:249)
	at com.vaadin.server.communication.UidlWriter.write(UidlWriter.java:110)
	at com.vaadin.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:124)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:92)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1450)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:380)

**Comment by mstahv** [comment]
In RC2 the situation is definitely better, but the lazy loading is still quite buggy.

 * Going to a new page in UI always makes a new call to the backend, even though there would still be lot of rows in the "cache"
 * Making similar "X" search as in description, returning 0 for the count, now makes a fetch call to backend, fetching 50 rows from index 0. I'd expect it to do no fetch to backend at all if there are no results.

**Comment by pleku** [comment]
The initial load and opening of pop-up have been fixed as part of this ticket, split out the remaining issues to #8665 and #8666 .
