### ISSUE TITLE
Internal error if ComboBox itemCaptionGenerator returns null

### ISSUE THREAD

**Issue by Artur-** [vaadin/framework#8630]
8.0.0.rc1:

```
ComboBox<MyBean> cb = new ComboBox<>();
cb.setItems(new MyBean());
cb.setItemCaptionGenerator(item -> null);
```

results in
```
Caused by: java.lang.NullPointerException: null
	at elemental.json.impl.JsonUtil.quote(JsonUtil.java:208) ~[vaadin-shared-8.0.0.rc1.jar:8.0.0.rc1]
	at elemental.json.impl.JsonUtil$StringifyJsonVisitor.visit(JsonUtil.java:96) ~[vaadin-shared-8.0.0.rc1.jar:8.0.0.rc1]
	at elemental.json.impl.JreJsonString.traverse(JreJsonString.java:81) ~[vaadin-shared-8.0.0.rc1.jar:8.0.0.rc1]
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82) ~[vaadin-shared-8.0.0.rc1.jar:8.0.0.rc1]
	at elemental.json.impl.JreJsonObject.traverse(JreJsonObject.java:177) ~[vaadin-shared-8.0.0.rc1.jar:8.0.0.rc1]
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82) ~[vaadin-shared-8.0.0.rc1.jar:8.0.0.rc1]
	at elemental.json.impl.JreJsonArray.traverse(JreJsonArray.java:164) ~[vaadin-shared-8.0.0.rc1.jar:8.0.0.rc1]
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82) ~[vaadin-shared-8.0.0.rc1.jar:8.0.0.rc1]
	at elemental.json.impl.JreJsonArray.traverse(JreJsonArray.java:164) ~[vaadin-shared-8.0.0.rc1.jar:8.0.0.rc1]
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82) ~[vaadin-shared-8.0.0.rc1.jar:8.0.0.rc1]
	at elemental.json.impl.JreJsonArray.traverse(JreJsonArray.java:164) ~[vaadin-shared-8.0.0.rc1.jar:8.0.0.rc1]
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82) ~[vaadin-shared-8.0.0.rc1.jar:8.0.0.rc1]
	at elemental.json.impl.JreJsonArray.traverse(JreJsonArray.java:164) ~[vaadin-shared-8.0.0.rc1.jar:8.0.0.rc1]
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:82) ~[vaadin-shared-8.0.0.rc1.jar:8.0.0.rc1]
	at elemental.json.impl.JsonVisitor.accept(JsonVisitor.java:72) ~[vaadin-shared-8.0.0.rc1.jar:8.0.0.rc1]
	at elemental.json.impl.JsonUtil.stringify(JsonUtil.java:281) ~[vaadin-shared-8.0.0.rc1.jar:8.0.0.rc1]
	at elemental.json.impl.JsonUtil.stringify(JsonUtil.java:267) ~[vaadin-shared-8.0.0.rc1.jar:8.0.0.rc1]
	at elemental.json.impl.JsonUtil.stringify(JsonUtil.java:252) ~[vaadin-shared-8.0.0.rc1.jar:8.0.0.rc1]
	at com.vaadin.server.communication.ClientRpcWriter.write(ClientRpcWriter.java:106) ~[vaadin-server-8.0.0.rc1.jar:8.0.0.rc1]
```

It's quite impossible to understand where this comes from. 
Maybe the correct way to handle it would be to convert null to "".

**Comment by pleku** [comment]
Currently the javadocs mention that _not null_, so value should be at least verified immediately

**Comment by pleku** [comment]
It seems that this only an issue for the single selects. `AbstractMultiSelect` changes `null` to `""`
