### ISSUE TITLE
v8Grid sort throws NullPointerException

### ISSUE THREAD

**Issue by gokhanoner** [vaadin/framework#8644]
When a column contains null values, sorting on that column throws below exception & clear all data from grid:

`java.lang.NullPointerException: null
	at com.vaadin.ui.Grid$Column.compareMaybeComparables(Grid.java:890) ~[vaadin-server-8.0.0.jar:8.0.0]
	at com.vaadin.ui.Grid$Column.lambda$new$bcd0aaa9$3(Grid.java:881) ~[vaadin-server-8.0.0.jar:8.0.0]
	at java.util.Comparator.lambda$thenComparing$36697e65$1(Comparator.java:217) ~[na:1.8.0_66]`

issue is `Grid.Column.hasCommonComparableBaseType` return false if any of the values are null, and then `return compareComparables(a.toString(), b.toString());` throws the NullPointerException.

**Comment by elmot** [comment]
There is a patch for this #8610

**Comment by pleku** [comment]
Fixed in 8.0.1 by 2c58ba7
