### ISSUE TITLE
Binder.readBean with null fields causes NPE in AbstractTextField

### ISSUE THREAD

**Issue by mvysny** [vaadin/framework#8664]
I am implementing a simple CRUD dialog. I create a new JPA bean and pass it to Binder.readBean, however it fails with:
```
java.lang.NullPointerException: value cannot be null
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.vaadin.ui.AbstractTextField.setValue(AbstractTextField.java:96)
	at com.vaadin.ui.AbstractTextField.setValue(AbstractTextField.java:46)
	at com.vaadin.data.Binder$BindingImpl.initFieldValue(Binder.java:890)
	at com.vaadin.data.Binder$BindingImpl.access$100(Binder.java:763)
	at com.vaadin.data.Binder.lambda$readBean$11(Binder.java:1380)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.vaadin.data.Binder.readBean(Binder.java:1380)
```
I understand that the problem here is that AbstractTextField disallows nulls. Yet, maybe Binder should handle this gracefully? Also, please the error message may be improved - the exception/stacktrace should mention the field in question.
Thanks! :)

**Comment by mvysny** [comment]
A workaround of calling withNullRepresentation("") for every AbstractTextField seem to work nicely.

**Comment by tnus** [comment]
Any updates on this bug? Is it possible to allow null values in the text field, like the Vaadin 7 TextField?

**Comment by tsuoanttila** [comment]
This issue only exists when you have a conversion in your TextField. When you make the conversion, you should handle the `null` values as they are expected to be in your backend.

The TextField is a bit problematic on the semantics of when should a the content to be considered `null`. For example let's say empty string `""` is `null`. Then the user adds a character to text field and removes it. Did the user mean to input empty string or `null`? If at this point for every single application we assume to translate `"" -> null` we prevent the user from inputting the empty string, and if the coder decides that `null` from TextField is actually an empty string from the user leads to `textField.setValue(null)` would be actually interpreted as `textField.getValue("")` because of the assumption made earlier.

Because of these highly controversial things mentioned before, we decided not to allow `null` as value for TextField. It makes the use of the TextField safer for the user, and you never have to guess what is the user input. It is recommended to always use `.withNullRepresentation()` from binding when you might have a `null` in your model. This gives you the developer explicit control on how to handle it.

**Comment by mvysny** [comment]
From the framework's point of view it's definitely a good thing to make a difference between an empty string `""` and `null`, since those represent two distinct values which may represent different things in certain use cases.

However, Vaadin 8 `TextField` actually doesn't support that difference since it can't handle `null` values and will fail with an exception. Visually, `TextField` alone can't represent `null`: it cannot be string `""` nor `"null"` since `empty string != null` and `"null" != null`. Only a combination of `TextField` and a combo box could be able to represent null values as well, but that's out of the scope for TextField. So, the decision for TextField to avoid this empty string/null duality and not to support nulls is the correct one - this decision will avoid the controversial topic as described by @tsuoanttila .

However, let's leave the pure academical grounds here, and enter the dirty reality. In my use-case (entering user's name, street, etc) the empty string is not really different from `null` and means the same thing - missing value. Typically I'll have a NotNull and MinLength(1) validation annotations here, to force the user to type something here. And I'd expect the vast majority of use-cases to actually be like this. However, current Vaadin implementation is that in majority of cases it will simply fail with a NPE. That is sub-optimal and I believe we can do better.

I'd appreciate if Vaadin at least failed with "call `.withNullRepresentation("")` on a binder to convert nulls to empty strings" or similar; Binder would then have a `.withNullRepresentation("")` helper method which would just set up the conversion for all fields. What do you think?

**Comment by tnus** [comment]
Thanks for the quick response. 

new TextField().setValue(null) will lead to a NPE. In my application i have often the use case where i bind a bean with string properties or use the textfield directly.

binder.bind(fName, "name");

is for me much faster to write than

binder.forField(fVersion).withNullRepresentation("").bind("name");

My current workaround is a TextField which extends the VaadinTextField and handles the null values.

public class NTextField extends TextField {
	@Override
	public void setValue(String value) {
		super.setValue(value == null ? "" : value);
	}
	@Override
	public String getValue() {
		String value = super.getValue();
		return StringUtils.isEmpty(value) ? null : value;
	}
}

**Comment by mvysny** [comment]
I agree - for me the simplest case of using `binder.bind(field, "field")` ends with a NPE on null-valued bean. In another words, the simplest use-case fails with a NPE which will confuse new users. That is definitely something we need to rethink since this seriously hampers the Vaadin experience both for new users, and for users switching to Vaadin 8.

To improve the common use-case experience, I propose to change the Binder to call `withNullRepresentation("")` implicitly for all TextFields; this is no longer academically-accurate but improves real-world experience a lot. If someone needs to differentiate between "" and null then I'd introduce a method `.withNullRepresentation(null)` or something like that.

**Comment by tsuoanttila** [comment]
I've tested this a couple of times today and for me the following code (given `Person` has `String firstName`) works:
```
TextField nameField = new TextField();
Binder<Person> binder = new Binder<>(Person.class);
Person p = new Person();
p.setFirstName(null);
binder.bind(nameField, "firstName");
binder.readBean(p);
```

If you're encountering exceptions with a code like that, please provide a code example where the issue can be seen, since I was not able to reproduce it. Binder should use the default null representation path, which in a TextField is `null -> ""` without any conversion when getting the value back from the TextField. If in some case it is not using it in the automatic parts, that is indeed a bug and should be fixed ASAP.

The idea of adding a generic null representation should work for this particular case, and we should have some mechanism to provide it, but it would be null representation for a specific type of data (in this case string) and couldn't be used in other cases than data that is String. I'll take this idea to discussion later this week or early next week.

For @tnus, good to hear your project has a solution, and seems to me it works the way you want it to work!

**Comment by mvysny** [comment]
@tsuoanttila I'm so sorry, you're right - I reviewed my code one more time and I have found out that I actually have a custom converter. An innocent one, it only trims strings ;)

> When you make the conversion, you should handle the null values as they are expected to be in your backend.

Can you please explain the reasoning behind this please, since I'm not sure I understand. I'm using just a generic converter which trims strings, and I do not understand the reasoning why such generic converter would disable the automatic null conversions.

**Comment by tsuoanttila** [comment]
From the point of view of Binder every single converter, no matter how small and innocent, is a black box of magic. We can't know what the converter does when the it is applied . Something we could do is to provide a "one-way converter" for doing things like `String::trim`, but then again, you could just go through the text fields and run the trimming operation to every TextField in your form just before commit.

If you're applying any kind of conversion from the model value to the text field, you will need a null check if your model can have null values. A simple `.withConverter(str -> str.trim(), str -> str.trim())` throws a nasty NPE when a `null` value is passed in.

The logging in this case definitely needs to be improved, so we catch the exceptions when applying the conversions and validations to give the developer a better chance to find out which binding is in a faulty state.

**Comment by mvysny** [comment]
> every single converter, no matter how small and innocent, is a black box of magic.

True.

I expected that any call `withConverter` chains after the "implicit" converter which convert nulls to empty strings. Yet it is not done so - the implicit converter is removed and thus nulls suddenly pass through to TextFields. This is the bit that's surprising to me.

It is true though that the custom converter may re-introduce nulls and thus we're back with NPEs in TextFields.

**Comment by mehdi-vaadin** [comment]
If the 'implicit' converter was the first in the chain and converted `null` value to an empty `String`, the programmer who wants to implement their own converter wouldn't be able to distinct `null` and empty `String`. So, the implemented converter must be ahead in the chain to make its own the decision about `null` values.

**Comment by mvysny** [comment]
This bug is primarily about allowing/disallowing nulls into a `TextField`. I've therefore created a separate bug report rgd improvement of Binder's error message: https://github.com/vaadin/framework/issues/11109

**Comment by mddorfli** [comment]
FYI, I also encountered this problem and worked around it by creating my own subclass of StringToLongConverter:

```
public class LongFieldConverter extends StringToLongConverter {
    @Override
    public String convertToPresentation(Long value, ValueContext context) {
        String text = super.convertToPresentation(value, context);
        return text==null?"":text;
    }
}
```
