### ISSUE TITLE
[v8] Field binding with a converter sends `null` values into the field regardless of other validators/asRequired before

### ISSUE THREAD

**Issue by christoph-frick** [vaadin/framework#8725]
Given a binder setup for a TextField with an converter set e.g. an
StringToBigDecimalConverter.  Having that converter set, the bound TextField
will receive incoming `null` values and therefor fail with an assert.  Trying
to "protect" from this by e.g.  setting a validator or with an `asRequired`
beforehand, does not prevent it.

Removing the converter no longer gives the exception.   Extending that
converter and just return an empty string intead of the `null` prevents it too.

Important parts of the trace:

        at java.util.Objects.requireNonNull(Objects.java:228) ~[na:1.8.0_121]
        at com.vaadin.ui.AbstractTextField.setValue(AbstractTextField.java:96) ~[vaadin-server-8.0-SNAPSHOT.jar:8.0-SNAPSHOT]
        at com.vaadin.ui.AbstractTextField.setValue(AbstractTextField.java:46) ~[vaadin-server-8.0-SNAPSHOT.jar:8.0-SNAPSHOT]
        at com.vaadin.data.Binder$BindingImpl.initFieldValue(Binder.java:890) ~[vaadin-server-8.0-SNAPSHOT.jar:8.0-SNAPSHOT]
        at com.vaadin.data.Binder$BindingImpl.access$100(Binder.java:763) ~[vaadin-server-8.0-SNAPSHOT.jar:8.0-SNAPSHOT]
        at com.vaadin.data.Binder.lambda$setBean$10(Binder.java:1341) ~[vaadin-server-8.0-SNAPSHOT.jar:8.0-SNAPSHOT]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[na:1.8.0_121]
        at com.vaadin.data.Binder.setBean(Binder.java:1341) ~[vaadin-server-8.0-SNAPSHOT.jar:8.0-SNAPSHOT]
        at com.vaadin.data.Binder$setBean$0.call(Unknown Source) ~[na:na]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[groovy-2.4.7.jar!/:2.4.7]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[groovy-2.4.7.jar!/:2.4.7]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-2.4.7.jar!/:2.4.7]
        at MyUI$_init_closure1.doCall(vaadin-binder-converter-null.groovy:30) ~[na:na]

Code to reproduce:

	// run with `spring run --watch vaadin.groovy`
	@Grab('com.vaadin:vaadin-spring-boot-starter:2.0.0')
	import com.vaadin.ui.*
	import com.vaadin.data.*
	
	@groovy.transform.ToString(includeNames=true)
	class Bean {
		BigDecimal value = null
	}
	
	class BeanForm extends FormLayout {
		TextField valueField = new TextField("Value")
		Label valueStatusLabel = new Label()
		BeanForm() { addComponents(valueField, valueStatusLabel) }
	}
	
	@com.vaadin.spring.annotation.SpringUI
	@com.vaadin.annotations.Theme("valo")
	class MyUI extends UI {
	        protected void init(com.vaadin.server.VaadinRequest request) {
			def binder = new Binder<Bean>(Bean)
			def form = new BeanForm()
			binder.forField(form.valueField).
				withStatusLabel(form.valueStatusLabel).
				asRequired("Required!").
				// XXX: without the converter there is no error; rewriting the converter so it returns "" instad of null works too
				withConverter(new com.vaadin.data.converter.StringToBigDecimalConverter("Enter a number")).
				bind('value')
			setContent(new VerticalLayout(
				new Button("Set bean (gives assert error)", { binder.setBean(new Bean()); binder.validate() } as Button.ClickListener),
				form
			))
		}
	}

**Comment by elmot** [comment]
Please use `withNullRepresentation` method. It was done specially for this case.

**Comment by christoph-frick** [comment]
Thanks.  Works now without assert.
