### ISSUE TITLE
Exception when Opening a Spreadsheet (xlsx) with cells containing concatenated Links

### ISSUE THREAD

**Issue by mwxwidmann** [vaadin/framework#8768]
This happened in Vaadin 8.0.1 with Spreadsheet 2.
When I create a Spreadsheet component using an Excel file in Spreadsheet 2, there's an Exception if a cell contains a Hyperlink that's a concatenation of two fields.
The cell's formula looks like this:
=LINK(VERKETTEN($G$1;A2))       _// VERKETTEN is German for CONCATENATE._ 
It seems that a specific format is expected in the linked cell, that's not there. The CONCATENATE should be executed before the link is interpreted.

Attached you'll find an Excel file containing such a concatenated link.
[test.xlsx](https://github.com/vaadin/framework/files/824555/test.xlsx)

StackTrace: 
`java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1954)
	at com.vaadin.addon.spreadsheet.DefaultHyperlinkCellClickHandler.getHyperlinkFunctionCellAddress(DefaultHyperlinkCellClickHandler.java:124)
	at com.vaadin.addon.spreadsheet.Spreadsheet.loadHyperLinks(Spreadsheet.java:3160)
	at com.vaadin.addon.spreadsheet.Spreadsheet.loadHyperLinks(Spreadsheet.java:3122)
	at com.vaadin.addon.spreadsheet.Spreadsheet.loadCells(Spreadsheet.java:2985)
	at com.vaadin.addon.spreadsheet.Spreadsheet.onSheetScroll(Spreadsheet.java:767)
	at com.vaadin.addon.spreadsheet.SpreadsheetHandlerImpl.onSheetScroll(SpreadsheetHandlerImpl.java:57)
	at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:116)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:443)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:415)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1464)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:380)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:225)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:524)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by hesara** [comment]
This repository is for Vaadin Framework only. Please file Vaadin Spreadsheet issues to its repository at https://github.com/vaadin/spreadsheet/ .

**Comment by mwxwidmann** [comment]
Sorry for the confusion. I re-posted this to the spreadsheet repo as you suggested.
