### ISSUE TITLE
Binder.bindInstanceFields() overwrites existing bindings

### ISSUE THREAD

**Issue by twiggledi** [vaadin/framework#8858]
**Vaadin Version: 8.0.2 (vaadin-server-8.0.2)**

Seems binder.bindInstanceFields() tries to bind existing fields again.

In documentation you can read following:
```
binder.forField(yearOfBirth)
  .withConverter(
    new StringToIntegerConverter("Please enter a number"))
  .bind(Person::getYearOfBirth, Person::setYearOfBirth));

binder.bindInstanceFields(this); // Should not touch yearOfBirth, which is already configured
```
I try to bind a Double manually and the rest by using bindInstanceFields, then I get the Exception:
```
java.lang.IllegalStateException: Property type 'java.lang.Double' doesn't match the field type 'java.lang.String'. Binding should be configured manually using converter.
```

Seems that already bind fields are not filtered out.

**To Reproduce:**
```
public class TestBindingComponent extends VerticalLayout {

	private TextField name = new TextField("Name");
	private TextField price = new TextField("Price");

	private BeanValidationBinder<Article> binder = new BeanValidationBinder<>(Article.class);

	public TestBindingComponent() {
		this.addComponents(this.name, this.price);
		this.binder.forField(this.price).withConverter(new StringToDoubleConverter("Please enter a double value")).bind(Article::getPrice, Article::setPrice);
		this.binder.bindInstanceFields(this);
	}

	public class Article {

		private String name;

		private Double price;

		public Double getPrice() {
			return this.price;
		}

		public void setPrice(Double price) {
			this.price = price;
		}

		public String getName() {
			return this.name;
		}

		public void setName(String name) {
			this.name = name;
		}
	}

}
```
I expect that field "name" will be bind by bindInstanceFields() and field "price" will not be touched, it tries to bind again, although it is bound manually). That you can read in javadoc of the method "It's always possible to do custom binding for any field: the bindInstanceFields(Object) method doesn't override existing bindings."

But that leads to following StackTrace:
```
java.lang.IllegalStateException: Property type 'java.lang.Double' doesn't match the field type 'java.lang.String'. Binding should be configured manually using converter.
	at com.vaadin.data.Binder.bindProperty(Binder.java:2203) ~[vaadin-server-8.0.2.jar:8.0.2]
	at com.vaadin.data.Binder.lambda$null$20(Binder.java:2129) ~[vaadin-server-8.0.2.jar:8.0.2]
	at com.vaadin.data.Binder.handleProperty(Binder.java:2295) ~[vaadin-server-8.0.2.jar:8.0.2]
	at com.vaadin.data.Binder.lambda$bindInstanceFields$21(Binder.java:2127) ~[vaadin-server-8.0.2.jar:8.0.2]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_121]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_121]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[na:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_121]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_121]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_121]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_121]
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:484) ~[na:1.8.0_121]
	at com.vaadin.data.Binder.bindInstanceFields(Binder.java:2131) ~[vaadin-server-8.0.2.jar:8.0.2]
	at de.bertelsmann.praemienpflege.web.TestBindingComponent.<init>(TestBindingComponent.java:26) ~[classes/:na]
```

**Comment by monestri** [comment]
This issue makes bindInstanceFields() unusable for me.

**Comment by gerib** [comment]
This issue makes `bindInstanceFields()` unusable for a number of people.

See [ StackOverflow: Does Vaadin 8 `Binder::bindInstanceFields` only work with String data types?](http://stackoverflow.com/questions/43154002/does-vaadin-8-binderbindinstancefields-only-work-with-string-data-types) and [Vaadin Framework Data Binding forum: Binding from Integer not working](https://vaadin.com/forum#!/thread/15385912).
