### ISSUE TITLE
VaadinService.reinitializeSession doesn't work with 8.0.3+ 

### ISSUE THREAD

**Issue by Jmanuel4SandMan** [vaadin/framework#8924]
Broken in: 8.0.3 and 8.0.4, still works as of 8.0.2

When running 

		`VaadinService.reinitializeSession(VaadinService.getCurrentRequest());` 
before login we get 
`java.lang.IllegalStateException: setAttribute: Session [2E3C456321B6211DD0F23F20B44BC42A] has already been invalidated
	at org.apache.catalina.session.StandardSession.setAttribute(StandardSession.java:1450) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.session.StandardSession.setAttribute(StandardSession.java:1415) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.session.StandardSessionFacade.setAttribute(StandardSessionFacade.java:137) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at com.vaadin.server.WrappedHttpSession.setAttribute(WrappedHttpSession.java:59) ~[vaadin-server-8.0.3.jar:8.0.3]
	at com.vaadin.server.VaadinService.reinitializeSession(VaadinService.java:1124) ~[vaadin-server-8.0.3.jar:8.0.3]`

when debugging i can determine that the 'oldSession' and 'newSession' seem to wrap the same session at this location in Vaadinservice:
lines 1114-1118
'  // Invalidate the current session
        oldSession.invalidate();

        // Create a new session
        WrappedSession newSession = request.getWrappedSession();
'
I am supecting something to do with Atmosphere, as this is where the new Wrapped session seems to get its session....

**Comment by ricardovm** [comment]
This new Atmosphere seems to have some problems with session handling.

**Comment by Artur-** [comment]
Is this about using websockets vs not using websockets? In 8.0.2 websockets do not work, it will fall back to long-polling and session access works in a different way (HTTP request vs websocket message). My guess is that this works the same way in 8.0.3+ if you use `@Push(transport=LONG_POLLING)`
