### ISSUE TITLE
vaadin-server-7.7.7: NullPointerException at AbstractClientConnector.detach(AbstractClientConnector.java:640)

### ISSUE THREAD

**Issue by maksym72** [vaadin/framework#8941]
The full stack trace of the error:

Mar 23, 2017 6:36:37 PM com.vaadin.ui.UI setSession
WARNING: Error while detaching UI from session
java.lang.NullPointerException
	at java.util.LinkedList$ListItr.next(LinkedList.java:893)
	at com.vaadin.server.AbstractClientConnector.detach(AbstractClientConnector.java:640)
	at com.vaadin.ui.AbstractComponent.detach(AbstractComponent.java:701)
	at com.vaadin.server.AbstractClientConnector.detach(AbstractClientConnector.java:641)
	at com.vaadin.ui.AbstractComponent.detach(AbstractComponent.java:701)
	at com.vaadin.server.AbstractClientConnector.detach(AbstractClientConnector.java:641)
	at com.vaadin.ui.AbstractComponent.detach(AbstractComponent.java:701)
	at com.vaadin.server.AbstractClientConnector.detach(AbstractClientConnector.java:641)
	at com.vaadin.ui.AbstractComponent.detach(AbstractComponent.java:701)
	at com.vaadin.server.AbstractClientConnector.detach(AbstractClientConnector.java:641)
	at com.vaadin.ui.AbstractComponent.detach(AbstractComponent.java:701)
	at com.vaadin.server.AbstractClientConnector.detach(AbstractClientConnector.java:641)
	at com.vaadin.ui.AbstractComponent.detach(AbstractComponent.java:701)
	at com.vaadin.ui.UI.detach(UI.java:1307)
	at smartway.checkpoint.ui.BusAwareUI.detach(BusAwareUI.java:28)
	at com.vaadin.ui.UI.setSession(UI.java:462)
	at com.vaadin.server.VaadinSession.removeUI(VaadinSession.java:871)
	at com.vaadin.server.VaadinService$2.run(VaadinService.java:1201)
	at com.vaadin.ui.UI.accessSynchronously(UI.java:1392)
	at com.vaadin.server.VaadinService.removeClosedUIs(VaadinService.java:1196)
	at com.vaadin.server.VaadinService.cleanupSession(VaadinService.java:1160)
	at com.vaadin.server.VaadinService.requestEnd(VaadinService.java:1364)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1436)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:379)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:205)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Artur-** [comment]
How do you reproduce this? It looks like a problem of accessing UI without locking the session. Does `smartway.checkpoint.ui.BusAwareUI.detach` do something special? Try running the server with assertions enabled (`-ea`) and you will likely get a better error message of what goes wrong

**Comment by maksym72** [comment]
It happens when I restart application server environment (jetty 9) while UI still open in browser and do refresh(F5).
BusAwareUI.detach just calls the superclass UI.detach method. Nothing more.
