### ISSUE TITLE
all 8.0.4 samples/archetypes completely not work!

### ISSUE THREAD

**Issue by gravin** [vaadin/framework#8948]
i tried the tutorials as listed here 
https://vaadin.com/maven#start

but all doesnt work resulting in 

严重: A child container failed during start
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/app]]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:915)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:871)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1407)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1397)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/app]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:153)
	... 6 more
Caused by: java.lang.NoClassDefFoundError: com/vaadin/external/org/slf4j/LoggerFactory
	at org.atmosphere.util.IOUtils.<clinit>(IOUtils.java:58)

so a huge bug exits here 
Caused by: java.lang.NoClassDefFoundError: com/vaadin/external/org/slf4j/LoggerFactory

i dont know how do you publish a complete wrong release to mislead users.

i planned to save some time but it wasted me more!

Only use GitHub issues for bugs and feature requests.   
For general support from the community, see https://vaadin.com/forum

For bugs, please provide at minimum the following information:
- Vaadin version
- Description of the bug
- If possible, minimal reproducible example

**Comment by pleku** [comment]
Hello. Which tutorial you're referring to, works fine for me when I'm running
```
mvn -B archetype:generate -DarchetypeGroupId=com.vaadin -DarchetypeArtifactId=vaadin-archetype-application -DarchetypeVersion=8.0.4 -DgroupId=org.test -DartifactId=vaadin-app -Dversion=1.0-SNAPSHOT
cd vaadin-app
mvn package jetty:run
```

Further details you could add are you're operation system, and did you run the commands inside some IDE like Eclipse, IntelliJ Idea ?

**Comment by gravin** [comment]
still failed with error , after i added below to pom, it works. 

		<dependency>
			<groupId>com.vaadin.external.slf4j</groupId>
			<artifactId>vaadin-slf4j-jdk14</artifactId>
			<version>1.6.1</version>
		</dependency>



[INFO] Finished at: 2017-03-28T15:08:29+08:00
[INFO] Final Memory: 60M/412M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.jetty:jetty-maven-plugin:9.3.9.v20160517:run (default-cli) on project vaadin-app: Execution default-cli of goal org.eclipse.jetty:jetty-maven-plugin:9.3.9.v20160517:run failed: A required class was missing while executing org.eclipse.jetty:jetty-maven-plugin:9.3.9.v20160517:run: com/vaadin/external/org/slf4j/LoggerFactory
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.eclipse.jetty:jetty-maven-plugin:9.3.9.v20160517
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy

**Comment by tsuoanttila** [comment]
Replicated test project with command from @pleku. Works in my environment as well, no stacktraces. Can you be more specific which archetype you are running, have you made any code changes or added dependencies?

**Comment by gravin** [comment]
didnt change anything, you can try running this one.
https://github.com/vaadin/tutorial/
by added below dependency will be ok
	<dependency>
		<groupId>com.vaadin.external.slf4j</groupId>
		<artifactId>vaadin-slf4j-jdk14</artifactId>
		<version>1.6.1</version>
	</dependency>

**Comment by elmot** [comment]
Works for me, Vaadin-8.0.4, java 1.8, Windows 7 64bit.
The initial stack trace looks a bit strange, since the tutorial uses jetty as a web container but the stacktrace is generated by tomcat (org.apache.catalina).
Looks like something is wrong with your maven or eclipse configuration.
`vaadin-slf4j-jdk14` artifact is a transitive dependency for `vaadin-push` through Atmosphere. There is nothing wrong with those dependencies.

Please clean up your maven cache and try again. 

I close the ticket, and if you still have problems, please share your project at github or bitbucket and reopen the ticket.
