### ISSUE TITLE
@SessionScoped injection not working with @Push enabled (8.0.3+)

### ISSUE THREAD

**Issue by ricardovm** [vaadin/framework#8967]
- Vaadin version: 8.0.3+ and WildFly 10.1.0

- Description of the bug

Using CDI, injection of a SessionScoped bean not working on events. Until 8.0.2, using a session bean on listeners works fine. But since 8.0.3 it doesn't work anymore. More precisely, since new Atmosphere (2.4.5.vaadin2) on #8785 

Without @Push it works.

```
14:33:16,090 SEVERE [com.vaadin.server.DefaultErrorHandler] (default task-9) : org.jboss.weld.context.ContextNotActiveException: WELD-001303: No active contexts for scope type javax.enterprise.context.SessionScoped
	at org.jboss.weld.manager.BeanManagerImpl.getContext(BeanManagerImpl.java:689)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.getIfExists(ContextualInstanceStrategy.java:90)
	at org.jboss.weld.bean.ContextualInstanceStrategy$CachingContextualInstanceStrategy.getIfExists(ContextualInstanceStrategy.java:165)
	at org.jboss.weld.bean.ContextualInstance.getIfExists(ContextualInstance.java:63)
	at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:83)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:125)
	at com.linkhos.tests.sessions.UserSession$Proxy$_$$_WeldClientProxy.getHello(Unknown Source)
	at com.linkhos.tests.sessions.MainUI.lambda$init$6de4602$1(MainUI.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:211)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:174)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1029)
	at com.vaadin.ui.Button.fireClick(Button.java:370)
	at com.vaadin.ui.Button$1.click(Button.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:116)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:445)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:410)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274)
	at com.vaadin.server.communication.PushHandler.lambda$new$71(PushHandler.java:145)
	at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:235)
	at com.vaadin.server.communication.PushHandler.onMessage(PushHandler.java:489)
	at com.vaadin.server.communication.PushAtmosphereHandler.onMessage(PushAtmosphereHandler.java:87)
	at com.vaadin.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:77)
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:223)
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:115)
	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:68)
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2284)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:593)
	at org.atmosphere.websocket.DefaultWebSocketProcessor$3.run(DefaultWebSocketProcessor.java:345)
	at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:340)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:447)
	at org.atmosphere.container.JSR356Endpoint$3.onMessage(JSR356Endpoint.java:260)
	at org.atmosphere.container.JSR356Endpoint$3.onMessage(JSR356Endpoint.java:257)
	at io.undertow.websockets.jsr.FrameHandler$7.run(FrameHandler.java:283)
	at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:162)
	at io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:159)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.websockets.jsr.ServerWebSocketContainer.invokeEndpointMethod(ServerWebSocketContainer.java:575)
	at io.undertow.websockets.jsr.ServerWebSocketContainer$6.run(ServerWebSocketContainer.java:561)
	at io.undertow.websockets.jsr.OrderedExecutor$ExecutorTask.run(OrderedExecutor.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

- If possible, minimal reproducible example

```java
@SessionScoped
public class MySessionScoped {
    private Instant sessionInit = Instant.now();

    public String getHello() {
        return "Hello! Session started at: " + sessionInit;
    }
}

@CDIUI("main")
@Push
public class MyUI extends UI
    @Inject
    MySessionScoped bean;

    protected void init(VaadinRequest request) {
        // This works
        Label helloLabel = bean.getHello();

        // This listener doesn't work
        Button showButton = new Button("Show", e -> helloLabel.setValue(bean.getHello()));

        setContent(new VerticalLayout(helloLabel, showButton));
}
```

A complete example: https://github.com/ricardovm/session-problem-vaadin

**Comment by Artur-** [comment]
The example project uses 8.0.2 which suffers from #8734  and therefore websockets do not work. It will fallback to long polling, which makes session scoped beans work because long polling uses normal HTTP requests. 

For 8.0.3+ websockets will work as expected, with the drawback that websockets do not enable SessionScope. See https://github.com/vaadin/cdi/issues/88 and the spec issue at https://java.net/jira/browse/WEBSOCKET_SPEC-196

**Comment by ricardovm** [comment]
In most situations, @UIScoped should be enough. If it's a CDIxWS spec problem, I'll go with UIScoped until they solve this. Is it possible to display this in a exception message and documentation?

**Comment by Artur-** [comment]
Although I am not sure, I would be surprised if `@UIScoped` would work as UIs are part of the session. The workaround for this is to use `@Push(transport=WEBSOCKET_XHR)` or alternatively `transport=LONG_POLLING` - with these options the client->server requests are sent as HTTP requests and all CDI scopes work as expected

**Comment by ricardovm** [comment]
`@UIScoped` works fine. `VaadinService.getCurrentRequest().getWrappedSession()` works too. Just `@SessionScoped` don't.

**Comment by mrts** [comment]
@Artur-, in vaadin/cdi#88 @hesara wrote

> *Known CDI issues with push (including with web sockets) have been resolved. Note that this only concerns @UIScoped and @ViewScoped beans - request and session scopes are not supported with web sockets in CDI 1.0.*

So one would presume that `@UIScoped` should work. It's also used in the [official CDI tutorial](https://github.com/vaadin/cdi-tutorial/blob/f402b2759d722e2f0efca199cac7143f8059fb18/src/main/java/com/vaadin/cdi/tutorial/ChatView.java#L33) along with `@Push` (where [`UserInfo` is `@UIScoped`](https://github.com/vaadin/cdi-tutorial/blob/f402b2759d722e2f0efca199cac7143f8059fb18/src/main/java/com/vaadin/cdi/tutorial/UserInfo.java)).

However, given the following `@CDIUI`, `@CDIView` and `@UIScoped` classes

```java
@Push
@CDIUI("")
public class UIScopedInjectionTestUI extends UI {

    @Inject
    private CDIViewProvider cdiViewProvider;

    ...
}

@CDIView("default")
public class DefaultView extends VerticalLayout implements View {

    @Inject
    private UserSessionData userSessionData;

    ...
}

@UIScoped
public class UserSessionData implements Serializable {
    ...
}
```

I get the following error in WildFly 10.1.0

```
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies 
for type UserSessionData with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private com.uiscopedinjectiontest.DefaultView.userSessionData
  at com.uiscopedinjectiontest.DefaultView.userSessionData(DefaultView.java:0)
```
Example code [here](https://gitlab.com/mrts/vaadin-javaee-uiscoped-injection-test).

@ricardovm, did `@UIScoped` work for you in a `@CDIView`?

Did I miss anything or should I file another bug?

**Comment by mrts** [comment]
Note that there is an ongoing discussion how to get this fixed in Java EE 9 here:
https://javaee.groups.io/g/websocket-spec/topic/websocket_spec_security_and/5842413

@Artur-, could Vaadin representatives also voice share their perspective in the discussion?

**Comment by TatuLund** [comment]
I closed this, since CDI add-on 3.0.0 provides workaround via @VaadinSessionScoped and https://github.com/vaadin/framework/issues/8734 and https://github.com/vaadin/cdi/issues/88 are closed.

**Comment by janhuba** [comment]
I have never seen the example how to workaround @CDIView in Vaadin 8 with @VaadinSessionScoped. Can you pls send a link?

**Comment by TatuLund** [comment]
Here is an example app, which uses it, i.e. there is a bean with @VaadinSessionScoped annotation

https://github.com/TatuLund/cdi-demo/blob/master/src/main/java/org/vaadin/cdidemo/data/UserProfileHolderImpl.java#L16

and it is used for example here

https://github.com/TatuLund/cdi-demo/blob/master/src/main/java/org/vaadin/cdidemo/views/login/LoginPresenter.java#L27

I recommend to download the whole app and play with it, it demonstrates the most typical CDI cases with Vaadin app.
