### ISSUE TITLE
Calling "clearFilters" in empty grid throws NullpointerException

### ISSUE THREAD

**Issue by sebastianfilke** [vaadin/framework#9073]
- Vaadin version: 8.0.5

If you have an empty grid and call "clearFilters" of your ListDataProvider throws NullPointerException.
For sure you have to set the ListeDataProvider first:

```
listDataProviderResponsibility = new ListDataProvider<ResponsibilityDto>(responsibilityDtos);
gridResponsibility.setDataProvider(listDataProviderResponsibility);

listDataProviderResponsibility.clearFilters();
```

```
2017-04-12T16:22:13.824+0200|Schwerwiegend: java.lang.NullPointerException
	at de.alegria.qkiss.webportal.ui.responsibility.ResponsibilityViewImpl.updateAllFilter(ResponsibilityViewImpl.java:222)
	at de.alegria.qkiss.webportal.ui.responsibility.ResponsibilityViewImpl.lambda$14(ResponsibilityViewImpl.java:216)
	at com.vaadin.ui.ComboBox.lambda$addValueChangeListener$bddd7469$1(ComboBox.java:681)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:211)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:174)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1029)
	at com.vaadin.ui.AbstractSingleSelect.setSelectedFromClient(AbstractSingleSelect.java:238)
	at com.vaadin.ui.ComboBox.setSelectedFromClient(ComboBox.java:835)
	at com.vaadin.ui.AbstractSingleSelect$1.select(AbstractSingleSelect.java:384)
	at sun.reflect.GeneratedMethodAccessor1157.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:116)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:445)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:410)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:274)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1464)
	at com.vaadin.cdi.server.VaadinCDIServletService.handleRequest(VaadinCDIServletService.java:92)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:381)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
	at org.apache.catalina.core.StandardContextValve.__invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:416)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:283)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:283)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:200)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:132)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:111)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:536)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Legioth** [comment]
Hi. According to the stacktrace, the null pointer exception comes from the application's own code (`de.alegria.qkiss.webportal.ui.responsibility.ResponsibilityViewImpl.updateAllFilter`) and not from any code directly related with Grid itself. What does line 222 of `ResponsibilityViewImpl.java ` do?

**Comment by sebastianfilke** [comment]
This bug is related to this forum post: https://vaadin.com/forum/#!/thread/14870720/15560243
I try to implement a generic filter generator for a headerrow in a grid.


The exception directly occured if i call `listDataProviderResponsibility.clearFilters();` in line 222 if there are no items in the listdataprovider. If i have 1 item in the list, everything works fine.

[ResponsibilityViewImpl.txt](https://github.com/vaadin/framework/files/918952/ResponsibilityViewImpl.txt)
This is my code snippet. The whole class is attached.
```
	private void addGridFilters() {
		final HeaderRow filterRow = gridResponsibility.appendHeaderRow();
		for (final Column<ResponsibilityDto, ?> column : gridResponsibility.getColumns()) {
			final HeaderCell headerCell = filterRow.getCell(column);

			if (!columnResponsibilityPool.equals(column.getId()) && !columnResponsibilityDisabled.equals(column.getId())) {
				headerCell.setComponent(createFilterTextField(column));
			} else if (columnResponsibilityPool.equals(column.getId()) || columnResponsibilityDisabled.equals(column.getId())) {
				headerCell.setComponent(createFilterComboBox(column));
			}
		}
	}

	private TextField createFilterTextField(final Column<ResponsibilityDto, ?> column) {
		final TextField tfFilter = new TextField();
		tfFilter.setPlaceholder(tp.getText(TextKey.VIEW_TEXTFIELD_FILTER));
		tfFilter.addStyleName(ValoTheme.TEXTFIELD_TINY);
		tfFilter.setWidth(100, Unit.PERCENTAGE);
		tfFilter.addValueChangeListener(event -> {
			updateAllFilter();
		});
		return tfFilter;
	}

	private ComboBox<BooleanFilterBean> createFilterComboBox(final Column<ResponsibilityDto, ?> column) {
		final ComboBox<BooleanFilterBean> cbFilter = new ComboBox<BooleanFilterBean>();
		cbFilter.setPlaceholder(tp.getText(TextKey.VIEW_COMBOBOX_FILTER));
		cbFilter.setItemIconGenerator(BooleanFilterBean::getFilterIcon);
		cbFilter.setItemCaptionGenerator(BooleanFilterBean::getFilterName);
		cbFilter.addStyleName(ValoTheme.COMBOBOX_TINY);
		cbFilter.setWidth(100, Unit.PERCENTAGE);
		cbFilter.setTextInputAllowed(false);

		cbFilter.setItems(new BooleanFilterBean(true, tp.getText(TextKey.VIEW_COMBOBOX_FILTER_YES), VaadinIcons.CHECK_SQUARE_O),
				new BooleanFilterBean(false, tp.getText(TextKey.VIEW_COMBOBOX_FILTER_NO), VaadinIcons.THIN_SQUARE));

		cbFilter.addValueChangeListener(event -> {
			updateAllFilter();
		});
		return cbFilter;
	}

	private void updateAllFilter() {
		listDataProviderResponsibility.clearFilters();

		final HeaderRow filterRow = gridResponsibility.getHeaderRow(1);
		for (final Column<ResponsibilityDto, ?> column : gridResponsibility.getColumns()) {
			final ValueProvider<ResponsibilityDto, String> valueProvider = (ValueProvider<ResponsibilityDto, String>) column.getValueProvider();
			final HeaderCell headerCell = filterRow.getCell(column);

			if (!columnResponsibilityPool.equals(column.getId()) && !columnResponsibilityDisabled.equals(column.getId())) {
				final TextField textField = (TextField) headerCell.getComponent();

				if (textField.getValue() != null && !textField.getValue().isEmpty()) {
					listDataProviderResponsibility.addFilter(valueProvider, value -> {
						return value.toLowerCase().contains(textField.getValue().toLowerCase());
					});
				}
			} else if (columnResponsibilityPool.equals(column.getId()) || columnResponsibilityDisabled.equals(column.getId())) {
				final ComboBox<BooleanFilterBean> comboBox = (ComboBox<BooleanFilterBean>) headerCell.getComponent();

				if (comboBox.getValue() != null) {
					listDataProviderResponsibility.addFilter(valueProvider, value -> {
						if (value.toString().contains(VaadinIcons.CHECK_SQUARE_O.getHtml()) && comboBox.getValue().isFilterValue()) {
							return true;
						} else if (value.toString().contains(VaadinIcons.THIN_SQUARE.getHtml()) && !comboBox.getValue().isFilterValue()) {
							return true;
						}
						return false;
					});
				}
			}
		}
		listDataProviderResponsibility.refreshAll();
	}

	@Override
	public void addAllResponsibilities(List<ResponsibilityDto> responsibilityDtos) {
		listDataProviderResponsibility = new ListDataProvider<ResponsibilityDto>(responsibilityDtos);
		gridResponsibility.setDataProvider(listDataProviderResponsibility);

		lLastUpdate.setValue(tp.getText(TextKey.VIEW_LABEL_LASTUPDATE, new Date()));
	}
```

**Comment by Legioth** [comment]
The line that triggers the NPE is `listDataProviderResponsibility.clearFilters();`. The only reasonable way for that line to directly cause an NPE is if `listDataProviderResponsibility` is `null`. What's the relationship between that field being `null` and not having any items in the data provider?

**Comment by sebastianfilke** [comment]
Okay you're right. This was my fault. Please close this issue!
