### ISSUE TITLE
com.vaadin.data.Binder should skip synthetic members

### ISSUE THREAD

**Issue by OldIMP** [vaadin/framework#9504]
- Vaadin version: 8.0.6
- Description of the bug
Similar to #5294, **Binder** doesn't skip synthetic members. Therefore any unit test involving value change event will fail if run w/ [JaCoCo](http://www.eclemma.org/jacoco/trunk/doc/faq.html), which 
> instruments the classes under test which adds two members to the classes: A private static field $jacocoData and a private static method $jacocoInit(). Both members are marked as synthetic.

- If possible, minimal reproducible example
Run the following test w/ JaCoCo...
```java
import org.junit.Test;

import com.vaadin.data.Binder;
import com.vaadin.ui.TextField;

public class VaadinJacocoTest {
    private final TextField bar = new TextField();

    @Test
    public void test() {
        Binder<?> binder = new Binder<>();
        binder.bind(bar, o -> "bar", (foo, s) -> {});
        binder.addValueChangeListener(event -> {});

        bar.setValue("boom");
    }
}
```
will produce the following stack trace
```
com.vaadin.event.ListenerMethod$MethodException: Invocation of method valueChange in com.vaadin.data.Binder$BindingImpl$$Lambda$9/1464177809 failed.
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
	at java.lang.reflect.Method.invoke(Method.java:491)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:518)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:211)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:174)
	at com.vaadin.data.Binder.fireValueChangeEvent(Binder.java:2362)
	at com.vaadin.data.Binder.access$1300(Binder.java:96)
	at com.vaadin.data.Binder$BindingImpl.handleFieldValueChange(Binder.java:933)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:211)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:174)
	at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1029)
	at com.vaadin.ui.AbstractField.setValue(AbstractField.java:144)
	at com.vaadin.ui.AbstractTextField.setValue(AbstractTextField.java:97)
```

**Comment by hesara** [comment]
Binder.addValueChangeListener() and Binder.addStatusChangeListener() currently assume that the corresponding interfaces only have one method, and probably should look for the correct method instead.

**Comment by OldIMP** [comment]
Tested w/ Vaadin 8.1.7 and works fine. Is Milestone 8.2.0.alpha3 correct?
