### ISSUE TITLE
TreeGrid.scrollTo(int) always throws an exception

### ISSUE THREAD

**Issue by mvysny** [vaadin/framework#9579]
Vaadin 8.1.0-beta2:

```
Caused by: java.lang.IllegalArgumentException: Hierarchical data provider doesn't support non-hierarchical queries
	at com.vaadin.data.provider.HierarchicalDataProvider.size(HierarchicalDataProvider.java:51)
	at com.vaadin.ui.Grid.scrollTo(Grid.java:3714)
```

**Comment by sabesoft-jeff** [comment]
+1 on this.  This is a hard bug.

**Comment by Hedath** [comment]
You can override the scrollTo method as a hotfix:
```
    @Override
    public void scrollTo(int row, ScrollDestination destination) {
        Objects.requireNonNull(destination,
                "ScrollDestination can not be null");

        getRpcProxy(GridClientRpc.class).scrollToRow(row, destination);
    }
```

**Comment by wbadam** [comment]
This issue is fixed in https://github.com/vaadin/framework/pull/10005
