### ISSUE TITLE
Cannot get description attribute for Tree

### ISSUE THREAD

**Issue by tanbt** [vaadin/framework#9670]
Vaadin Framework version 8.1.0.rc1 shows exception when **Vaadin Designer** was trying to get description attribute of ```com.vaadin.ui.Tree```, because there is no implementation of ```getDescription()``` for Tree.

```
Jul 12, 2017 10:17:09 AM com.vaadin.ui.declarative.DesignAttributeHandler writeAttribute
SEVERE: Failed to invoke getter for attribute description
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.ui.declarative.DesignAttributeHandler.writeAttribute(DesignAttributeHandler.java:213)
	at com.vaadin.ui.AbstractComponent.writeDesign(AbstractComponent.java:1281)
	at com.vaadin.ui.declarative.DesignContext.createElement(DesignContext.java:485)
	at com.vaadin.designer2.model.vaadin.DesignerDesignContext.createElement(DesignerDesignContext.java:93)
	at com.vaadin.ui.declarative.Design.createHtml(Design.java:550)
	at com.vaadin.ui.declarative.Design.write(Design.java:791)
	at com.vaadin.designer2.model.vaadin.VaadinComponentSource.write(VaadinComponentSource.java:335)
	at com.vaadin.designer2.intellij.util.VaadinUtil.createSnippetFromSource(VaadinUtil.java:145)
	at com.vaadin.designer2.intellij.util.VaadinUtil.getComponentTemplateSnippet(VaadinUtil.java:110)
	at com.vaadin.designer2.intellij.palette.PalettePanel$ComponentTransferHandler.createTransferable(PalettePanel.java:341)
	at javax.swing.TransferHandler$DragHandler.dragGestureRecognized(TransferHandler.java:1601)
	at java.awt.dnd.DragGestureRecognizer.fireDragGestureRecognized(DragGestureRecognizer.java:361)
	at javax.swing.TransferHandler$SwingDragGestureRecognizer.gestured(TransferHandler.java:1669)
	at javax.swing.TransferHandler.exportAsDrag(TransferHandler.java:744)
	at javax.swing.plaf.basic.DragRecognitionSupport.mouseDraggedImpl(DragRecognitionSupport.java:174)
	at javax.swing.plaf.basic.DragRecognitionSupport.mouseDragged(DragRecognitionSupport.java:91)
	at javax.swing.plaf.basic.BasicListUI$Handler.mouseDragged(BasicListUI.java:2757)
	at java.awt.AWTEventMulticaster.mouseDragged(AWTEventMulticaster.java:319)
	at java.awt.AWTEventMulticaster.mouseDragged(AWTEventMulticaster.java:319)
	at java.awt.AWTEventMulticaster.mouseDragged(AWTEventMulticaster.java:319)
	at java.awt.AWTEventMulticaster.mouseDragged(AWTEventMulticaster.java:319)
	at java.awt.Component.processMouseMotionEvent(Component.java:6581)
	at javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3342)
	at java.awt.Component.processEvent(Component.java:6302)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4542)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.UnsupportedOperationException: A composite has no DOM or widget
	at com.vaadin.ui.Composite.getDescription(Composite.java:304)
	... 59 more
```

**Comment by elmot** [comment]
There is a bunch of Component properties blocked in Composite (caption, captionAsHtml etc ). We need to implement them for `Tree` or for `Composite`
