### ISSUE TITLE
NPE FileUploadHandler.handleRequest

### ISSUE THREAD

**Issue by dzkras** [vaadin/framework#9677]
Vaadin version 7.7.3
Description of the bug:

By some condition it is possible to get the NPE by file uploding form. As a result it commes Servlet Exception.

```
Warnung:   StandardWrapperValve[DataToolUIServlet]: Servlet.service() for servlet DataToolUIServlet threw exception
Schwerwiegend:   java.lang.NullPointerException
	at com.vaadin.server.communication.FileUploadHandler.handleRequest(FileUploadHandler.java:286)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1422)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:379)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	...
	at java.lang.Thread.run(Thread.java:745)
```

It is possible to reproduce the exception, if you try to open action Link directly in Browser, f.e:
https://xxxxxxxx xxxx.com/APP/UPLOAD/10/1135/action/2a4be696-4021-4a1f-9b1b-8b4ccf8f7de41

**Comment by enver-haase** [comment]
Happens when VaadinRequest.getContentType() returns NULL, so if that could be worked around, that would help.
The code is very similar still in Vaadin Framework 8.2.1 so I suspect the bug is still valid.

**Comment by dtsaryov** [comment]
We've also encountered this problem.

Error on browser console:
```
XML Parsing Error: syntax error
Location: http://localhost:8080/app/APP/UPLOAD/0/169/uploadUrl/e4186155-3a9a-4734-bbb9-812ed84b5fc1
Line Number 1, Column 1:
```

Stacktrace:
```
    javax.servlet.ServletException: com.vaadin.server.ServiceException: java.lang.NullPointerException
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:427)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.serviceAppRequest(CubaApplicationServlet.java:329)
	at com.haulmont.cuba.web.sys.CubaApplicationServlet.service(CubaApplicationServlet.java:215)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:107)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:73)
	at com.haulmont.cuba.web.sys.CubaHttpFilter.doFilter(CubaHttpFilter.java:93)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:836)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1747)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.vaadin.server.ServiceException: java.lang.NullPointerException
	at com.vaadin.server.VaadinService.handleExceptionDuringRequest(VaadinService.java:1630)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1590)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	... 30 more
Caused by: java.lang.NullPointerException
	at com.vaadin.server.communication.FileUploadHandler.handleRequest(FileUploadHandler.java:293)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1578)
	... 31 more
```

**Comment by TatuLund** [comment]
This could be potentially fixed by https://github.com/vaadin/framework/pull/11745 in Vaadin 8.9.2
