### ISSUE TITLE
BeanPropertySet's getProperty(name) method is not able to find a nested property which is listed by its own getProperties() method

### ISSUE THREAD

**Issue by muammerYucel** [vaadin/framework#9960]
Vaadin Version: 8.1.3

```
@Theme("mytheme")
public class MyUI extends UI {

	@Override
	protected void init(VaadinRequest vaadinRequest) {

		Grid<Foo> grid = new Grid<>(Foo.class);
		grid.setColumns("bar.name");
		grid.setItems(new Foo("X"), new Foo("Y"), new Foo("Z"));
		setContent(grid);
	}

	public static class Foo {

		private Bar bar;

		public Foo(String name) {
			super();
			this.bar = new Bar(name);
		}

		public Bar getBar() {
			return bar;
		}
	}

	public static class Bar {

		private String name;

		public Bar(String name) {
			super();
			this.name = name;
		}

		public String getName() {
			return name;
		}
	}

	@WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
	@VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
	public static class MyUIServlet extends VaadinServlet {
	}
}

```
Run the given UI. Everything is perfect. Refresh the web page. As you can see, "bar.name" property is stored in definitions map with key "bar.name". But, its nested bean property definition returns "name" as property name. The result of getProperties() method is iterated and properties requested by their names during the grid initialization. As a result, definition map contains the nested property definition with key "bar.name", and it is not reachable by property name.

```
java.lang.IllegalArgumentException: Could not resolve property name name from Property set for bean com.pany.MyUI$Foo
	at com.vaadin.ui.Grid.lambda$addColumn$0(Grid.java:2537)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.vaadin.ui.Grid.addColumn(Grid.java:2537)
	at com.vaadin.ui.Grid.addColumn(Grid.java:2507)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1620)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.vaadin.ui.Grid.<init>(Grid.java:2370)
	at com.vaadin.ui.Grid.<init>(Grid.java:2323)
	at com.vaadin.ui.Grid.<init>(Grid.java:2280)
	at com.vaadin.ui.Grid.<init>(Grid.java:2261)
	at com.pany.MyUI.init(MyUI.java:27)
	at com.vaadin.ui.UI.doInit(UI.java:745)
	at com.vaadin.server.communication.UIInitHandler.getBrowserDetailsUI(UIInitHandler.java:216)
	at com.vaadin.server.communication.UIInitHandler.synchronizedHandleRequest(UIInitHandler.java:74)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1568)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:381)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)


```

**Comment by stadler** [comment]
An ugly but functioning workaround for this problem is to invoke the following method before each invocation of a Grid constructor:
```
    private static void clearBeanPropertySetCacheForClass(Class<?> beanType) {
        Field instancesField = ReflectionUtils.findField(BeanPropertySet.class, "instances");
        instancesField.setAccessible(true);
        try {
            ConcurrentMap<Class<?>, BeanPropertySet<?>> instances = (ConcurrentMap<Class<?>, BeanPropertySet<?>>) instancesField.get(null);
            instances.remove(beanType);
        } catch (IllegalAccessException e) {
            throw new RuntimeException("Unable to clear BeanPropertySet cache for class: " + beanType.getSimpleName(), e);
        }
    }
```

**Comment by stadler** [comment]
With Vaadin 8.2 this issue still remains. Even worse, the above mentioned workaround is no longer possible, as the Key of the ConcurrentMap has become a private class `InstanceKey` which makes it even harder to remove the cached class.
As an even uglier and slower workaround one can now do the following:
```
    public static void clearBeanPropertySetCacheForClass(Class<?> beanType) {
        Field instancesField = ReflectionUtils.findField(BeanPropertySet.class, "INSTANCES");
        instancesField.setAccessible(true);
        try {
            ConcurrentMap<?, ?> instances = (ConcurrentMap<?, ?>) instancesField.get(null);
            Object instanceKeyForBeanType = createInstanceKeyInstance(beanType);
            instances.remove(instanceKeyForBeanType);
        } catch (ReflectiveOperationException e) {
            throw new RuntimeException("Unable to clear BeanPropertySet cache for class: " + beanType.getSimpleName(),
                    e);
        }
    }

    /**
     * Dirty hack, needed since Vaadin 8.2, to create an instance of the private inner class BeanPropertySet#InstanceKey.
     * @see #clearBeanPropertySetCacheForClass(Class).
     */
    private static Object createInstanceKeyInstance(Class<?> beanType) throws ReflectiveOperationException {
        String expectedClassName = "InstanceKey";
        Class<?> innerClass = Arrays.stream(BeanPropertySet.class.getDeclaredClasses())
                .filter(declaredClass -> declaredClass.getSimpleName().equals(expectedClassName))
                .findFirst()
                .orElseThrow(() -> new RuntimeException(
                        "Expected nested class: '" + expectedClassName + "' to be present in class BeanPropertySet."));
        Constructor<?> constructor = innerClass.getDeclaredConstructors()[0];
        constructor.setAccessible(true);
        return constructor.newInstance(beanType, false, 0, null);
    }
```

Here a simple Test to reproduce this issue:
```
public class VaadinIssue9960GridWithNestedPropertiesBrokenTest {

    class Person {
        Address address;

        public Address getAddress() {
            return address;
        }
    }
    class Address {
        String street;

        public String getStreet() {
            return street;
        }

    }

    @Test
    public void createWithConstructorReturnsExceptionForNestedProperties() {
        // Create Grid for class that is not cached in BeanPropertySet works
        new Grid<>(Person.class);

        // Access a nested property which will get cached too for the PropertySet instance of Person.class
        assertThat(BeanPropertySet.get(Person.class).getProperty("address.street")).isPresent();

        // Now grids cannot be created anymore and will throw IllegalArgumentException with the message:
        // Could not resolve property name street from Property set for bean
        // VaadinIssue9960GridWithNestedPropertiesBrokenTest$Person
        new Grid<>(Person.class);
    }
}
```

**Comment by VittorioZinno** [comment]
We have problems to with this issue. Please solve it. Thanks.

**Comment by humb1t** [comment]
This problem ruins usage of Vaadin with `@Embedded` entities in spring data and DDD

**Comment by mcollovati** [comment]
It seems this has been fixed in 8.3

**Comment by stadler** [comment]
Indeed!

**Comment by TatuLund** [comment]
Yes, this was fixed by PR: https://github.com/vaadin/framework/pull/9925
